### ISSUE TITLE
Not a bug - where to donate?

### ISSUE THREAD

**Issue by AmbrosYTC** [mylinuxforwork/dotfiles#1]
I don't use discord or else I'd post it there.  Where can I make a donation to you and/or this project?  I really love the tremendous work you guys do, and although I don't have the ability to contribute my time or talent, I'd love to throw a couple bucks your way as a 'thank you!'

**Comment by mylinuxforwork** [comment]
Thanks for your offer. But I am not planning to open a donation platform. I am happy if you have fun with the dotfiles and you like my videos on YouTube: https://www.youtube.com/channel/UC0sUzmZ0CHvVCVrpRfGKZfw

**Comment by mylinuxforwork** [comment]
You can use Super Thanks below my videos if you want to donate. Thank you.
