### ISSUE TITLE
I can no longer access the Monitor Variations

### ISSUE THREAD

**Issue by MrBulldog684** [mylinuxforwork/dotfiles#100]
Hi Stephan, 

since updating to 2.9.5RL I can no longer access the Monitor Variations. When I try using the ML4W Welcome App/System/Monitor Variations and click on "Open Variations Folder" or "Edit current Variations" in the menu, nothing happens. Reload Variations doesn't change anything either. My  ~/dotfiles folder is also empty, I think I'm doing something wrong.

**Comment by mylinuxforwork** [comment]
Thanks for testing and reporting the bug. It’s a side effect from the new folder structure. Will fix it as soon as possible.
In the meanwhile you can edit the variation directly in dotfiles/.config/hypr/conf/monitors/

**Comment by MrBulldog684** [comment]
Ok great, thanks for your quick answer! I was now able to change it using the path you described.

**Comment by mylinuxforwork** [comment]
Thanks again for reporting this issue. It's fixed on the Rolling Release for 2.9.5.
