### ISSUE TITLE
[FEATURE]  On ML4W dotfiles upgrade restore previous settings for wallpaper, waybar 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#104]
**Is your feature request related to a problem? Please describe.**
 It's been a long standing issue, when upgrading dotfiles, wallpaper, waybar are set back to defaults. 

**Describe the solution you'd like**
 Keep the previous settings 

**Describe alternatives you've considered**
None  I end up having to reset manually.

**Comment by mylinuxforwork** [comment]
With 2.9.5 I will introduce a new cache folder https://github.com/mylinuxforwork/dotfiles/tree/main/dotfiles/.config/ml4w/cache
And it is prefilled with the default wallpaper. And this meeds to be removed if the cache folder already exists. 
Will check if I can restore from older versions into the new location and of course avoid overwriting.

**Comment by mylinuxforwork** [comment]
@dwilliam62 I assume you have updated to 2.9.5RC1. Please change your wallpaper and waybar theme. Can you run the installer with the rolling release again? Just checked the code and the wallpaper and waybar theme should be restored. When you restore the settings during the update.

**Comment by mylinuxforwork** [comment]
@dwilliam62 Just pushed an update to the main branch (rolling release). The restore of the wallpaper if you update 2.9.5 should work now. The update from 2.9.4 will fall back to the default.jpg.

**Comment by mylinuxforwork** [comment]
@dwilliam62 And another push. The installer should also now restore the wallpaper from 2.9.4 during the update.

**Comment by dwilliam62** [comment]
I just tested it. works great!  Even the custom color them I created using wal -i IMAGE was restored!    NICE!
