### ISSUE TITLE
[FEATURE]  Don't hard code firefox as the waybar browser set it "Browse Internet" then use the default browser defined

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#105]
**Is your feature request related to a problem? Please describe.**
 Not everyone uses firefox and having a dedicated waybar icon for it is wasteful IMO

**Describe the solution you'd like**
Instead make it generic like "Browse Internet" or "Open browser" and use the defined default browser instead

**Describe alternatives you've considered**
Having to edit the waybar config is wasteful since the next update will reset it

**Comment by dwilliam62** [comment]
Also it appears you are installing firefox by default?    During the install I recall being asked and saying no.

**Comment by mylinuxforwork** [comment]
@dwilliam62 Hi. The Waybar Quicklinks can be edited as described here. And the Quicklinks can be restored/protected during the update. 
https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks

**Comment by dwilliam62** [comment]
I understand My suggestion is that since I am setting the default browser in your app,  why should I also have to edit the quick links?   Same for filemgr,  ideally the links should inherit those settings

**Comment by dwilliam62** [comment]
One problem is I don't have a .settings/waybar-quicklins.json 
![image](https://github.com/user-attachments/assets/c4f8a392-a2d8-435d-885f-41040482d931)

I have always used  ~/src/dotfiles as my install from DIR.   When you added the mulitple locations I accepted the default of ~/dotfiles.  

the .settings is in ~/src/dotfiles/.settings. 

Is there an easy way to correct that ?

**Comment by dwilliam62** [comment]
![image](https://github.com/user-attachments/assets/025f3c8e-d62f-4780-bdd6-a3c9f8d74c98)

**Comment by dwilliam62** [comment]
that's  ~/src/dotfiles/dotfiles

**Comment by mylinuxforwork** [comment]
> that's ~/src/dotfiles/dotfiles

The installer creates the dotfiles folder within your home directory. The .settings folder doesn’t exists anymore . It is now in dotfiles/.config/ml4w/settings

The new structure mirrors the real folders starting from your home directory to be compatible with GNU stow.  

Please check
https://github.com/mylinuxforwork/dotfiles/wiki/Activate-another-ML4W-Dotfiles-installation

and 

https://github.com/mylinuxforwork/dotfiles/wiki/Using-ML4W-Dotfiles-on-other-distributions

**Comment by dwilliam62** [comment]
OK I will check that.  However the link you provided earlier points to that location

![image](https://github.com/user-attachments/assets/b338a942-02df-4050-bc9a-8ce86f7955cf)

So you should update that link.

**Comment by mylinuxforwork** [comment]
> OK I will check that. However the link you provided earlier points to that location
> 
> ![image](https://private-user-images.githubusercontent.com/129223418/355933859-b338a942-02df-4050-bc9a-8ce86f7955cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg5MTEsIm5iZiI6MTcyMzA1ODYxMSwicGF0aCI6Ii8xMjkyMjM0MTgvMzU1OTMzODU5LWIzMzhhOTQyLTAyZGYtNDA1MC1iYzlhLThjZTg2Zjc5NTVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTc5NDQxMDA3YmQyYWRkODBkZDg3OTllYWQ2ZDVjMGVjYjI5NWQxZWZjMGY4OGM5MjkxZGNkNTlhODgxMzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FXuuaJtN1gR7dZC-4usyelr5xtpMqnWkoaojMMMRnME)
> 
> So you should update that link.

Which link do you mean?

**Comment by dwilliam62** [comment]
> > OK I will check that. However the link you provided earlier points to that location
> > ![image](https://private-user-images.githubusercontent.com/129223418/355933859-b338a942-02df-4050-bc9a-8ce86f7955cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg5MTEsIm5iZiI6MTcyMzA1ODYxMSwicGF0aCI6Ii8xMjkyMjM0MTgvMzU1OTMzODU5LWIzMzhhOTQyLTAyZGYtNDA1MC1iYzlhLThjZTg2Zjc5NTVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTc5NDQxMDA3YmQyYWRkODBkZDg3OTllYWQ2ZDVjMGVjYjI5NWQxZWZjMGY4OGM5MjkxZGNkNTlhODgxMzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FXuuaJtN1gR7dZC-4usyelr5xtpMqnWkoaojMMMRnME)
> > So you should update that link.
> 
> Which link do you mean?

This one you sent earlier to mod the quicklinks

https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks

That link references the location I said above that I don't have .dotfiles/settings/waybar......

![image](https://github.com/user-attachments/assets/2bfa5771-93bd-476a-9a51-ee70f467d5f5)

**Comment by mylinuxforwork** [comment]
> > > OK I will check that. However the link you provided earlier points to that location
> > > ![image](https://private-user-images.githubusercontent.com/129223418/355933859-b338a942-02df-4050-bc9a-8ce86f7955cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg5MTEsIm5iZiI6MTcyMzA1ODYxMSwicGF0aCI6Ii8xMjkyMjM0MTgvMzU1OTMzODU5LWIzMzhhOTQyLTAyZGYtNDA1MC1iYzlhLThjZTg2Zjc5NTVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTc5NDQxMDA3YmQyYWRkODBkZDg3OTllYWQ2ZDVjMGVjYjI5NWQxZWZjMGY4OGM5MjkxZGNkNTlhODgxMzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FXuuaJtN1gR7dZC-4usyelr5xtpMqnWkoaojMMMRnME)
> > > So you should update that link.
> > 
> > 
> > Which link do you mean?
> 
> This one you sent earlier to mod the quicklinks
> 
> https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks
> 
> That link references the location I said above that I don't have .dotfiles/settings/waybar......
> 
> ![image](https://private-user-images.githubusercontent.com/129223418/355959106-2bfa5771-93bd-476a-9a51-ee70f467d5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjIyMzQsIm5iZiI6MTcyMzA2MTkzNCwicGF0aCI6Ii8xMjkyMjM0MTgvMzU1OTU5MTA2LTJiZmE1NzcxLTkzYmQtNDc2YS05YTUxLWVlNzBmNDY3ZDVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QyMDE4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWVhMWNhYWE1OWYwZTAyMzNiODEwOTRlZDRiNDQxZTVmNTE4ZTMzNTZjZmVlNjIxMjU1Yjg2M2M2YjlkZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SXhdV-vYiazgpqEOMZEKc4HEuyZ4hNshtJxTKAHswRs)

You are right. Just updated the link.
