### ISSUE TITLE
[FEATURE] Use Zsh as default terminal 

### ISSUE THREAD

**Issue by PSGitHubUser1** [mylinuxforwork/dotfiles#107]
I like Zsh too. I would like to see [this](https://youtu.be/ud7YxC33Z3w?feature=shared) config in YOUR dotfile.
Watch the whole video, you will get my point.

It looks really nice. Can you config and make it defaults as shown in Video. It just looks stunning! Also, it has some features which are time-saver for users like me.

**Comment by mylinuxforwork** [comment]
@PSGitHubUser1 Thanks for sharing this reference. ZSH will definitely come. It is planned for 2.9.6

**Comment by PSGitHubUser1** [comment]
> @PSGitHubUser1 Thanks for sharing this reference. ZSH will definitely come. It is planned for 2.9.6

Here, take the links, which are shown in video:
 [Zensh repo](https://github.com/dreamsofautonomy/zensh)

[Zinit](https://github.com/zdharma-continuum/zinit)

[Fzf-tab](https://github.com/Aloxaf/fzf-tab?tab=readme-ov-file#install)

[Nerd fonts](https://github.com/ryanoasis/nerd-fonts)

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/issues/30

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/wiki/Switch-between-bash-and-zsh
