### ISSUE TITLE
[BUG] No confirmation in ~/dotfiles/.config/ml4w/scripts/pacman.sh

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#108]
**Describe the bug**
When 'configure pacman.conf is executed from ML4W Welcome app, the script exits to soon when all the conditions are already met. Version: 2.9.5RC1

**To Reproduce**
1. start the welcome app
2. Click drop down 'Settings', System, Configure pacman.conf
3. Execute
4. script output is not kept visable

**Expected behavior**
I would expect a "Press enter to return" or something of that kind

**Screenshots**
n/a

**Distribution (please complete the following information):**
 - Arch Linux. 

**Additional context**

**Comment by mylinuxforwork** [comment]
@eljejer Thanks. Added to the main branch. https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/ml4w/scripts/pacman.sh
