### ISSUE TITLE
[FEATURE] Installation profile

### ISSUE THREAD

**Issue by omsenjalia** [mylinuxforwork/dotfiles#11]
It is an automatically generated profile that sets default for everytime you update or do anything with the system. Here is a more detailed picture from discord.

![Screenshot_20240720_062953](https://github.com/user-attachments/assets/67c9bbc2-1b66-4d78-9470-1c3c60e6f816)

**Comment by mylinuxforwork** [comment]
Thanks for the details. Would be helpful for me too. Will add this feature soon.

**Comment by mylinuxforwork** [comment]
Related issue https://github.com/mylinuxforwork/dotfiles/issues/8

**Comment by omsenjalia** [comment]
> Related issue #8

It is a bit diffrent then that.

**Comment by mylinuxforwork** [comment]
That's right. I will implement your request first.

**Comment by omsenjalia** [comment]
> That's right. I will implement your request first.

they both were my request 🤣

**Comment by dianaw353** [comment]
I'd like to show my own idea on installation profiles. I have recently discovered this program called ansible which is a amazing tool on automating the install process.

Pros:

    Automates installation
    Can run on multiple machines simultaneously
    Easy to set up your own settings
    Includes many conditional checks (e.g., to detect virtual machines)
    Consistent environment setup across different machines
    Lots of other benefits

Cons:

    May need to rewrite the installation script
    Might require changes to how dotfiles are organized

For examples of how I’ve automated the installation process and profiles with Ansible, please refer to my [dotfiles]((https://github.com/dianaw353/dotfiles)).

this also would be a solution to  #8

**Comment by mylinuxforwork** [comment]
@omsenjalia Automation for the installation/update is now available on the rolling release. Feel free to test it: https://github.com/mylinuxforwork/dotfiles/wiki/Automation-of-the-installation-and-update

**Comment by omsenjalia** [comment]
> @omsenjalia Automation for the installation/update is now available on the rolling release. Feel free to test it: https://github.com/mylinuxforwork/dotfiles/wiki/Automation-of-the-installation-and-update

Thanks.
