### ISSUE TITLE
SDDM Login Failed [BUG] 

### ISSUE THREAD

**Issue by Its-Japo** [mylinuxforwork/dotfiles#112]
**Describe the bug**
SDDM configuration does not allow me to log in, even though the credentials are correct it says "Login failed!". I need to log in via console to use my pc.

**To Reproduce**
It just happens

**Expected behavior**
A expect to log in

**Screenshots**
![Login](https://github.com/user-attachments/assets/b963789f-30dc-4cdf-97f6-33edba69685e)
I repeat, I KNOW my credentials, I just won´t show them here...

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
Do you have an NVIDIA card? 
Is Hyprland working fine when starting from tty?

**Comment by Its-Japo** [comment]
I do not have an NVIDIA card, I am using the Dell Latitude 5420, with 16GB of RAM and an Intel Core I5 1135G7 with its integrated graphics.

And yes, hyperland does work fine when running from tty.

**Comment by mylinuxforwork** [comment]
> I do not have an NVIDIA card, I am using the Dell Latitude 5420, with 16GB of RAM and an Intel Core I5 1135G7 with its integrated graphics.
> 
> 
> 
> And yes, hyperland does work fine when running from tty.

You can also try a different display manager. Please check https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#launching-hyprland
