### ISSUE TITLE
[FEATURE] Add Emoji Picker on Waybar

### ISSUE THREAD

**Issue by PSGitHubUser1** [mylinuxforwork/dotfiles#115]
It will be a time saver. Otherwise it takes centuries to find emoji & paste on Discord or other platform.

[Here](https://github.com/koeqaife/hyprland-material-you) is the reference.

Just found that repo. It looks nice too, it may give more ideas about the things to add on Waybar or in the dotfile.

**Comment by mylinuxforwork** [comment]
@PSGitHubUser1 I will add a key binding to execute smile with SUPER+CTRL+E

Adding the emoji picker would make waybar to busy. But a user can decide on doing that with a custom QuickLink. https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks

**Comment by PSGitHubUser1** [comment]
> @PSGitHubUser1 I will add a key binding to execute smile with SUPER+CTRL+E
> 
> Adding the emoji picker would make waybar to busy. But a user can decide on doing that with a custom QuickLink. https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks


@mylinuxforwork By the way, is there any on-screen keyboard app? based on GNOME and doesn't look like sh1t?

**Comment by mylinuxforwork** [comment]
> > @PSGitHubUser1 I will add a key binding to execute smile with SUPER+CTRL+E
> > Adding the emoji picker would make waybar to busy. But a user can decide on doing that with a custom QuickLink. https://github.com/mylinuxforwork/dotfiles/wiki/Waybar#define-your-quicklinks
> 
> @mylinuxforwork By the way, is there any on-screen keyboard app? based on GNOME and doesn't look like sh1t?

I only know Onboard and I agree, it's super ugly.

**Comment by mylinuxforwork** [comment]
@PSGitHubUser1 Just pushed an update to main branch (rolling release) including Smile. You can open it with SUPER+CTRL+E.
