### ISSUE TITLE
VS Code launch problem after 2.9.5

### ISSUE THREAD

**Issue by Makhsalar** [mylinuxforwork/dotfiles#118]
I know it seems irrelevant but after 2.9.5 update vs code takes about 2-3 minutes to launch BUT if you add --disable-gpu command and run it through the terminal problem will be solved
maybe some changes in env or nvidia settings?

**Comment by mylinuxforwork** [comment]
Can you try this? Visual Studio Code frequently crashes linux. Using NVIDIA GPU

1. Open command pallete (Ctrl + Shift + P)
2. Enter "Preferences: Configure Runtime Arguments"
3. Add config: "disable-hardware-acceleration": true
4. Restart VS Code

These are the Ozone Variables in ~/.config/hypr/conf/ml4w.conf

```
# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
```

Not sure if this would have an impact on VS Code. But you could test to comment the variables.

**Comment by Makhsalar** [comment]
disabling hardware acceleration fixed the problem but I'm looking for a way to run vs code without disabling it

**Comment by mylinuxforwork** [comment]
It seams it's an NVIDIA only issue. Not sure if really the new Dotfiles version is generating that issue.

**Comment by gegehprast** [comment]
> disabling hardware acceleration fixed the problem but I'm looking for a way to run vs code without disabling it

If you don't use many Electron apps other than VSCode or you haven't encounter any issue with any Electron apps, you can just remove the ELECTRON_OZONE_PLATFORM_HINT env.

You can also set for per app basis with --ozone-platform=wayland flag.
