### ISSUE TITLE
[FEATURE] Separate the installation of Hyprland and packages from the installation of the dotfiles

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#120]
**Is your feature request related to a problem? Please describe.**
Currently the installation of Hyprland and the required packages are mixed with the installation of the dotfiles. With a clear separation it could be easier in the future to support more distros.

**Describe the solution you'd like**
Create a subfolder basesystem including the Hyprland installation. + install.sh
Create a subfolder dotfiles including the dotfiles installation scripts. + install.sh
Make sure that the automation is still running.
The global install.sh should execute both scripts.

**Comment by Homer-Max** [comment]
Maybe you can list the packages installed. People may choose the different packages such as fish rather than  zsh or the others

**Comment by mylinuxforwork** [comment]
@Homer-Max The packages are listed here: https://github.com/mylinuxforwork/dotfiles/tree/main/packages

**Comment by mylinuxforwork** [comment]
I will add the option to define a custom list of packages.
