### ISSUE TITLE
[BUG] PyWal not working

### ISSUE THREAD

**Issue by DanieleBertagnoli** [mylinuxforwork/dotfiles#122]
**Describe the bug**
I was trying to use a different wallpaper rather than those shipped with the dot files. However, when I select the wallpaper using the tool the wallpaper is changed into a black image. I tried to use the command `wal -i ~/wallapaper/photo.jpeg`, the theme colors are generated and applied but the wallpaper remains black. I also get a warning when using the command:

![image](https://github.com/user-attachments/assets/c34c1bfa-1f36-4d4d-a730-030d347fc5a5)

**Expected behavior**
The wallpaper should be changed.

**Distribution (please complete the following information):**
 - EndeavourOS

**Comment by mylinuxforwork** [comment]
@DanieleBertagnoli Thanks for testing.

I cannot replicate the issue on my system. I can select from different folders a new wallpaper and pywal is coloring the terminal and borders correctly. The wallpaper will be set without any problem.

Can you describe every step.
And can you share the filename of the image that you want to set as wallpaper?

**Comment by DanieleBertagnoli** [comment]
Hi, the file name is the one indicated in the screenshot `sport.jpg` (without spaces as indicated in the wiki). I've simply downloaded the image, put it in the `wallpaper` directory and either using the `wal -i` command or the wallpaper widget `CTRL + SUPER + W`, the result is always the same, black wallpaper while the color theme are updated according to the image. (The image was downloaded from the following [link](https://www.uhdpaper.com/2023/02/sports-car-futuristic-mountain-4k-5370i.html?m=0))

**Comment by mylinuxforwork** [comment]
Hi. No. clearcache isn't normal and I don't know where this comes from.

Which waypaper version have you installed? 

`waypaper --version`

**Comment by smoleyxd** [comment]
Hello I am having this same issue. waypaper v.2.2

Upon running the installation script I found pywal saying "No image found"

**Comment by mylinuxforwork** [comment]
> Hello I am having this same issue. waypaper v.2.2
> 
> Upon running the installation script I found pywal saying "No image found"

Have you changed a setting in waypaper? Can you describe the steps how you set a walllpaper?

**Comment by DanieleBertagnoli** [comment]
Well, I solved by manually setting the values in `hyprpaper.conf`. Once insert the path of  the image instead of `clearcache`, I rebooted the system and all just started to work again.

**Comment by mylinuxforwork** [comment]
And are you able to change the wallpaper with waypaper app?

**Comment by DanieleBertagnoli** [comment]
I do, yes.
