### ISSUE TITLE
[FEATURE] Screeshot Keybinding Option for Laptops Without "PRINT"

### ISSUE THREAD

**Issue by Somnius** [mylinuxforwork/dotfiles#125]
**Screeshot Keybinding Option for Laptops Without "PRINT"**
I'm on a laptop enjoying the fact i've just setup my self-hosted git and clone dotfile settings etc, but i can't screenshot while using the laptop cause i don't have the Print Screen Key, and yes some-one will say "it's that one with Fn+X" but i don't know cause my key-caps don't mention it :-O 

**Maybe.. (!?)**
Have an option inside the ml4w app or at least let me change it on the `~/.config/hypr/conf/keybindings/default.conf`  cause when i tamper with it on 
```
bind = $mainMod, PRINT, exec, $HYPRSCRIPTS/screenshot.sh # Take a screenshot
```
commenting out and swapping `PRINT` with [...]`$mainMod, SHIFT, S, exec`[...], hyprctl screams red bars.. 

Any ideas?

**Comment by mylinuxforwork** [comment]
Thanks for bringing this up. You can create your own custom keybinding variation. Copy the default.conf to mybindings.conf (choose your own filename), make your changes and select the new variation in the settings app.

https://github.com/mylinuxforwork/dotfiles/wiki/Configuration-Variations

Would that work for you?

**Comment by mylinuxforwork** [comment]
@Somnius Would that work for you?

**Comment by Somnius** [comment]
> @Somnius Would that work for you?

It would, not only for me, but all laptoo users without the print or fn+print button .. I'm running your dotfiles over eOS on a macbook air that doesn't have it

**Comment by mylinuxforwork** [comment]
Maybe I can add an additional keybinding. Will check...

**Comment by Somnius** [comment]
> I had also to change it on my external Logitech mac/windows keyboard connected to a Laptop.
> 
> There is a dedicated screenshot key, that also triggers: "$mainMod SHIFT, S" not PRINT

+1 for mod + shift + S

**Comment by mylinuxforwork** [comment]
@Somnius @NeussConsulting Just pushed an update including the keybinding SUPER+SHIFT+S to open the screenshot feature.

**Comment by Somnius** [comment]
it works on latest .9RL with Super + Shift +S, thank you!!
