### ISSUE TITLE
[BUG] Smile wasn't installed on latest rolling

### ISSUE THREAD

**Issue by Somnius** [mylinuxforwork/dotfiles#126]
**Smile wasn't installed on latest rolling**
I'm on latest ml4w v2.9.5, based on endeavourOS, selected rolling, selected both Qtile & Hyprland, all fresh installed today. When you hit `SUPER + CTRL + E` the emoji picker (`smile`) doesn't pop-up !!

**To Reproduce**
Hit `Super + CTRL +E`, and nothing happens,
Try to run `smile` and nothing happens,

**How to remedy that?**
Install smile with `pacseek` with `pacseek smile`
Now if i hit Super +CTRL +E` i get the emoji picker :100: 

**Notes**
The user can see what the keybinding does by less'ing inside `keybindings/default.conf`
```
bind = $mainMod CTRL, E, exec, ~/.config/ml4w/settings/emojipicker.sh # Open the emoji picker
```
And the `emojipicker.sh` just runs `smile` but without the package, no emojiz!

**Comment by mylinuxforwork** [comment]
You're right. Will add smile to the package list.

**Comment by mylinuxforwork** [comment]
Added smile to the package list.

**Comment by oluijks** [comment]
I'm on version 2.9.7.3, when I open the welcome app, click Installation Options and then More and choose smile, it doesn't do anything. I managed by installing it via yay... not a big issue but I thought I let you know...

**Comment by mylinuxforwork** [comment]
@oluijks Thanks for testing. I will check.
