### ISSUE TITLE
[FEATURE] Change default terminal from Alacritty to Kitty

### ISSUE THREAD

**Issue by kerbyyy** [mylinuxforwork/dotfiles#128]
**Is your feature request related to a problem? Please describe.**
This isn't a problem or anything, but I think it's much better if we use Kitty instead. Alacritty is amazing, but Kitty has a lot more better features like image rendering.

**Describe the solution you'd like**
Replace the default terminal to Kitty or have an option between Alacritty or Kitty.

**Describe alternatives you've considered**
Add it to the post-intall script or add it to the installation prompt.

**Comment by mylinuxforwork** [comment]
Hi. Would that work for you? https://github.com/mylinuxforwork/dotfiles/wiki/Change-the-default-terminal

Thanks for your feedback.

**Comment by adam-coates** [comment]
Maybe also this is useful https://github.com/jstkdng/ueberzugpp I use this with alacritty and its not so bad. And the ability to integrate with `fzf`

**Comment by kerbyyy** [comment]
> Hi. Would that work for you? https://github.com/mylinuxforwork/dotfiles/wiki/Change-the-default-terminal
> 
> Thanks for your feedback.

I'll try doing this instead. Thank you so much!
