### ISSUE TITLE
[BUG] HELP:how to configure scaling rate in hyprland

### ISSUE THREAD

**Issue by bgp65530** [mylinuxforwork/dotfiles#131]
I really like your dotfiles, but I don't know how to adjust the scaling rate after the default installation. 
My laptop is 16 inches, with a resolution of 2560x1600. The scaling rate of 1.5 is more appropriate when I using KDE PLASMA. I don't know how to configure this in hyprland. Can you help me? Thank you!

**Comment by RobertKlonowski** [comment]
For example :

in file: ~/.config/hypr/conf/monitors/default.conf

set 
monitor=,preferred,auto,1.5

Hyprland Settings:
https://wiki.hyprland.org/Configuring/Monitors/

**Comment by RobertKlonowski** [comment]
https://github.com/mylinuxforwork/dotfiles/wiki/Configuration-Variations

**Comment by mylinuxforwork** [comment]
That is correct. But I would suggest to copy the default.conf and name it mymonitor.conf, make your adjustments and select your variation in the settings app, system tab.

Then you'll be safe for updates of the Dotfiles.

**Comment by bgp65530** [comment]
@mylinuxforwork @RobertKlonowski 
Thanks a lot!
