### ISSUE TITLE
[BUG]  Waybar not loading

### ISSUE THREAD

**Issue by afzl-wtu** [mylinuxforwork/dotfiles#132]
**Describe the bug**
I installed several times dotfiles 2.9.5 and main rolling with and without xdg-desktop-portal-gtk. But at first time waybar loads after that it does not load. Even I tried Ctrl + Super + B. this is strange issue.  I tried it with  and without sddm installed. It is working fine on my same other laptop but not on this one. I did not change any config.

**To Reproduce**
It happens randomly. 

**Expected behavior**
Waybar should load atleat after reboot. 

**Screenshots**
NO

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
Can we do a test?
Can you increase in this file https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/waybar/launch.sh on line 23 the value from 0.5 to 3s

Then reboot and try again several times.

**Comment by afzl-wtu** [comment]
> Can we do a test? Can you increase in this file https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/waybar/launch.sh on line 23 the value from 0.5 to 3s
> 
> Then reboot and try again several times.

I found root cause of this issue. I do not know why there is a file exists in  ~/.cache/waybar-disabled. So when this file exists waybar exits in  launch.sh here:
```
if [ -f $HOME/.cache/waybar-disabled ] ;then 
    killall waybar
    pkill waybar
    exit 1 
fi
```
if I comment this section and run launch.sh manually everything works great. Or if I delete waybar-disabled file. it works great.

**Comment by mylinuxforwork** [comment]
This file will be created when you disable waybar in the settings app or with super+ctrl+b to toggle waybar. But it's great that you found the reason.

**Comment by afzl-wtu** [comment]
Moreover, I installed dotfiles 2.9.5 and rolling, everytime with:
```
sudo rm -rf ~/*
```
and restored **Base Install snapshot** with snapper of root, taken after first arch boot without any display manager and window manage (You can say I reinstall arch before every dotfiles installation with nothing in home directory and clean root file system). But somehow every time after reboot this file is created

**Comment by afzl-wtu** [comment]
> This file will be created when you disable waybar in the settings app or with super+ctrl+b to toggle waybar. But it's great that you found the reason.

I never turned off waybar in setting app or through Ctrl+Super+B. I know those shorcuts.
