### ISSUE TITLE
[FEATURE] Use HyprPanel

### ISSUE THREAD

**Issue by ElectroPerf** [mylinuxforwork/dotfiles#136]
https://github.com/Jas-SinghFSU/HyprPanel

Looks elegant

**Comment by mylinuxforwork** [comment]
Need to check. But a user can already decide to use it.
Disable waybar in the settings app and install HyprPanel should work.

**Comment by ElectroPerf** [comment]
> Need to check. But a user can already decide to use it. Disable waybar in the settings app and install HyprPanel should work.

yea well thats the ultimate for everything but i am talking of making it the default as its pretty cool. i am working on adapting to the ml4w dotfiles and will post screenshots soon enough

**Comment by Somnius** [comment]
Sub'ed on this, pretty interesting, and loved the results on main screenshot
