### ISSUE TITLE
[FEATURE] Provide for an autostart.custom 

### ISSUE THREAD

**Issue by hanska-slow** [mylinuxforwork/dotfiles#137]
To allow user specific additions to the autostart.conf file that remain consistent after a system update

**Comment by mylinuxforwork** [comment]
@hanska-slow  You can already do this by adding additions to the file custom.conf 
https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/hypr/conf/custom.conf
This file can be restored in an update.

Would that work for you?

**Comment by hanska-slow** [comment]
Great suggestion. It worked perfectly. Thank you
