### ISSUE TITLE
[FEATURE] Backlight for Laptop Keys Control

### ISSUE THREAD

**Issue by Somnius** [mylinuxforwork/dotfiles#139]
**Backlight for Laptop Keys Control**
I couldn't change the backlight of my keys while using latest rolling release dotfiles

**Solution**
Adding the following keybindings :
```
bind = , code:238, exec, brightnessctl -d smc::kbd_backlight s +10
bind = , code:237, exec, brightnessctl -d smc::kbd_backlight s 10- 
```
This will identify `'smc::kbd_backlight' of class 'leds'` as it does for screen brightness, if you run it on the terminal with 
```
brightnessctl -d smc::kbd_backlight s +10
```
or
```
brightnessctl -d smc::kbd_backlight s 10- 
```
you'll see the terminal reporting back information, including current brightness.

Hope it get's included in next release! ;)

**Comment by mylinuxforwork** [comment]
@Somnius I have added the two lines to the default.json in ~/.config/hypr/conf/keybindings

Can you test?

**Comment by Somnius** [comment]
> @Somnius I have added the two lines to the default.json in ~/.config/hypr/conf/keybindings
> 
> Can you test?

No need to test its smc it will work 😉
