### ISSUE TITLE
Missing package (Arch: python-pyperclip) for alias gr / python script "growthrate.py"

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#14]
**Describe the bug**
No idea what the script growthrate.py in ~/dotfiles/scripts/ is for, but to be able to run it, you need the (arch) package python-pyperclip

**To Reproduce**
1. run gr in terminal -> error
2. install python-pyperclip -> script runs

**Expected behavior**
run the script or delete it altogether

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Thanks for your awesome hyprland install script!

**Comment by mylinuxforwork** [comment]
@legymhueck I have moved the issue to the dotfiles repo. Thanks for testing. Will look into it.

**Comment by mylinuxforwork** [comment]
I will remove the script. It is a legacy script from older versions.

**Comment by mylinuxforwork** [comment]
File has been removed.
