### ISSUE TITLE
[BUG] Config error in waybar

### ISSUE THREAD

**Issue by marcobir** [mylinuxforwork/dotfiles#141]
I have this error:
![ML4wError](https://github.com/user-attachments/assets/6a09c162-1fa3-45a4-9956-3193a80c808d)

How can i fix this please?

**Comment by mylinuxforwork** [comment]
Pywal isn't installed correctly. Please try

`yay -S python-pywal `

Then reboot.

Open a terminal and enter 

`wal -i $HOME/wallpaper/default.jpg`

**Comment by marcobir** [comment]
Thank you.
I reinstalled Pywal but the problem not solved.
I uninstalled it and reinstalled again.
the wallpape folder still empty
![2024-08-15_16-5716-57-44](https://github.com/user-attachments/assets/92263b25-5511-4437-89a3-e9085576e53d)
Thank you so much for your help.

**Comment by mylinuxforwork** [comment]
OK. Does the wallpaper folder exists? If not please create the folder in your home directory and copy the images from here into the folder: https://github.com/mylinuxforwork/dotfiles/tree/107-feature-zsh/install/wallpapers and try again.

**Comment by marcobir** [comment]
Thank you so much.
I appreciate your effort.
Problem Solved.
![solved](https://github.com/user-attachments/assets/b67d8a64-0d89-43ad-899b-653ccbd5b30a)

**Comment by mylinuxforwork** [comment]
Great!
