### ISSUE TITLE
[FEATURE] Blurry GNOME

### ISSUE THREAD

**Issue by PSGitHubUser1** [mylinuxforwork/dotfiles#145]
## Describe your idea

I want blurry GNOME, since your dotfile is based on GNOME DE, there should be an option to enable blur. Like you can do with KDE apps (I guess so). I know it blurs when you don't focus on a GNOME Window but I want blur ON the focused GNOME window.

Is this possible? If yes, then it should be a nice idea to select v2.9.7 milestone instead of v2.9.6, hence, giving you some time for proper implementation.

**Comment by PSGitHubUser1** [comment]
> @PSGitHubUser1 Can you share a screenshot that describes the desired output a bit more?


No. How can I? 

I mean, like dolphin (kde app) can be customised to change colour and make it blur/translucent. 

Like when you unfocus/do not hover cursor over a window, it becomes blurry, that's the blur I want ON the focused window/when cursor is on the window.

**Comment by mylinuxforwork** [comment]
You could try out the following. 
Open the Hyprland Settings App

**Comment by PSGitHubUser1** [comment]
> You could try out the following. 
> Open the Hyprland Settings App and set the active opacity to 8
> And set a high blur level.
> 
> Then it looks like that.
> 
> ![image](https://github.com/user-attachments/assets/1f7f1a24-53bd-426e-800e-2b8140fecff4)
> 


@mylinuxforwork That's too much blurry. I mean in a limit, don't you think there should be a checkbox to enable Blur?
