### ISSUE TITLE
[FEATURE]  wallpaper is reset on every update to dotfiles.  

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#148]
**Is your feature request related to a problem?  
Especially since I am on the rolling release  I have to reset the wallpaper and I use `wal -i  IMAGE` to set the color theme too.  Since preferred background sets a very dim color pallet 

**Describe the solution you'd like**
Preserve the current wallpaper and pywall color palette` on dotfiles update

**Describe alternatives you've considered**
 I have to redo it each time

**Comment by mylinuxforwork** [comment]
Just tested with the latest rolling release of 2.9.6. No issues in restoring the wallpaper after an update. 
Maybe there is an issue from updating from 2.9.5 to 2.9.6. But this is something that I cannot improve unfortunately.
