### ISSUE TITLE
[FEATURE] Add SUPER + K for swapsplit to default config

### ISSUE THREAD

**Issue by dfd** [mylinuxforwork/dotfiles#149]
**Is your feature request related to a problem? Please describe.**
Not so much a problem as a suggestion for better ergonomics.
`swapsplit` is a useful command to swap windows without using a mouse.

**Describe the solution you'd like**
I think SUPER + K is a natural choice for it, as it makes a nice complement to SUPER + J for toggle split.
Add a binding:
```
bind = $mainMod, K, swapsplit,
```

**Describe alternatives you've considered**
Using a mouse or custom config.

**Additional context**
This is just a suggestion more than a problem that needs to be solved.  But I'd encourage you to try it out.  SUPER + J and SUPER + K become intuitive complements.

**Comment by dfd** [comment]
I'm referring to the [swapsplit](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#layout-messages) layout message, and adding 

`bind = $mainMod, K, swapsplit,`

after [this line here](https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/hypr/conf/keybindings/default.conf#L23) in your default key bindings.

**Comment by mylinuxforwork** [comment]
@dfd Just added the keybinding to the default.conf on the main release. Thanks.
