### ISSUE TITLE
matrix alias for cmatrix -> cmatrix not installed

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#15]
**Describe the bug**
You have the alias matrix, but the (arch) package cmatrix is not installed

**To Reproduce**
1. run matrix in terminal -> alias does not work
2. install cmatrix -> alias works

**Expected behavior**
cmatrix program running when alias is run

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I love your hyprland install script.

**Comment by mylinuxforwork** [comment]
@legymhueck I have moved the issue to the dotfiles repo. Thanks for testing. Will look into it.

**Comment by mylinuxforwork** [comment]
Thanks for looking into it. Will remove the alias.

**Comment by mylinuxforwork** [comment]
@legymhueck Cannot find the alias. Where have you found it?

**Comment by mylinuxforwork** [comment]
Pretty sure that you're using an older customized.bashrc and haven't it overwritten during the installation. This is the latest version:

https://gitlab.com/stephan-raabe/dotfiles/-/blob/main/dotfiles/.bashrc?ref_type=heads

**Comment by legymhueck** [comment]
Sorry, my bad. Copied your latest .bashrc
Thanks for looking into the problem and informing me.

**Comment by mylinuxforwork** [comment]
No worries. Thanks for testing.
