### ISSUE TITLE
[BUG] installed ml4w dotfiles, now floorp vertical tab bar is transparent

### ISSUE THREAD

**Issue by rbutera** [mylinuxforwork/dotfiles#156]
**Describe the bug**
I installed ml4w dotfiles (thank you for this) and Floorp's vertical tab bar is now transparent, and I have no idea why.

I have no theme installed in Floorp or anything like that. 

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
Can you share a screenshot?

**Comment by mylinuxforwork** [comment]
You can try to set another gtk theme with nwg-look. Maybe this will fix it.

**Comment by rbutera** [comment]
> You can try to set another gtk theme with nwg-look. Maybe this will fix it.

I tried adwaita which is my old gtk theme and it has the same problem

Can you please try and think of anything you have done to make things transparent in your dot files? I've tried grepping for opacity, transparency etc and I can't find anything

**Comment by mylinuxforwork** [comment]
Can you check the inactive opacity in the Hyprland Settings app? And try to set it to 10?

![image](https://github.com/user-attachments/assets/e17b1a34-4be3-4db9-8104-6d8fa098028d)

**Comment by mylinuxforwork** [comment]
@rbutera I would like to close this issue because floorp is not part of the tested dotfiles app. In that case I cannot help you. Please feel free to open a discussion to get feedback from other users.
