### ISSUE TITLE
Changing the terminal - rofi keeps using alacritty

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#158]
### Discussed in https://github.com/mylinuxforwork/dotfiles/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **aecardenasfl** August 14, 2024</sup>
Sorry to open a different post but this is a different issue I'm facing. I changed the default terminal through the "Dot files" App, on the system section from "alacritty" to "kitty" (as this was my terminal emulator of choice before installing ML4W). When I use the keybind SUPER+return it launches kitty just fine. But when I use super+ctrl+return to launch rofi and I want to open for example Neovim, or Yazi it launches those apps in Alacritty. 

I created a custom config file under ~/.config/bashrc/custom and added export TERMINAL=kitty then sourced the ~/.bashrc, rebooted but rofi is still opening everything in Alacritty. I uninstalled Alacritty and it correctly launches the apps in kitty, but if I install it back rofi goes back to launching terminal apps in Alacritty. Not really important but if you maybe have an idea what I'm doing wrong I'd appreciate your feedback. </div>

**Comment by mylinuxforwork** [comment]
@aecardenasfl Can you check https://superuser.com/questions/361377/what-is-arch-linuxs-default-terminal

**Comment by aecardenasfl** [comment]
> @aecardenasfl Can you check https://superuser.com/questions/361377/what-is-arch-linuxs-default-terminal

done. echo $TERM shows kitty both in kitty and alacritty. But rofi still launches yazi and nvim in alacritty instead :(

**Comment by jamesrahhh** [comment]
Rofi by default uses `rofi-sensible-terminal` as its terminal which uses the `$TERMINAL` variable rather than `$TERM`.

**Comment by mylinuxforwork** [comment]
> Rofi by default uses `rofi-sensible-terminal` as its terminal which uses the `$TERMINAL` variable rather than `$TERM` according to the manpages. Alacritty by default has priority above kitty if `$TERMINAL` isn't set.

Great input. Thanks for sharing it.

**Comment by aecardenasfl** [comment]
> Rofi by default uses `rofi-sensible-terminal` as its terminal which uses the `$TERMINAL` variable rather than `$TERM` according to the manpages. Alacritty by default has priority above kitty if `$TERMINAL` isn't set.

that's good to know... I set TERMINAL=kitty, so even in alacritty when I do $echo $TERMINAL it returns "kitty"... but rofi stills doesn't like it and uses alacritty instead :(
