### ISSUE TITLE
alias ChatGPT -> no folder and no script mychatgpt

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#16]
**Describe the bug**
The ChatGPT alias does not work because there is no folder mychatgpt and also no script inside.

**To Reproduce**
1. run ChatGPT in terminal

**Expected behavior**
- Script should launch
- If not wanted, delete alias

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Sorry for yet another report on missing aliases.

**Comment by mylinuxforwork** [comment]
@legymhueck I have moved the issue to the dotfiles repo. Thanks for testing. Will look into it.

**Comment by mylinuxforwork** [comment]
Cannot find the alias in https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.bashrc Where have you found it?

**Comment by legymhueck** [comment]
Since it's my fault, i.e. I used the original .bashrc, you can close the bug report.
Sorry again for the inconvenience.

**Comment by mylinuxforwork** [comment]
No worries. Thank you for testing.
