### ISSUE TITLE
[BUG] history of commands in zsh shell not available

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#163]
**Describe the bug**
I have a ~/.zsh_history file with my command history
When I open terminal and issue command 'history' only one command is shown: 'history'
That way the <CTRL>+R key is not very meaningfull

**To Reproduce**
1. open (zsh) terminal
2. issue some commands
3. check them with 'history'  command and CTRL+R
4. open a new terminal
5. earlier commands are 'gone'

**Expected behavior**
I would expect the commands to be saved until HISTSIZE and/or SAVEHIST

**Screenshots**
n/a

**Distribution (please complete the following information):**
 - Arch Linux
 - CachyOS

**Additional context**
ML4W version 2.9.6RL

**Comment by mylinuxforwork** [comment]
@eljejer On my system it's working fine. 

![image](https://github.com/user-attachments/assets/f56ba48b-1a00-4424-9eaa-754832b94a1c)

Can you check that FZF is installed correctly?

**Comment by eljejer** [comment]
> @eljejer On my system it's working fine.
> 
> ![image](https://private-user-images.githubusercontent.com/145253254/359882847-f56ba48b-1a00-4424-9eaa-754832b94a1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDIxODYsIm5iZiI6MTcyNDI0MTg4NiwicGF0aCI6Ii8xNDUyNTMyNTQvMzU5ODgyODQ3LWY1NmJhNDhiLTFhMDAtNDQyNC05ZWFhLTc1NDgzMmI5NGExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMjA0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTA0ZjUyNjM4MWFkNDc3MWI5OWU5MmNkN2E2NmM4Njc2ZTkzNjdhZjFlZjE4NmQxYTE1NmY2NWUwMjNhODhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KMpYOzAI2bsk36Yeot6xxdK0M-13Q5nNtnYDtZGoyzk)
> 
> Can you check that FZF is installed correctly?

@mylinuxforwork I re-installed fzf

`pacman -S fzf`

Also my zsh prompt is not what it's supposed to be:

![screenshot_21082024_141517](https://github.com/user-attachments/assets/25e70f43-d55f-4441-8ad4-76e994b1d9cb)

also when I am in downloads en type .. I get permission error
![screenshot_21082024_141742](https://github.com/user-attachments/assets/b3db5bde-8eda-4dde-9c34-64ce49e624bf)




Maybe re-install zsh?

**Comment by eljejer** [comment]
@mylinuxforwork I re-installed Dotfiles completely from tty with command

`cd ~/downloads && rm -rf dotfiles && git clone --depth=1 https://github.com/mylinuxforwork/dotfiles.git && cd dotfiles && ./install.sh`

Now the complete zsh history is available to me.

Only the 'permission denied' response to command `..` is not clear to me. I will invastigate this further
