### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jlengelbrecht** [mylinuxforwork/dotfiles#168]
**Describe the bug**
Graphical bug on dual monitor setup after updating dotfiles. Not sure what's causing it as it does not appear when I switch from hyprland to Plasma - Wayland. Any idea what could be causing this? 

**Screenshots**
![20240821_143052.jpg](https://github.com/user-attachments/assets/16f95d91-5846-4ec9-83d7-209192d0cd15)

**Distribution (please complete the following information):**
 - Arch Linux
 - primary GPU - RX7900 XTX 
 - second GPU - VM passthrough - Nvidia Titan Xp

 

**Additional context**
Had no issues using dotfiles prior. For some reason this bug just started out of no where and I can't seem to fix it. Reinstalling dotfiles does not resolve the issue.

**Comment by mylinuxforwork** [comment]
Can you share your monitor configuration in .config/hypr/conf/monitors/

**Comment by jlengelbrecht** [comment]
Sorry for the delay I got caught up with some other things. So I removed hyprland and reinstalled from scratch this fixed the issue. Back up and running now. Updated to 2.9.6 earlier today with no issues. Not sure what broke but its good now.

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing and your feedback.
