### ISSUE TITLE
[BUG] after i install all script follow in a video guide i recive that notification. And my video resolution doesnt work. So this is the screenshot of the error

### ISSUE THREAD

**Issue by EnigmaStyle** [mylinuxforwork/dotfiles#169]
**Describe the bug**
Error on line 41

**To Reproduce**

**Expected behavior**

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Add any other context about the problem here.![image](https://github.com/user-attachments/assets/f9a6ff3b-bc1e-4174-b824-64a9059bd7f4)

**Comment by mylinuxforwork** [comment]
Can you check that the folder wallpaper exists in your home directory and includes images?

**Comment by EnigmaStyle** [comment]
I reinstall the script but now i have black screen when i select the
hyprland in the login screen

Il giorno gio 22 ago 2024 alle 21:43 Stephan Raabe ***@***.***>
ha scritto:

**Comment by EnigmaStyle** [comment]
I think the nvidia drivers doesn't work. I have a RTX2060 super

**Comment by EnigmaStyle** [comment]
![image](https://github.com/user-attachments/assets/79f1514d-dc57-4ac3-8e44-7e178b725d9d) this is the line 41 but i can't find the folder. They say the folder doesn't exist

**Comment by mylinuxforwork** [comment]
@EnigmaStyle Please update to the latest version 2.9.6 and try again:
https://github.com/mylinuxforwork/dotfiles/wiki/Update

**Comment by mylinuxforwork** [comment]
@EnigmaStyle Any updates? If not I would close the issue.

**Comment by EnigmaStyle** [comment]
Sorry i cant try in these day cause i have a lot of work. I try in weekend
and i send a report of installation

Il giorno mar 27 ago 2024 alle 16:21 Stephan Raabe ***@***.***>
ha scritto:

**Comment by mylinuxforwork** [comment]
@EnigmaStyle  I would close this issue for now. Please reopen it in case that the problem still exists.
