### ISSUE TITLE
xclip not installed

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#17]
**Describe the bug**
The alias ascii works, but copying the result to the clipboard fails because xclip is not installed.

**To Reproduce**
1. Run ascii in terminal
2. Enter something to render in ascii
3. xclip not installed
4. sudo pacman -S sclip

**Expected behavior**
Copy ascii art text to clipboard

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Glad you put so much effort into the project. It has developed incredibly from when I first used the install-script.

**Comment by mylinuxforwork** [comment]
@legymhueck I have moved the issue to the dotfiles repo. Thanks for testing. Will look into it.

**Comment by mylinuxforwork** [comment]
Thanks for testing. I have added xclip to the general-packages.sh file. Will be installed with your next update of the ML4W Dotfiles if not installed manually.
