### ISSUE TITLE
[BUG] ml4w-hyprland-git fails to install on Endeavor OS 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#172]
**Describe the bug**
![image](https://github.com/user-attachments/assets/be847f03-27e9-456f-bb98-fb6c04b79701)

**To Reproduce**
I ran this in a promox VM using VirGL
 did yay -S ml4w-hyprland-git  Used all defaults  Fails with error code 

**Expected behavior**
Expect install to complete w/o errors 

**Screenshots**
 
![image](https://github.com/user-attachments/assets/ae2d9bbc-a0de-48fc-b314-a1a092c838b1)

**Distribution (please complete the following information):**
  - EndeavourOS  w/i3 WM 
 
 

**Additional context**
Output of VM config attached 
[diag.txt](https://github.com/user-attachments/files/16719830/diag.txt)

**Comment by dwilliam62** [comment]
Found this error much earlier 

![image](https://github.com/user-attachments/assets/8b9c6e04-5a67-487c-99ba-9476a5eefe31)

**Comment by dwilliam62** [comment]
And this error before that 

![image](https://github.com/user-attachments/assets/2e8bbf00-d8b9-41b2-870c-a0ecc7b42eac)

**Comment by dwilliam62** [comment]
![image](https://github.com/user-attachments/assets/d7deb5d3-c4fe-4eea-b9b6-7d8282a794bd)
And this one before that

**Comment by dwilliam62** [comment]
Here's the entire install output.  
[error.log.txt](https://github.com/user-attachments/files/16720006/error.log.txt)
In case it helps triage this

**Comment by dwilliam62** [comment]
From Jak
![image](https://github.com/user-attachments/assets/14d243f5-7156-4ec2-a798-e8957097e4f5)

**Comment by dwilliam62** [comment]
https://wiki.archlinux.org/title/PKGBUILD#optdepends

Ive check his pkgbuild 

he can try switch to optdepends instead..
PKGBUILD

**Comment by mylinuxforwork** [comment]
Thank you so much for testing @dwilliam62 

I am actually planning to move some packages to the optdepends section. 
Today is the testing day for the aur installation. Will test on several distros.

Will send you a note as soon as the update is available.

**Comment by dwilliam62** [comment]
> Thank you so much for testing @dwilliam62
> 
> I am actually planning to move some packages to the optdepends section. Today is the testing day for the aur installation. Will test on several distros.
> 
> Will send you a note as soon as the update is available.

You are most welcome

**Comment by andresparrab** [comment]
thank you testing as well i have endeavouros in an spare laptop so i can trest as many things as you want..it is only dedicated to ml4w  testing :)

**Comment by mylinuxforwork** [comment]
@andresparrab @dwilliam62 Was able to install the ml4w-hyprland-git successfully on Garuda Linux and on Arch with Minimal profile. 

![image](https://github.com/user-attachments/assets/7195636a-3150-4221-8743-22568c2aebba)

@andresparrab Can you try again on EndeavourOS? Thank you.

**Comment by andresparrab** [comment]
@mylinuxforwork insteresting i wonder what are the differences.. but did you update something to be able to install in garuda? i will go home soon and try to install again not in VM but real laptop again to se if i can ge tit to work

**Comment by mylinuxforwork** [comment]
@andresparrab Thank you so much for testing. Yes please test again on Endeavour. Don’t know why I cannot install it in a VM anymore.

**Comment by andresparrab** [comment]
Installing now

**Comment by dwilliam62** [comment]
This is working now.   I think this can be closed ?

**Comment by andresparrab** [comment]
yes . sorry for late answer i try to install this in a few laptops now with endeavouros. And everything works just fine :)
