### ISSUE TITLE
SDDM wallpaper modification through welcome app

### ISSUE THREAD

**Issue by Makhsalar** [mylinuxforwork/dotfiles#173]
the welcome app uses the current desktop wallpaper for the SDDM wallpaper
instead of that  add an option for browsing the wallpaper

**Comment by Somnius** [comment]
sddm uses a theme as template, so you may want to change the picture in that theme folder in order to get different background while logging in with sddm.

**Comment by PSGitHubUser1** [comment]
> sddm uses a theme as template, so you may want to change the picture in that theme folder in order to get different background while logging in with sddm.

how to even change wallpaper in sddm?

I want to change but still I got the default.jpg

**Comment by mylinuxforwork** [comment]
> > sddm uses a theme as template, so you may want to change the picture in that theme folder in order to get different background while logging in with sddm.
> 
> how to even change wallpaper in sddm?
> 
> I want to change but still I got the default.jpg

https://github.com/mylinuxforwork/dotfiles/wiki/Wallpapers#wallpaper-for-sddm

**Comment by mylinuxforwork** [comment]
@PSGitHubUser1 Please try the welcome app on the latest 2.9.6

![image](https://github.com/user-attachments/assets/42de0f05-f707-4d47-ade6-8b4a484a2bb8)
