### ISSUE TITLE
[BUG] Minor Visual Bug with Top Bar Margins

### ISSUE THREAD

**Issue by demirciAhmet** [mylinuxforwork/dotfiles#174]
**Describe the bug**
Sometimes the margin between the workspaces indicator and the update indicator disappears. This happens especially when connecting to a Bluetooth device. I am using a 14" laptop with 1920x1200 resolution.

**To Reproduce**
1. Just connect to a bluetooth device.

**Screenshots**

![image](https://github.com/user-attachments/assets/f6f68845-01f5-46b3-bf95-ba824599ce7a)

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@demirciAhmet Which of the modules could you most easily do without?

**Comment by demirciAhmet** [comment]
> @demirciAhmet Which of the modules could you most easily do without?

I think the screen brightness module is not very crucial.

**Comment by mylinuxforwork** [comment]
@demirciAhmet I agree.
