### ISSUE TITLE
[BUG] Dependency issue on Arco Linux

### ISSUE THREAD

**Issue by 4uror4kn3ght** [mylinuxforwork/dotfiles#179]
**Describe the bug**
ML4W not installing full using the AUR(ml4w-hyprland-setup) on fresh Arco linux install

**To Reproduce**
1.install arco linux with gnome and linux kernel and pipewire sound and laptop support
2.run the scripts on chrultrabook as I am on a chromebook, or not
3.install ml4w using the AUR package
**Expected behavior**
For the setup to complete
**Screenshots**
[log.txt](https://github.com/user-attachments/files/16737460/log.txt)
**Distribution (please complete the following information):**
 - Arco linux

I will install the script the curl way.

**Comment by mylinuxforwork** [comment]
Thanks for testing. Can you share the results of installing the rolling release with the bash command?

**Comment by mylinuxforwork** [comment]
@4uror4kn3ght Can you remember what with packages couldn't install?

**Comment by 4uror4kn3ght** [comment]
essentially,all the info shoud be in the log file that I copied and pased from terminal.
`resolving dependencies...
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "aquamarine", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "libaquamarine.so=2-64", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "aquamarine", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "libaquamarine.so=2-64", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprland"
warning: cannot resolve "hyprland", a dependency of "hyprshade"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprpaper"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "aquamarine", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "aquamarine"
warning: cannot resolve "libaquamarine.so=2-64", a dependency of "hyprland"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprland"
warning: cannot resolve "hyprland", a dependency of "grimblast-git"
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprlock"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      hyprland  hyprshade  hyprpaper  grimblast-git  hyprlock

:: Do you want to skip the above packages for this upgrade? [y/N] y 
looking for conflicting packages...`

**Comment by 4uror4kn3ght** [comment]
bash command? is it the `ml4w-hyprland-setup` or  the Curl script?

**Comment by mylinuxforwork** [comment]
> bash command? is it the `ml4w-hyprland-setup` or the Curl script?

Yes. But I guess it will not solve the issue. It seams that the latest Hyprland isn’t supported by Arco. Arco is sometimes a bit special.

**Comment by mylinuxforwork** [comment]
@4uror4kn3ght https://github.com/mylinuxforwork/dotfiles/issues/181
