### ISSUE TITLE
check aliases and missing folders

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#18]
**Describe the bug**
Could you please check further aliases and folders such as "private" that are missing / have not been generated by the script?

**Expected behavior**
- aliases that refer to programs that are not installed should be deleted or commented out (for future use)
- aliases that reference the "private" folder should be deleted altogether.

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I hope my request is useful.

**Comment by mylinuxforwork** [comment]
@legymhueck I have moved the issue to the dotfiles repo. Thanks for testing. Will look into it.

**Comment by mylinuxforwork** [comment]
@legymhueck Can you share an example?

**Comment by legymhueck** [comment]
Again, sorry for the inconvenience. Your current .bashrc no longer has the missing folders from my initial installation of your script, which I installed around July 3rd.

What about the last line in autostart.sh? Does that path exist? I can neither find it in my installation nor in the current dotfiles.

# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh

Thanks for all the work you put into the project!

**Comment by mylinuxforwork** [comment]
Thanks again for testing...

Yes. When you're using the version of ML4W Dotfiles with the ML4W Hyprland Settings App. This app will create with the first start this folder and store the configuration there in a json file. This exec command is therefore required.
