### ISSUE TITLE
[BUG] bash and zsh customisation is not protected with update

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#180]
**Describe the bug**
I am using Dotfiles 2.9.6 and had some customization in bash and zsh in the directories

`~/dotfiles/.config/bashrc/custom
`
I updated Dotfiles with the bash command in tty

`cd ~/downloads && rm -rf dotfiles && git clone --depth=1 https://github.com/mylinuxforwork/dotfiles.git && cd dotfiles && ./install.sh
`
I use this way of updating my Dotfiles according to [this](https://github.com/mylinuxforwork/dotfiles/issues/98#issuecomment-2273534136).

**To Reproduce**
See description PLUS I removed the ~/dotfiles directory prior to the restore

**Expected behavior**
I expected the files in the customization directory to be restored during update

**Screenshots**
n/a

**Distribution (please complete the following information):**
 - CachyOS (arch linux)

**Additional context**

**Comment by eljejer** [comment]
I see the problem now: I remove ~/dotfiles/ prior to the install.
So the bash and zsh customization can never be preserved and therefor neither be restored.
However, my customizations in ~/dotfiles/.config/hypr/conf/custom.conf ARE preserved.
How can this be?

**Comment by mylinuxforwork** [comment]
Please follow this guide. https://github.com/mylinuxforwork/dotfiles/wiki/Switch-between-bash-and-zsh

If you delete the target folder for the dotfiles nothing can be restored.The installer will list all possible files and folders to restore if exists.

**Comment by eljejer** [comment]
> Please follow this guide. https://github.com/mylinuxforwork/dotfiles/wiki/Switch-between-bash-and-zsh
> 
> If you delete the target folder for the dotfiles nothing can be restored.The installer will list all possible files and folders to restore if exists.

@mylinuxforwork Yes, if I delete I cannot restore. I understand that. But I still don't understand how the ~/dotfiles/.config/hypr/conf/custom.conf could be restored...
Also, I understand that you went away from ~/dotfiles/.config/zshrc/custom/ subdirectroy and in stead introduced the inject file principle. Correct?
