### ISSUE TITLE
[BUG] ML4W-hyprland-git won't install on Arco Linux  Hyprutils dependency failure 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#181]
**Describe the bug**\
The version of  hyprutils in arco repo is too old for this package causing install to fail\

![image](https://github.com/user-attachments/assets/f463de69-f785-4a4a-9803-0ef72d8b7452)

**To Reproduce**
Install basic arco linux
yay -S ml4w-hyprland-git  

**Expected behavior**
ml4w package would select correct hyprutils

**Workaround ** 
Manually install the hyprutils from extra repo before installing ml4w package 
yay -S extra/hyprutils 

**Screenshots**
![image](https://github.com/user-attachments/assets/99c8e29e-7d7f-427a-b4d7-c0067365dbb9)

![image](https://github.com/user-attachments/assets/b9fd0758-e8ed-45df-981f-ff613e5ab2fc)

**Distribution (please complete the following information):**
![image](https://github.com/user-attachments/assets/e742161a-0e04-4695-ab07-ae83d565f06e)

**Comment by mylinuxforwork** [comment]
Do you think I should add hyprutils to the dependency list directly?

**Comment by dwilliam62** [comment]
Not sure what else you can do,  But for now the correct  version is only in
the extra repo.   Noit sure why Arco hasn't updated theirs yet

Might be worth asking them

**Comment by mylinuxforwork** [comment]
Have added a note to the README and Wiki for Arco Linux users.

**Comment by NeussConsulting** [comment]
@mylinuxforwork 

I have a smimiliar issue, don't know if I should open a new issue for it.

I can't install it on a fresh Arch Linux install.
Error message is:

"Could not find all required packages: roti-wayland"

**Comment by mylinuxforwork** [comment]
> @mylinuxforwork
> 
> I have a smimiliar issue, don't know if I should open a new issue for it.
> 
> I can't install it on a fresh Arch Linux install. Error message is:
> 
> "Could not find all required packages: rofi-wayland"

Just installed it on a Minimal Arch Linux profile installed with archinstall. No issues. Can you try to install rofi-wayland individually and try again?

**Comment by NeussConsulting** [comment]
UNFORTUNATELY I don't have archinstall because it's a VM on a ARM MacBook. There is just archboot available with an ugly Dos looking Setup script 😭😭 I miss Archinstall totally as a Linux Noob that I am.

**Comment by mylinuxforwork** [comment]
Added a note in the installation instructions. Thanks guys for testing.

**Comment by NeussConsulting** [comment]
> Added a note in the installation instructions. Thanks guys for testing.

But not related to my issue, correct?

I think maybe this rofi package does not exist for ARM?

**Comment by mylinuxforwork** [comment]
Try to install the package rofi instead.
