### ISSUE TITLE
Waybar modules.

### ISSUE THREAD

**Issue by Xeo23** [mylinuxforwork/dotfiles#182]
I'm trying to modify the network module to show the bandwidth all the time and also a media control setting.
How can I add, modify or disable modules..? 
I wan to make these changes persistent, if I modify the modules.jsonc will it be overwritten on the update..?

**Comment by mylinuxforwork** [comment]
@Xeo23 Please follow this guide. I would suggest that you protect the modules.json with a hook.sh
https://github.com/mylinuxforwork/dotfiles/wiki/How-to-customize-the-ML4W-Dotfiles
