### ISSUE TITLE
[BUG] Multiple computers under one public IP with ML4W installed is triggering AUR ban/block

### ISSUE THREAD

**Issue by Forge64** [mylinuxforwork/dotfiles#187]
Per title, with multiple computers on a single network/public IP, the updates.sh is being run too often, resulting in a rate limit/temporary ban from the AUR. This is undesirable, and ML4W doesn't seem to expose any settings relating to this background update checking. Simply changing the check interval to something longer would work, but I can't find what is calling the update checker script, to adjust.

Steps to reproduce:
1. Have multiple PCs with ML4W installed powered on and idle. I see this 429 Rate limit reached quite often now with three desktops and one laptop.
2. Wait. (generally 24 hours or less)
3. Get banned.

**Expected behavior**
Not getting rate limited for "AUR abuse" without user action.

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by Forge64** [comment]
![image](https://github.com/user-attachments/assets/b71f188c-84c8-47b2-8198-d8326f53f262)

**Comment by Forge64** [comment]
I have perhaps explained poorly.

In ML4W, there's a little applet that checks for updates. I don't know how often, I'd guess every 10-15 minutes or so? When there are updates, it shows a number, of how many pending updates there are.

When you have more than ~4 computers, all running ML4W, these checks are too frequent, and it's causing the AUR to block my IP. After the block gets put in place, *ALL* AUR access is blocked from my IP. The problem isn't installing ML4W, I've been doing that all along, the problem is that *after* I install ML4W, I lose AUR access most of the time.

I'm just trying to figure out where this update check is being scheduled from, so I can make it fire less often, and I filed a bug because this seems like a good thing to have in settings somewhere, for folks that don't want to dig into all the configuration files yet.

**Comment by mylinuxforwork** [comment]
Now I got you. I can increase the time frame between checks and can make it configurable in the settings.

**Comment by Forge64** [comment]
Holy moly, it was checking every sixty seconds? Thank you very much for the heads up on where the setting was, I never thought to look there, and thank you for addressing the issue I was having.

Since I've stolen your attention for a moment, also thank you very much for making and sharing ML4W, it has been a delight to use and an education to adjust and tinker with. Excellent work; Vielen Dank für ML4W.

**Comment by mylinuxforwork** [comment]
> Holy moly, it was checking every sixty seconds? Thank you very much for the heads up on where the setting was, I never thought to look there, and thank you for addressing the issue I was having.
> 
> Since I've stolen your attention for a moment, also thank you very much for making and sharing ML4W, it has been a delight to use and an education to adjust and tinker with. Excellent work; Vielen Dank für ML4W.

Thank you so much for your feedback.
