### ISSUE TITLE
[BUG]  missing dependency pkgconf for manjaro 

### ISSUE THREAD

**Issue by Neo-29** [mylinuxforwork/dotfiles#188]
**Describe the bug**
Building impossible without `pkgconf`
**To Reproduce**

**Expected behavior**
A clear and concise description of what you 
expected to happen.
Building success 
**Screenshots**

**Distribution (please complete the following information):**
 - Manjaro (gnome) 

**Additional context**

**Comment by mylinuxforwork** [comment]
Have you solved it by adding a package manually?

**Comment by Neo-29** [comment]
Yes

**Comment by mylinuxforwork** [comment]
@Neo-29 What exactly have you installed?

**Comment by Neo-29** [comment]
As specified above
```pkgconf````

**Comment by mylinuxforwork** [comment]
@Neo-29 I think we can close this issue.
