### ISSUE TITLE
[BUG] Waybar does not start in 2nd session in between boots on tty

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#19]
**Describe the bug**
I start Hyprland from tty after login (no display-manager active).
When I exit the Hyprland session returning to the prompt and start Hyprland once more, waybar is not shown.

**To Reproduce**
1. reboot PC
2. login from tty (not display-manager)
3. execute 'Hyperland'
4. waybar is displayed
5. exit Hyprland
6. execute 'Hyprland'
--> waybar is not displayed

**Expected behavior**
Waybar display

**Screenshots**
n/a

**Distribution (please complete the following information):**
 - Manjaro

**Additional context**
Originally mentioned in [this](https://gitlab.com/stephan-raabe/dotfiles/-/issues/387#note_2002227762) post

**Comment by Ahorts** [comment]
Yeah. Sometimes I also experience this with a restart. I did a re-installation it I think it is fixed. Still testing. Try that.

**Comment by mylinuxforwork** [comment]
Have you tried this? https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#waybar-is-not-loading

**Comment by eljejer** [comment]
> Have you tried this? https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#waybar-is-not-loading

Yes, I looked into that suggestion, but the procedure here implies a reboot. And the problem does not occur after a reboot. Only in between reboots

**Comment by eljejer** [comment]
> Yeah. Sometimes I also experience this with a restart. I did a re-installation it I think it is fixed. Still testing. Try that.

I re-installed also, but the issue remains

**Comment by mylinuxforwork** [comment]
@eljejer I was able to replicate the issue in VM based on EndeavourOS. 

From sddm I switched to tty and started Hyprland with the Hyprland command. Waybar loaded up.
Then I exit Hyprland and restarted again with Hyprland command.
Waybar is not loading.
When I launch ~/dotfiles/waybar/launch.sh it triggers a xdg-desktop-portal timeout issue

I have deinstalled xdg-desktop-portal-gtk with sudo pacman -R xdg-desktop-portal-gtk.
Exit Hyprland
Start Hyprland again and waybar is back
Exit Hyprland
Start Hyprland and waybar is back again.

Seams that fixed it with a side effect, that teh dark theme is lost on nautilus.

Can you try to replicate it based on the steps above.

**Comment by mylinuxforwork** [comment]
https://discourse.gnome.org/t/using-adwaita-dark-on-another-compositor/17563/10

**Comment by eljejer** [comment]
> @eljejer I was able to replicate the issue in VM based on EndeavourOS.
> 
> From sddm I switched to tty and started Hyprland with the Hyprland command. Waybar loaded up. Then I exit Hyprland and restarted again with Hyprland command. Waybar is not loading. When I launch ~/dotfiles/waybar/launch.sh it triggers a xdg-desktop-portal timeout issue
> 
> I have deinstalled xdg-desktop-portal-gtk with sudo pacman -R xdg-desktop-portal-gtk. Exit Hyprland Start Hyprland again and waybar is back Exit Hyprland Start Hyprland and waybar is back again.
> 
> Seams that fixed it with a side effect, that teh dark theme is lost on nautilus.
> 
> Can you try to replicate it based on the steps above.

I can confirm: what you experience, I experience as well.

**Comment by eljejer** [comment]
> https://discourse.gnome.org/t/using-adwaita-dark-on-another-compositor/17563/10

@mylinuxforwork After uninstalling xdg-desktop-portal-gtk and testing as per your suggestion, I re-installed xdg-desktop-portal-gtk and altered ~/dotfiles/hypr/hyprland.conf as described in [this](https://discourse.gnome.org/t/using-adwaita-dark-on-another-compositor/17563/14) post ;

commented line `exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`
and added line `exec-once = dbus-update-activation-environment --systemd --all`

Now I can both restart Hyprland in between boots without Waybar issue AND the right theme is applied in nautilus.

I'm not sure if the issue is resolved with this and could be closed maybe?

**Comment by mylinuxforwork** [comment]
This is great. Maybe finally the solution for this effect. Let me test tomorrow and then we can close. Thanks again.

**Comment by mylinuxforwork** [comment]
@eljejer It is still not working in my VM. Firstg launch without any trouble. With the second launch of Hyprland I have again the delay between the launch and that Waybar appears. It feels that the delay is shorter but still there.
No issues with sddm. 

How's your impression today on with your system?

**Comment by eljejer** [comment]
> @eljejer It is still not working in my VM. Firstg launch without any trouble. With the second launch of Hyprland I have again the delay between the launch and that Waybar appears. It feels that the delay is shorter but still there. No issues with sddm.
> 
> How's your impression today on with your system?

@mylinuxforwork Contrary to my earlier experience yesterday, just now I re-started Hyprland in between boots, and now Waybar is not started with me as well. I will keep an eye on it and keep you posted

**Comment by mylinuxforwork** [comment]
Can you check this as well? https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615

**Comment by eljejer** [comment]
> Can you check this as well? [Alexays/Waybar#1828 (comment)](https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615)

@mylinuxforwork As my setup has changed today, I cannot really comment on the original problem anymore:;I wiped my boot disk and installed CachyOS with Hyprland. So no Linux desktop environment anymore, which was KDE Plasma earlier. At the moment I logon with display manger and in this setup Waybar does start on the 2nd session in between boots.
I will deactivate DM and try tty in stead and see what happens

**Comment by eljejer** [comment]
> Can you check this as well? [Alexays/Waybar#1828 (comment)](https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615)

@mylinuxforwork I have disabled the display manager and start Hyprland from tty again. In this setup, so without the packages for a Linux desktop as I had before (KDE Plasma), starting a 2nd session in between reboots is again failing to start Waybar. I will investigate further as per the [link](https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615) you provided and report back later

**Comment by eljejer** [comment]
> Can you check this as well? [Alexays/Waybar#1828 (comment)](https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615)

@mylinuxforwork After deactivating display manager and starting Hyprland from tty, I can confirm that Waybar is not activated on 2nd session in between logins. Also in my new setup.
Then I have altered ~/dotfiles/waybar/launch.sh by adding the following right before the last line where waybar is started:

###
# test https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# end test

I'm however not completely sure if this is what you meant by "can you check this as well? https://github.com/Alexays/Waybar/discussions/1828#discussioncomment-10126615"

Anyway, this change did not result in the display of the waybar in the 2nd session.

**Comment by mylinuxforwork** [comment]
This issue is really tricky. Crazy that the issue not exists when using sddm. Only tty.

**Comment by kerbyyy** [comment]
@mylinuxforwork I'm having this issue yesterday and today. Now it's even worse because Waybar does not load any more even after reboot. I've tried everything, from reinstalling the dotfiles to uninstalling it and installing it again. None worked.

**Comment by mylinuxforwork** [comment]
Have you tried to uninstall xdg-desktop-portal-gtk?

https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#waybar-is-not-loading

**Comment by kerbyyy** [comment]
let me try this, thanks!

**Comment by kerbyyy** [comment]
Hi @mylinuxforwork, I did the troubleshooting guide twice to no avail. I'm gonna try uninstalling the dotfiles, then reinstall it with sddm, im gonna see if that changes something

**Comment by mylinuxforwork** [comment]
@kerbyyy And updates?
