### ISSUE TITLE
[BUG] Workspace's glitch

### ISSUE THREAD

**Issue by 4uror4kn3ght** [mylinuxforwork/dotfiles#192]
**Describe the bug**
Workspaces [all workspaces that are not {1}]  don't work as they are ment to, you cant open applications including the terminal, workspace [2] is particularly buggy: It displays no cursor and if you press [SUPER + 2] while on workspace [1] then the apps running in window 1 appear translucent.

**To Reproduce**
1. Install EOS with xfce on a chromebook
2. run clean install of AUR ML4W both the rolling and main

**Screenshots**

**Distribution (please complete the following information):**
 - EndeavourOS
 - and maybe Vanilla Arch 

**Additional context**
I'm on a chromebook
Kernel is stock and zen

**Comment by 4uror4kn3ght** [comment]
It works for some reason now

**Comment by mylinuxforwork** [comment]
Thanks for testing.
