### ISSUE TITLE
[BUG] Waybar starter and other basic waybar file systems not working recently

### ISSUE THREAD

**Issue by 4uror4kn3ght** [mylinuxforwork/dotfiles#195]
**Describe the bug**
Waybar starter and other basic waybar [config,style.css,module.json] file systems not working on recent updates, even after fresh install.

**To Reproduce**
1. A fresh install rolling release of 2.9.5+
**Distribution (please complete the following information):**
 - EndeavourOS

**Comment by mylinuxforwork** [comment]
@4uror4kn3ght can you update to 2.9.6? 
https://github.com/mylinuxforwork/dotfiles/wiki/Update

**Comment by 4uror4kn3ght** [comment]
[fixed starter](https://discord.com/channels/1188185808277094520/1198365216963047504/1278272181293420624)
