### ISSUE TITLE
[BUG] Please update the wiki for Following reason

### ISSUE THREAD

**Issue by vamsi9955** [mylinuxforwork/dotfiles#196]
**Describe the bug**
As described in the wiki that the hook.tpl and automation.tpl are located in .dotfiles-versions present in home folder but it is not present there instead I found it on .ml4w-hyprland folder so please update the wiki

**Distribution (please complete the following information):**
 - CatchyOS

**Additional context**

**Comment by mylinuxforwork** [comment]
Good catch. Fixed it.
