### ISSUE TITLE
[BUG] Waybar not starting

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#198]
**Describe the bug**

script ~/dotfiles/.config/waybar/launch.sh echoes

`waybar: no process found
:: Theme: /ml4w
eljejer in NOCULAP  ~  dotfiles  .config  waybar                                                                                                                                                  [21:52:07]
➜  [2024-08-27 21:52:08.008] [info] Using configuration file /home/eljejer/.config/waybar/themes/ml4w/config
[2024-08-27 21:52:08.008] [info] Including resource file: ~/.config/ml4w/settings/waybar-quicklinks.json
[2024-08-27 21:52:08.008] [info] Including resource file: ~/.config/waybar/modules.json
[2024-08-27 21:52:08.009] [error] Error parsing JSON: * Line 27, Column 2
  Missing ',' or '}' in object declaration
`

and does not exit
**To Reproduce**

**Expected behavior**

**Screenshots**

**Distribution (please complete the following information):**
 - CachyOS (arch linux)

**Additional context**
I was changing the Waybar theme with Super CTRL T when unexpectedly the Waybar did not refresh and did not appear at all any more

**Comment by mylinuxforwork** [comment]
@eljejer Habe you changed something in the settings app? Hiding modules?

**Comment by eljejer** [comment]
> @eljejer Habe you changed something in the settings app? Hiding modules?

Indeed, the hanging was caused by me having edited ~/dotfiles/.config/waybar/modules.json in the "persistent-workspaces": { section. I had(added persistent WS for 2 different monitors). As a result of which the syntax error: because no ',' is written by the settings app behind the number of WS
