### ISSUE TITLE
[BUG] Custom time format for waybar clock does not show after upgrade

### ISSUE THREAD

**Issue by dfd** [mylinuxforwork/dotfiles#199]
**Describe the bug**
After I ran the update and rebooted, the clock did not reflect my custom format.
The ml4w setting was still in tact in the dotfiles app, but the clock did not match the custom format.
I had to re-edit and save the custom time format again to correct it.

**To Reproduce**
Do a fresh install with 2.9.5
Give a custom time setting in the dotfiles app of
`%b %Od %H:%M`
Then upgrade to 2.9.6 and reboot.
The settings will remain, but the clock will not match the custom format unless it is saved again.

**Expected behavior**
Expected the waybar clock to automatically show the custom time setting.

**Screenshots**
![image](https://github.com/user-attachments/assets/c40e733d-72fd-4c7c-bee8-873d5521e383)
Notice the display does not match the format in the above screenshot.
Should display `Aug 26 22:51`

**Distribution (please complete the following information):**
 - CachyOS

**Additional context**
None.

**Comment by mylinuxforwork** [comment]
@dfd Restore is working now on the latest rolling release. But it is possible that you need change it manually once again before the restore will work next time.
