### ISSUE TITLE
[BUG] error: packages failed to build: bun-bin-1.1.24-1

### ISSUE THREAD

**Issue by MalaskaDeividas** [mylinuxforwork/dotfiles#203]
**Describe the bug**
Followed this video: https://www.youtube.com/watch?v=6B4Kf30CWLg
with a new minimal arch install, installed paru, did paru -S ml4w-hyprland and after an eternity i get error cant build ml4w-hyprland, deps not satisfied bun-bin.

**To Reproduce**
1. Follow mylinuxforwork arch install from this video (dont do hyperland) [https://www.youtube.com/watch?v=kHG5czrQ7WA&list=PLSFRqrhOJDbwqPhu_Zz02kDHMnjgJkt70&index=6](url)
2. Then follow [https://www.youtube.com/watch?v=6B4Kf30CWLg](url) arch install part.

**Expected behavior**
error: cant build ml4w-hyprland, deps not satisfied: bun-bin
error:  packages failed to build: bun-bin 1.1.24-1
marked out of date: bun-bin

**Screenshots**
![IMG_20240828_175701](https://github.com/user-attachments/assets/66bab658-b268-4fae-890d-295ae3990e42)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
using hp elitebook laptop.

**Comment by mylinuxforwork** [comment]
Can you just run 

yay
And then
yay -S bun-bin 
and share the error message?

**Comment by MalaskaDeividas** [comment]
I ran the  paru -S ml4w-hyprland again and i think it installed a different version of it? Not sure, it installed everything but now it rebooted in an black window with redbar saying config error in file /home/myuser/dotfiles/.config/hypr/hyprland.conf at line 41: source= globbing error: found no match. Tyring to update dotfiles, ill update how it goes :D

**Comment by MalaskaDeividas** [comment]
ah same issue, also yay not installed

**Comment by mylinuxforwork** [comment]
Can you check that the wallpaper folder exits in you home directory and pypal is installed by typing

wal

in a terminal

**Comment by hambosto** [comment]
@MalaskaDeividas sometimes i got error when installing ml4w dotfiles using paru on my new machine even installing regular package i got similar issue like ssl error, connection error etc. i switched to yay got no issue so so far.

**Comment by mylinuxforwork** [comment]
> @MalaskaDeividas sometimes i got error when installing ml4w dotfiles using paru on my new machine even installing regular package i got similar issue like ssl error, connection error etc. i switched to yay got no issue so so far.

Interesting. Thanks for testing.

**Comment by mylinuxforwork** [comment]
@MalaskaDeividas @hambosto It is important that your system is up-to-date before starting the installation

sudo pacman -Syu

I have removed the dependency for bun-bin from the rolling release ml4w-hyprland-git
