### ISSUE TITLE
[BUG]  customized hyprpm hyprbars lost upon reboot

### ISSUE THREAD

**Issue by rich-user** [mylinuxforwork/dotfiles#205]
**Describe the bug**
Upon reboot - customization to hyprpm plugins is lost

**To Reproduce**
1.) Enable hyprpm hyprbars

2.) Customize hyprpm hyprbars with buttons in:
    ~/dotfiles/.config/hypr/conf/custom.conf

3.) code:

 plugin {
    hyprbars {
        # example config
        bar_height = 25

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 20, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 20, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(eeee11), 20, 🅰️, alacritty
    }
}

**Expected behavior**
1.) Works great until reboot then hyprbar buttons are gone
2.) hyprpm reload will bring them back

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by ajboni** [comment]
I think you need to a reload at startup 

in your custom.conf
```
# Autostart
exec-once = hyprpm reload -n
```

**Comment by rich-user** [comment]
Oh! Duh! Been one of those days - thank you! 😊

**Comment by rich-user** [comment]
Thanks again!
