### ISSUE TITLE
[BUG]  After updating via yay then 'ml4w-hyprland-setup'    Application defauls for brower, editor, filemgr are reset to defaults 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#206]
**Describe the bug**
I ugraded to today 2.9.6 rolling release via YAY then ran setup script 

Going to the welcome app, all the appllications for browser, filemgr, and editor that I had previsouly changes were returned to defaults.  I tested this with ARco, and Vanilla Arch so far 

**To Reproduce**
1. Upgrade via yay or PARU
2. Run ml4w-hyprland-setup
3. Reboot
4. Check settings via welcome app 

**Expected behavior**
Once edited the application defaults should be retained 

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux
 - EndeavourOS
 - Arco 
 - ... 

*

**Comment by ajboni** [comment]
I'm on EndevourOS aur-git version (2.9.6.1) and I did not encounter that issue. In my case `nemo` is still the default file manager after updating (manually once and several times automated)

**Comment by mylinuxforwork** [comment]
@dwilliam62 Tested as well with 2.9.6.1 and everything is working as expected. Will release 2.9.6.1 on Monday and please test again and reopen the issue if needed.

**Comment by dwilliam62** [comment]
Works fine now.  Tested vanilla, arco, EOS.
