### ISSUE TITLE
[BUG] screenshots saved with the name of the folder if the folder does not exist 

### ISSUE THREAD

**Issue by EuerErhabenheit** [mylinuxforwork/dotfiles#208]
**Describe the bug**
If the default folder "pictures" for saving the screenshots in cause of using localized folder name like "Bilder" does not exist, the recorded screenshot will be saved als file namend "pictures" in the home diretory.

**To Reproduce**
1. Remove or rename the pictures folder
2. record an save a screenshot (I used mode 'selection' and 'save')
3. check folder and files in home directory

**Expected behavior**
Using the localized folder or create a new folder and save the screenshot.

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux
![Pictures1](https://github.com/user-attachments/assets/4753a6c3-3756-4a05-9796-193f6df72f75)

**Additional context**

**Comment by mylinuxforwork** [comment]
@EuerErhabenheit Good catch. I will check.

**Comment by mylinuxforwork** [comment]
@EuerErhabenheit Just pushed the update in the main branch. You can install it already today with yay -S ml4w-hyprland-git and select cleanBuild All.
