### ISSUE TITLE
language keyboard icon

### ISSUE THREAD

**Issue by Ram3zani** [mylinuxforwork/dotfiles#209]
Hi
how can i make always show  layout keyboard icon in waybar. now only i can see keyboard layout when hover on three bar. i mark icon keyboard layout. see screenshot.
![Uploading screenshot123_31082024_002933.jpg…]()

**Comment by mylinuxforwork** [comment]
@Ram3zani In that case I would suggest to create an own custom waybar theme. A good starting point is the waybar starter theme. Or you need to update the modules.conf in ~/.config/waybar and protect your changes with a hook.sh
https://github.com/mylinuxforwork/dotfiles/wiki/Hook-and-Post-Installation-Scripts
