### ISSUE TITLE
[FEATURE] Add "Open Terminal Here" Option to Nautilus Context Menu

### ISSUE THREAD

**Issue by hambosto** [mylinuxforwork/dotfiles#215]
**Summary:**
I suggest adding an "Open Terminal Here" option directly into the Nautilus file manager's right-click context menu. This enhancement would enable users to quickly open their preferred terminal emulator in the current directory, streamlining their workflow.

**Use Case:**
For users of ML4W who use Nautilus as their file manager, opening a terminal in the current directory is a frequent task. While external solutions like the `nautilus-open-any-terminal` package offer this functionality, integrating it natively into Nautilus would provide a more integrated and consistent experience.

**Implementation Suggestion:**
Consider implementing this feature similarly to the existing third-party solutions. Users could configure their preferred terminal emulator using straightforward terminal commands:

1. Install the `nautilus-open-any-terminal` package:
   ```bash
   yay -S nautilus-open-any-terminal
   ```

2. Set the preferred terminal emulator (e.g., Kitty) and use a generic name for consistency:
   ```bash
   gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal 'kitty'
   gsettings set com.github.stunkymonkey.nautilus-open-any-terminal use-generic-terminal-name 'true'
   ```

Integrating this feature into Nautilus would eliminate the need for third-party tools and offer a more seamless experience, especially for ML4W users who rely on Nautilus. The feature should default to a generic "Open Terminal Here" name to maintain consistency across various terminal emulators.

Result: 
![screenshot123_04092024_131347](https://github.com/user-attachments/assets/8770dc79-df48-484d-aac9-fa59c717aaf4)

Source: https://github.com/Stunkymonkey/nautilus-open-any-terminal

**Comment by mylinuxforwork** [comment]
@hambosto This is a great idea. I will implement this for 2.9.7

**Comment by hambosto** [comment]
@mylinuxforwork cool. I think it might be nice to put it in post-installation.

**Comment by mylinuxforwork** [comment]
@hambosto Could tested the "Open Terminal here" feature successfully. Will add it to 2.9.6.3

**Comment by hambosto** [comment]
@mylinuxforwork It works great on my machine. thank you so much for your hard work. i really appreciate it👍

![image](https://github.com/user-attachments/assets/e1f8698f-4112-4b04-99bf-53a5ce759830)

**Comment by mylinuxforwork** [comment]
> @mylinuxforwork It works great on my machine. thank you so much for your hard work. i really appreciate it👍
> 
> ![image](https://private-user-images.githubusercontent.com/106536348/375035109-e1f8698f-4112-4b04-99bf-53a5ce759830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTA2MTgsIm5iZiI6MTcyODQ5MDMxOCwicGF0aCI6Ii8xMDY1MzYzNDgvMzc1MDM1MTA5LWUxZjg2OThmLTQxMTItNGIwNC05OWJmLTUzYTVjZTc1OTgzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNjExNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjIwOWYyMDVmMWViZGZlODMyYTY0NWNjMDY5Y2I0NmZjZGMyMmZjOGJjODdlMzgxMzcwOGJmMzcyYmQyZDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9fHndFAAZRVn47x2EKyVbc45nMINjBd47ElXPCWLD8M)

That’s great. Thanks for testing and your feedback.
