### ISSUE TITLE
[BUG] Pywal fails to generate colours for wallpapers with spaces in filename. 

### ISSUE THREAD

**Issue by Ahorts** [mylinuxforwork/dotfiles#22]
**Describe the bug**
I have fixed this but thought I might just bring it to your attention. Maybe I missed it but 
I had a bunch of wallpapers that had spaces in the filenames and was wondering for the longest time why pywal couldn't generate the colour scheme for some of them.

For anyone wondering just write a bash command to remove all the spaces in the filenames. Now pywal can actually generate the colour scheme for the wallpapers.

```sh
for f in *\ *; do mv "$f" "${f// /_}"; done
```
This replaces all the spaces  in the filename of the wallpapers with an underscore.

I think you can try to add this to the wiki. I remember someone asked a similar question somewhere.

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
Thank you so much for testing and sharing your idea to solve it. I will check it out.

**Comment by mylinuxforwork** [comment]
Thanks again for your help. I have added this comment to the wiki: https://github.com/mylinuxforwork/dotfiles/wiki/Wallpapers
