### ISSUE TITLE
[BUG] Can't update system

### ISSUE THREAD

**Issue by meo209** [mylinuxforwork/dotfiles#222]
**Describe the bug**
When trying to update my system using the ```paru``` or ```yay``` command, 
I get this error ```cp: cannot stat '/home/meo209/.cache/paru/clone/ml4w-hyprland/src/dotfiles-2.9.6.1/share/.': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'ml4w-hyprland-2.9.6.1-1':
error: packages failed to build: ml4w-hyprland-2.9.6.1-1```

**To Reproduce**
Run the ```paru``` command.

**Expected behavior**
The system should update just fine.

**Screenshots**
-

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
This was not happening initially, it just started recently.

**Comment by crashbit666** [comment]
I solved reinstalling package.

yay -S ml4w-hyprland

**Comment by mylinuxforwork** [comment]
@crashbit666 Thanks for testing.
