### ISSUE TITLE
[BUG] Hyprland crash after update

### ISSUE THREAD

**Issue by akgupta1337** [mylinuxforwork/dotfiles#223]
**Describe the bug**
I just installed the latest update on my system Lenovo Legion, I am using gdm and gnome as backup, after installation when i rebooted the system, and tried to login in Hyprland it will bring me back to login screen. It was working fine till the update. 

**To Reproduce**
1. Update ml4w
2. run the installer
3. reboot

**ScreenShots**
![image](https://github.com/user-attachments/assets/a3382518-6177-4262-ab6f-2b1712c55900)

**Expected behavior**
It should be working

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@akgupta1337 Can you run sudo pacman -Syu to ensure that your system is up-to-date and run the installation again?

**Comment by akgupta1337** [comment]
@mylinuxforwork  
A few days ago, I changed my username and was facing issues with the Nautilus file explorer.(as it was trying to access files in old username dir)  I fixed it by create soft link to new username dir , but today, after updating ml4w, I ran into this error. To fix everything, I reinstalled Arch and everything works now. The username change could have been the issue...
