### ISSUE TITLE
[BUG] ZSH load error

### ISSUE THREAD

**Issue by L4FeeR** [mylinuxforwork/dotfiles#225]
**Describe the bug**
i just installed your ml4w hyprland through yay, but zsh not loading, i skipped the first reboot keyboard and shell by not connecting wifi, defaultly keyboard layer set to se, but i managed to change it to us, now zsh only the problem am facing,lemme drop the screenshot

**To Reproduce**

**Expected behavior**

**Screenshots**
![screenshot_08092024_095948](https://github.com/user-attachments/assets/ac9fca76-f6a8-4ee6-871e-5e98e128bdfd)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by L4FeeR** [comment]
??

**Comment by mylinuxforwork** [comment]
@L4FeeR It seams that you have an issue with your local oh-my-zsh installation. Can you make sure that oh-my-zsh is installed correctly on your system? 

https://ohmyz.sh/#install

**Comment by L4FeeR** [comment]
Oh, ok I'll look into it
