### ISSUE TITLE
[BUG] can't delete nautilius

### ISSUE THREAD

**Issue by Aurora3night** [mylinuxforwork/dotfiles#226]
**Describe the bug**
ML4W AUR package seems to stop me from deleting nautilius and other programs it installed from `yay -S ml4w-hyprland-git`
**To Reproduce**
1. Install ML4W
2.Run something like `yay -Rns nautilus` 
3. See error

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@Aurora3night Please check https://www.adamsdesk.com/posts/pacman-remove-package-dependency-checks/

I will close this issue because it is not a ML4W bug.
