### ISSUE TITLE
[FEATURE] Looks like SugarCandy is no more -- long live Eucalyptus?

### ISSUE THREAD

**Issue by armenr** [mylinuxforwork/dotfiles#228]
**Is your feature request related to a problem? Please describe.**
It appears the [Kangie ](https://github.com/Kangie)/[sddm-sugar-candy](https://github.com/Kangie/sddm-sugar-candy) is no longer maintained. 

The repo suggests (in very big letters) to use --> https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop/

**Describe the solution you'd like**
Using https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop/

**Describe alternatives you've considered**
I've considered trying to contribute this change myself, but I'm not confident with my understanding of all the scripts in this codebase to know to be sure.

**Additional context**
None

**Comment by mylinuxforwork** [comment]
@armenr Yes. I know. Will replace it with 2.9.7

**Comment by r3mcos3** [comment]
#311

**Comment by mylinuxforwork** [comment]
Added a new Theme https://github.com/minMelody/sddm-sequoia/ to the main branch.
