### ISSUE TITLE
Waybar clock shows UTC in stead of my local time (CEST)

### ISSUE THREAD

**Issue by hanska-slow** [mylinuxforwork/dotfiles#230]
After updating to 2.9.6.1 the waybar clock shows the UTC time (11:07 Mon) instead of my local CEST time as before. The starship prompt line however displays the correct  time.

❯ timedatectl
                            Local time: Mon 2024-09-09 13:07:38 CEST
                     Universal time: Mon 2024-09-09 11:07:38 UTC
                               RTC time: Mon 2024-09-09 11:07:39
                             Time zone: Europe/Amsterdam (CEST, +0200)
System clock synchronized: yes
                           NTP service: active
                      RTC in local TZ: no

**Comment by hambosto** [comment]
the waybar problem is probably not supporting/misreading the latest tzdata, not a dotfiles problem. try downgrading the tzdata package.

```bash
wget https://archive.archlinux.org/packages/t/tzdata/tzdata-2024a-2-x86_64.pkg.tar.zst
sudo pacman -U tzdata-2024a-2-x86_64.pkg.tar.zst
```

and then restart/logout it will solve this problem.

**Comment by gnussbaum67** [comment]
make sure to edit /etc/pacman.conf and uncomment "IgnorePkg" and add tzdata to it, or else it will try to update it to the broken update

**Comment by ajboni** [comment]
btw, hyperlock has the same issue and probably others relaying on tzdata
more context:
https://github.com/hyprwm/hyprlock/issues/484
https://github.com/Alexays/Waybar/issues/3584

**Comment by hanska-slow** [comment]
Problem solved. Thank you all for your reaction.!
