### ISSUE TITLE
[BUG] wlogout dependency failed to install

### ISSUE THREAD

**Issue by Manuman76** [mylinuxforwork/dotfiles#231]
**Describe the bug**
wlogout depency fail to fetch or validate the PGP key while starting the install. As I can reproduce this on a different system, the problem seems to be on wlogout side.

Encounter this on a brand new minimal Arch install in a VM while I was following the Youtube tutorial.

**Distribution (please complete the following information):**
 - Arch Linux (newly installed minimal setup)
 - Existing Manjaro

**Additional context**
Added comment on the AUR repo of wlogout.

**Work Around**
Before installing ml4w-hyprland:
- git clone https://aur.archlinux.org/wlogout.git
- cd wlogout
- makepkg -si --skippgpcheck
- than launch ml4w-hyprland install -> paru -S ml4w-hyprland

**Comment by mylinuxforwork** [comment]
Thanks for your feedback.
