### ISSUE TITLE
[FEATURE] Added environment variable for Virtualbox/Vmware machines

### ISSUE THREAD

**Issue by gnussbaum67** [mylinuxforwork/dotfiles#233]
**Is your feature request related to a problem? Please describe.**
I use virtualbox and my linux clients are virtual machines.  In order to get alacritty or kitty to work, the following environment variable is required:
env = LIBGL_ALWAYS_SOFTWARE,1

**Describe the solution you'd like**
I was wondering if this could be added to default.conf environment file?

**Describe alternatives you've considered**
alternative is to install foot instead.

**Additional context**

**Comment by mylinuxforwork** [comment]
I have added this environment variable to https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/hypr/conf/environments/kvm.conf

Can be selected in the Settings app.
