### ISSUE TITLE
[BUG] Waybar clock using UTC time instead of currently set timezone

### ISSUE THREAD

**Issue by elliottophellia** [mylinuxforwork/dotfiles#237]
**Describe the bug**
I just re-install my Arch yesterday and then install ML4W Dotfiles from AUR, but I just realized today that my clock using UTC time, I thought maybe my Arch timezone bugged then I check `timedatectl` but :
```
❯ timedatectl
               Local time: Tue 2024-09-10 21:11:07 WIB
               Universal time: Tue 2024-09-10 14:11:07 UTC
               RTC time: Tue 2024-09-10 14:11:07
               Time zone: Asia/Jakarta (WIB, +0700)
               System clock synchronized: yes
               NTP service: active
               RTC in local TZ: no
```
I tried to do something about it and goto `/home/lia/.config/waybar/module.json` find `clock` and then add `"timezone":"Asia/Jakarta",` in it, but still got nothing.

Maybe its about `RTC in local TZ: no` i though, so I did `sudo timedatectl set-local-rtc 1` and reload the Waybar, change its Theme, or change the fmt format, but still in UTC.

Maybe I need to reboot? so I did reboot and after login SDDM, my clock still on UTC.

**To Reproduce**
1. Go to dekstop
2. Find out clock is on UTC ( idk maybe do fresh install and set timezone to Asia/Jakarta )

**Expected behavior**
Clock set to UTC

**Screenshots**
![ss](https://rei.my.id/assets/trashfile/bugwaybar.jpg)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
X

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#wrong-timezone-in-waybar
