### ISSUE TITLE
Universal timezone on waybar clock widget

### ISSUE THREAD

**Issue by Makhsalar** [mylinuxforwork/dotfiles#242]
my waybar is showing me the UTC +00:00 , not my local timezone
how can I change the settings for it

**Comment by mylinuxforwork** [comment]
@Makhsalar Please check https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#wrong-timezone-in-waybar

**Comment by ajboni** [comment]
I think the downgrade is not needed anymore as It seems that the latest Arch Linux update fixed this issue.,

**Comment by mylinuxforwork** [comment]
Great. Thanks for letting us know.
