### ISSUE TITLE
[BUG] Wallpaper swapping is not smooth and resets cursor position and window gap overrides

### ISSUE THREAD

**Issue by LuxLucian** [mylinuxforwork/dotfiles#243]
**Describe the bug**
When switching wallpapers the gaps for tiled windows will reset to the numbers set in /hypr/conf/windows and the cursor will be moved to screen center. The old wallpaper will fade out to the new one, before the background fades to black, before coming back to the new wallpaper. Shortly after this the gaps will change to match those set in the hyprland app config on the waybar. I fixed the gap change by removing the overides in the hyprland app and just using the window themes.

EDIT: Using waypaper with the option in the bottom left set to none as opposed to hyprland seems to fix these issues.

**To Reproduce**
change wallpapers with waypaper or wallpaper.sh

**Expected behavior**
wallpaper changes smoothly, cursor and window themes are not reset

**Distribution (please complete the following information):**
 - EndeavourOS

**Comment by mylinuxforwork** [comment]
You have to enable hyprpaper. sddm is currently not supported 
Can you share a screenshot from your waypaper screen?

**Comment by LuxLucian** [comment]
> You have to enable hyprpaper. sddm is currently not supported Can you share a screenshot from your waypaper screen?
Attempting to set wallpaper images for specific screens with hyprpaper results in both screens having the new images after everything resets. 
![image](https://github.com/user-attachments/assets/c1dfabd3-baa9-4e93-a310-d6c074cd765c)

**Comment by mylinuxforwork** [comment]
@LuxLucian I will change the wallpaper script to waypaper soon.

**Comment by mylinuxforwork** [comment]
@LuxLucian Just started to test waypaper 2.3. Works perfectly with hyprpaper and swww including wallpaper transitions.
Waiting for a feedback from the maintainer of the waypaper AUR and then I will push an update to the main branch and update the ml4w-hyprland-git

**Comment by mylinuxforwork** [comment]
@LuxLucian I have just updated the ml4w-hyprland-git AUR incl. full waypaper support with waypaper 2.3. swww can now be activated (after installation with yay -S swww) incl. wallpaper transitions.
