### ISSUE TITLE
[BUG] Update to 2.9.6.1-1 from 2.9.6.1 fails in CachyOS

### ISSUE THREAD

**Issue by dfd** [mylinuxforwork/dotfiles#244]
**Describe the bug**
Trying to update to 2.9.6.1-1, I get the following error (replacing my username with `user`:

```
❯ paru -Syu
[sudo] password for user: 
:: Synchronizing package databases...
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1)            Old Version  New Version    Make Only
aur/ml4w-hyprland  2.9.6-1      2.9.6.1-1      No

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: ml4w-hyprland 2.9.6.1-1 (Thu 12 Sep 2024 12:34:54 AM EDT)
==> Retrieving sources...
  -> Found ml4w-hyprland
==> Validating source files with md5sums...
    ml4w-hyprland ... Skipped
==> Making package: ml4w-hyprland 2.9.6.1-1 (Thu 12 Sep 2024 12:34:55 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ml4w-hyprland
==> Validating source files with md5sums...
    ml4w-hyprland ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting ml4w-hyprland with bsdtar
==> Sources are ready.
ml4w-hyprland-2.9.6.1-1: parsing pkg list...
==> Making package: ml4w-hyprland 2.9.6.1-1 (Thu 12 Sep 2024 12:34:58 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat '/home/user/.cache/paru/clone/ml4w-hyprland/src/dotfiles-2.9.6.1/share/.': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'ml4w-hyprland-2.9.6.1-1': 
error: packages failed to build: ml4w-hyprland-2.9.6.1-1
```

**To Reproduce**
In CachyOS, install `ml4w-hyprland` 2.9.6.1 with paru.
Then update to `ml4w-hyprland` 2.9.6.1-1.

**Expected behavior**
Expect it to update without error.

**Screenshots**
NA

**Distribution (please complete the following information):**
CachyOS
 - ... 

**Additional context**

**Comment by mylinuxforwork** [comment]
@dfd Can you please check if this folder exists?
/home/user/.cache/paru/clone/ml4w-hyprland/src/dotfiles-2.9.6.1/share/

You can also try to remove the folder
/home/user/.cache/paru/clone/ml4w-hyprland
and try again.

**Comment by dfd** [comment]
I just installed `ml4w-hyprland-git`, which worked fine.

When it failed for this bug, it was trying to access
`~/..cache/paru/clone/ml4w-hyprland/src/dotfiles-2.9.6.1/share/.' `
but it doesn't exist.  I had
`~/.cache/paru/clone/ml4w-hyprland/src/dotfiles-2.9.6/share/`
instead.

**Comment by mylinuxforwork** [comment]
@dfd Great. Thanks for your feedback. But still strange why ml4w-hyprland isn’t installing. No issues on my side on Arch Linux.

**Comment by pega2k** [comment]
> @dfd Great. Thanks for your feedback. But still strange why ml4w-hyprland isn’t installing. No issues on my side on Arch Linux.

That happened to me, the problem is this:

'
==> Retrieving sources...
  -> Found ml4w-hyprland
'

You have that file from version 6.9.6.1 and because of that it not downloading the new version of that file.

You have to delete it to download then new version and everything will work OK.

The PKGBUILD file need to to be modified to allow to detect this and download a new version automatically, probable using for the name of the file the pkgname + pkgversion.

Greetings...

**Comment by mylinuxforwork** [comment]
Yes. You're right. This could be the reason. Let me check.

**Comment by mylinuxforwork** [comment]
@pega2k Just pushed an update of the PKGBUILD file https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ml4w-hyprland
Can you try again if the update is now working?
