### ISSUE TITLE
[BUG]Sidebar's cpu and ram circle progress not working

### ISSUE THREAD

**Issue by synthetic-blood** [mylinuxforwork/dotfiles#245]
**Describe the bug**
CPU and RAM circle monitor in sidebar doesn't work/show hardware stats
![image](https://github.com/user-attachments/assets/ab9ba905-b76d-4732-8799-17001800b999)
**To Reproduce**
Click 'Open Sidebar' to see the two cpu and ram monitors

**Expected behavior**
show stats like in the video
https://youtu.be/CLSOLn4wbeU?si=N8xpSWZEmPrNk-Ym
![image](https://github.com/user-attachments/assets/340c1865-3002-4368-bb46-f4116b37c3ea)

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@synthetic-blood Is this issue still open? I am not able to reproduce it on any of my machines.
