### ISSUE TITLE
[BUG] how to disable oh-my-posh and not use the preset colors of ml4w in the shell?

### ISSUE THREAD

**Issue by bgp65530** [mylinuxforwork/dotfiles#246]
I'm used to using the powerlevel10k theme of oh-my-zsh and I can configure it easyly according to my own habits. I don't like and don't know much about using oh-my-posh. May I ask how to disable oh-my-posh and not use the preset colors of ml4w in the shell?

**Comment by mylinuxforwork** [comment]
@bgp65530 You can completely customize your terminal setup by following the instructions here: https://github.com/mylinuxforwork/dotfiles/wiki/Switch-between-bash-and-zsh
