### ISSUE TITLE
[FEATURE] Make the calendar highlight the current date by default when opening.

### ISSUE THREAD

**Issue by ajboni** [mylinuxforwork/dotfiles#247]
A really small FR

**Is your feature request related to a problem? Please describe.**
If  you open the calendar and select another date, and then close it. The next time you open it shows that date as default. It's confusing!

**Describe the solution you'd like**
I'd like to always highlight the current date when is open

BTW, will you accept PR for this? this could potentially be a good first issue for me to learn a bit about the project

**Comment by mylinuxforwork** [comment]
@ajboni Crazy this should already work like you described it. I will check.

**Comment by mylinuxforwork** [comment]
@ajboni THis is how it looks in the latest version.

![image](https://github.com/user-attachments/assets/5e085117-ab5c-43ff-9b92-3641d5145ce1)

**Comment by ajboni** [comment]
I've double checked and it still has the same behavior (every time you open it, you get the last date you clicked)

I've [asked the developer](https://github.com/Aylur/ags/issues/573#issuecomment-2375342700) and the fix is to select the current date explicitly when opening the calendar

```js
App.connect("window-toggled", (_, name, visible) => {
  if (visible && name == yourWindow.name) {
    // select the day on calender
  }
})
```

**Comment by mylinuxforwork** [comment]
Now I got your point. Will fix it.

**Comment by mylinuxforwork** [comment]
@ajboni Just pushed an update on main branch with the fix.

**Comment by ajboni** [comment]
Works like a charm! thanks for taking the time for this little thing, you are the best Stephan.
PS. Is it too late to ask for a `esc` key or `click-away` to close it ?  🙏

**Comment by ajboni** [comment]
I think this broke again in latest version 2.9.7.BETA :(

**Comment by Tyrn** [comment]
Yes, the bug's still there.
