### ISSUE TITLE
Waybar icon getting smaller after installing ttf-cascadia-code

### ISSUE THREAD

**Issue by hambosto** [mylinuxforwork/dotfiles#25]
hi, 

after I installed the ttf-cascadia-code font via pacman why did the icon on the waybar get smaller? and after I uninstalled it, the waybar icon size returned to normal. By the way, I need ttf-cascadia-code for visual studio code configuration needs.

![screenshot-20240722-130157](https://github.com/user-attachments/assets/53e54f4c-b7a4-4595-9379-a90483723ed3)

**Comment by mylinuxforwork** [comment]
Thanks for testing. Unfortunately every installation of a new font can have side effects with the existing configuration. Unfortunately I cannot change it.

You need to change the font size of the modules individually to restore the original size if it's really needed. 

Why do you need this font for your development?

**Comment by hambosto** [comment]
i need a font ligature and some italics for my vscode configuration. is there a way to install independent fonts without intervening the fonts in the dot configuration file? I only need Cascadia code in VScode. Otherwise there is no problem at all for ML4W dotfiles, everything runs well and of course very perfect.

**Comment by mylinuxforwork** [comment]
Understood. Unfortunately there is no way to install it without an effect on waybar. Can you try to replace an icon in modules.conf temporarily with an icon from https://www.nerdfonts.com/cheat-sheet

Just search and copy the glyph.

Would be interested if the effects only happens with font awesome.

**Comment by mylinuxforwork** [comment]
I could replicate your observation and have added a new feature issue to solve this for all tty-fonts by replacing the icons with SVGs. https://github.com/mylinuxforwork/dotfiles/issues/29

Then I will close this issue. And please follow https://github.com/mylinuxforwork/dotfiles/issues/29 to stay up-to-date.
