### ISSUE TITLE
[BUG] Screen sharing during zoom/google meet presentation not working properly

### ISSUE THREAD

**Issue by Iamloumie** [mylinuxforwork/dotfiles#251]
**Describe the bug**
Sharing my screen during zoom meeting/google meet is not working fine, at times it takes a while before it works on chromium, 
at some time it doesn't work at all even after trying repeatedly.. but screen sharing doesn't work on mozilla firefox at all..

**To Reproduce**
1. Go to 'google meet url or zoom url'
2. Initiate a meeting
3. Click on 'present screen during the meeting'
4. It doesn't work, at times, it only shows the google account profile picture

**Expected behavior**
It should share the selected screen without stress

**Distribution (please complete the following information):**
 - EndeavourOS

**Additional context**
Sometimes, screen sharing works on chromium, sometimes it doesn't.... It doesn't work on mozilla firefox at all... its blank

**Comment by mylinuxforwork** [comment]
Can you check this page on the Hyprland Wiki? https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/
I use Screensharing every day with Teams running in Edge and screen recording with OBS Studio.

**Comment by bwafi** [comment]
i have same issue with screen sharing, I can't screen sharing in browser google meet and zoom

**Comment by Iamloumie** [comment]
> Can you check this page on the Hyprland Wiki? https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/ I use Screensharing every day with Teams running in Edge and screen recording with OBS Studio.

thank you for this update... installing microsoft edge solved the whole issue.. thank you

**Comment by mylinuxforwork** [comment]
@Iamloumie Great. Thanks for your feedback.

**Comment by Xeo23** [comment]
i have the same issue  and also i can't even chromecast entire desktop on my android tv through chromium browser cast feature.

**Comment by Iamloumie** [comment]
What’s your laptop model?

**Comment by Xeo23** [comment]
I got it working, by installing pipewire and removing pulseaudio.

**Comment by mylinuxforwork** [comment]
Great.
