### ISSUE TITLE
[BUG] Error while trying to update ml4w-hyprland

### ISSUE THREAD

**Issue by oztopenessafa** [mylinuxforwork/dotfiles#254]
Whenever I'm trying to update the package through yay or the updater I'm getting an error saying that /home/oztopenessafa/.cache/yay/ml4w-hyprland/src/dotfiles-2.9.6.1/share/. doesn't exist the only folder in src that exists is dotfiles-2.9.6  

![image](https://github.com/user-attachments/assets/338cc50e-ad93-45ba-a7fe-7281ba602475)
- EndeavourOS

**Comment by mylinuxforwork** [comment]
I know it's an issue.

Can you try to select cleanbuild at the beginning and try again?

You can also try to clean the cache from the Welcome app first. Settings, system, clear cache and try again.

Thanks for testing and your feedback in advance.

**Comment by mylinuxforwork** [comment]
@oztopenessafa You can also try this. https://github.com/mylinuxforwork/dotfiles/issues/244

I will fix the pkgbuild as soon as possible.

**Comment by oztopenessafa** [comment]
Cleaning up the cache in the welcome app and retrying the update solved it in my case already.
But yeah thanks for all the methods you've given.

**Comment by mylinuxforwork** [comment]
Thanks for your feedback. I will keep that ticket open in case someone else need this solution as well.

**Comment by mylinuxforwork** [comment]
@oztopenessafa @Vladkarok @hasecilu @Codesmith28 Just pushed an update of the PKGBUILD file https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ml4w-hyprland
Can you try again if the update is now working?
