### ISSUE TITLE
PulseAudio no sound

### ISSUE THREAD

**Issue by h3-Hanouzz** [mylinuxforwork/dotfiles#259]
Whenever I got into my newly installed ML4W Arch system, everything was fine. Except for the audio. So I clicked on where the audio should've been and I noticed it was taking forever to connect to PulseAudio, so I checked and it wasn't even installed. So after installing it, I can get to the audio menu, but I can't hear anything playing. Does anyone know why this is?

**Comment by Xeo23** [comment]
hey can you help please.. i m having same issue
