### ISSUE TITLE
[BUG] Weird issue with WayBar Not working @ Startup

### ISSUE THREAD

**Issue by armenr** [mylinuxforwork/dotfiles#260]
**Describe the bug**
When logging into my desktop environment, WayBar does not appear to start successfully. 

BUT, if I immediately open a terminal and run `systemctl --user start xdg-desktop-portal-gtk.service`, WayBar suddenly loads without any other intervention (I don't need to run `launch.sh` or anything) 

This seems to happen sporadically, and I find it happens more consistently when my laptop is not plugged into a power source (when it runs on battery power, and without an external display connected).

**To Reproduce**
1. Reboot computer
2. Login from the candyland-themed login manager
3. WayBar doesn't load
4. run `systemctl --user start xdg-desktop-portal-gtk.service`
5. WayBar magically loads

**Expected behavior**
WayBar loads normally when logging in.

**Distribution (please complete the following information):**
 - CachyOS
 - The only things in my custom.conf are the following:

```
# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# Workaround for Gnome + Vulkan b0rkness
# ref: https://gitlab.gnome.org/GNOME/gtk/-/issues/7022
# ref: https://github.com/hyprwm/Hyprland/issues/7854
env=GSK_RENDERER,ngl

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

#########################
# Laptop Lid behaviors  #
#########################

# Safely laptop display when lid is closed
bindl = , switch:on:Lid Switch, exec, /home/x3r0/.config/hypr/custom-scripts/manage_display.sh closed

# Safely enable laptop display when lid is opened
bindl = , switch:off:Lid Switch, exec, /home/x3r0/.config/hypr/custom-scripts/manage_display.sh opened

##########################
# Display Configurations #
##########################

monitor=desc:Lenovo Group Limited 0x8AAF,3072x1920@120.0,5120x0,1.333333

```

**Comment by mylinuxforwork** [comment]
Thanks for testing. I can test adding systemctl --user start xdg-desktop-portal-gtk.service to the autostart.conf as default.

You can try to add this command to your custom.conf with exec-once = systemctl --user start xdg-desktop-portal-gtk.service
