### ISSUE TITLE
[BUG] Error message on waybar

### ISSUE THREAD

**Issue by Veicm** [mylinuxforwork/dotfiles#263]
**Describe the bug**
I have the files in the standard version so not Rolling Release installed as described in the instructions and this error message has appeared "Config error in file /home/*User Name */dotfiles/.config/hyprland.conf at line 41 : source= globbing error: found no match" also my background and waybar was not visible and the programs only start slowly.

**To Reproduce**
1. Enter "yay -S ml4w-hyprland" in the command line

2. Enter "ml4w-hyprland-setup" in the command line and follow the instructions

3. See error

**Expected behavior**
Hyprland starts with the configuration that I saw in the associated YouTube video 

**Screenshots**
![IMG_1519](https://github.com/user-attachments/assets/93e40c74-5fa7-4ebc-902d-a7018b250956)

**Distribution (please complete the following information):**
 - EndeavourOS

**Additional context**
I do not understand exactly where the error lies and can therefore only describe what I notice as a user. I'm very sorry but I still hope for help thank you in advance.

**Comment by marshoepial** [comment]
I have this same issue on the standard release using the steps you describe on Arch Linux.

On my machine, there is no `.cache/wal` directory after running the install script, which the hypr config seems to be trying to read? However wal is installed.

**Comment by Veicm** [comment]
Now it works after a short reinstallation and downloading the wallpaper collection. But waybar is not displayed to me even though I have activated it in the settings and no error message is displayed.

**Comment by mylinuxforwork** [comment]
@Veicm  Can you reboot again?

**Comment by Veicm** [comment]
I just did but the problem still exists and I just noticed that after reinstalling the pre installation script did not start.

**Comment by mylinuxforwork** [comment]
You can start the post script from the welcome app. You can start it from app launcher with SUPER+CTRL+Return

**Comment by Veicm** [comment]
I ran the post script again I was asked which shell I want to use I selected bash and then restarted the program but waybar is still not displayed

**Comment by mylinuxforwork** [comment]
OK. Then cd into .config/waybar and launch waybar manually with ./launch.sh
Any error messages?

**Comment by Veicm** [comment]
De These one 

![image](https://github.com/user-attachments/assets/4f7edfda-c945-4fa0-8533-a0692f8f374d)

Do you Need a Translationen?

**Comment by Veicm** [comment]
I just did the same thing again and now it worked thank you very much for your help.

**Comment by Veicm** [comment]
And now it didn’t work again and then again apparently you have to wait after the error message comes and then enter ./launch.sh again.

**Comment by mylinuxforwork** [comment]
Can you try to uninstall yay -R xdg-desktop-portal-gtk and reboot.

**Comment by Veicm** [comment]
It seems to work perfectly now. Thanks again for your help

**Comment by mylinuxforwork** [comment]
> It seems to work perfectly now. Thanks again for your help

Great. Thanks for your feedback.
