### ISSUE TITLE
[BUG] Error in system-monitor.sh

### ISSUE THREAD

**Issue by kcooper98** [mylinuxforwork/dotfiles#264]
**Describe the bug**
The system-monitor.sh script in `~/.config/ml4w/settings` executes mission-center which doesn't exit. This causes the click action of the waybar module to fail. I believe it should be missioncenter without the '-'.

**Expected behavior**
Mission center should launch when the CPU/Memory/Harddisc waybar modules are clicked.

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
```
❯ which missioncenter
/usr/bin/missioncenter
```

**Comment by mylinuxforwork** [comment]
@kcooper98 I believe it comes from your update of the dotfiles. The latest version includes htop as default but offers missioncenter as an option.

This os the default settings for the system monitor 
https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/ml4w/settings/system-monitor.sh

**Comment by kcooper98** [comment]
Strangely, I don't recall making any change there from htop, but it's probably just a mistake on my end. Thank you!
