### ISSUE TITLE
[BUG] Setting workspaces to 10 reverts back to 5 when changing waybar or on updates

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#27]
Original from https://gitlab.com/dwilliam62

**Describe the bug**
The number of workspaces have been changed to 10 via the Dotfiles App. After updating the Dotfiles with the installer the number of workspaces goes back to 5 (default). 
The number of workspaces couldn't be restored successfully.

**To Reproduce**
1. Change the number of workspaces to 10
2. Update the Dotfiles
3. waybar shows the default 5 workspaces

**Expected behavior**
After an update the number of workspaces should be restored.

**Screenshots**
![image](https://github.com/user-attachments/assets/e4c2aa81-defe-4d15-a3f6-711182e68c48)
![image](https://github.com/user-attachments/assets/a5e62291-e552-4f17-a05a-aeb8e74f8282)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
[Add any other context about the problem here.](https://gitlab.com/stephan-raabe/dotfiles/-/issues/386)

**Comment by mylinuxforwork** [comment]
Fixed on main by adding the optimized replacement function from the settings script.

**Comment by PSGitHubUser1** [comment]
> Fixed on main by adding the optimized replacement function from the settings script.

how did you changed the cursor?
I also want to do it.. but it doesn't work

I got the default Bibata Light one
