### ISSUE TITLE
[FEATURE] Multi Monitor Setup

### ISSUE THREAD

**Issue by Veicm** [mylinuxforwork/dotfiles#270]
**Is your feature request related to a problem? Please describe.**
I use a laptop and an additional monitor that is permanently installed and I would like that I can use the two monitors together, in a good configuring form.

**Describe the solution you'd like**
It would be very nice to white for example the worsckspaces 1-5 to the one monitor and 6-9 to the other monitor. What would be important to me if you separate the laptop from the screen you have all workspace only on the laptop. It would also be nice if you could change the workspace to ascend in a graphical surface.

**Describe alternatives you've considered**
It would also be ok if a worckspace on both monitors would be the same so that in the principle 2 window could run in the fully frame or in split view several windows on both screens but if you change the workspace the windows on both screens will also change.

**Additional context**
N/A

**Comment by Veicm** [comment]
Where can I find config.

**Comment by eljejer** [comment]
Hi,
There is some info on this subject in

https://discord.com/channels/1188185808277094520/1280077644225839147

**Comment by Veicm** [comment]
Now it works but how do I have to adjust it to adjust which screen is on the left and which is on the right?

**Comment by eljejer** [comment]
> Now it works but how do I have to adjust it to adjust which screen is on the left and which is on the right?

There is info on that in the ML4W discord channel:

https://discord.com/channels/1188185808277094520/1280077644225839147
