### ISSUE TITLE
[BUG]   On instructions for using your dotfiles on other distros add  Change KB layout before copying 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#275]
**Describe the bug**
If you strictly follow you instructions here: 
https://github.com/mylinuxforwork/dotfiles/wiki/Using-ML4W-Dotfiles-on-other-distributions

You end up with german keyboard.  I use US so that doesn't work well 

Suggesting adding instructions on how to set that before copying.  And suggest backing up files first 

**To Reproduce**
  Copy . -r ~/.config 

**Expected behavior**
Not setting German keyboard by default 

**Distribution (please complete the following information):**
  this was on NIXOS but distro doesn't matter

**Comment by mylinuxforwork** [comment]
@dwilliam62 Thanks for bringing this up. I have updated the wiki page accordingly.
