### ISSUE TITLE
[FEATURE] choose gaps = 0

### ISSUE THREAD

**Issue by j5onrf** [mylinuxforwork/dotfiles#278]
**Describe the solution you'd like**
Can you allow us to choose gaps = 0 from the ui? Right now it only goes to 1.

**Comment by mylinuxforwork** [comment]
@j5onrf Good point. Should be possible. I will check.

**Comment by j5onrf** [comment]
[note] I just noticed that with "gaps in" set to 0 you can no longer grab the window to resize. You can still use keyboard to do it.

**Comment by mylinuxforwork** [comment]
@j5onrf Just pushed an update of the Hyprland App into the dotfiles to enable gaps of 0.

**Comment by j5onrf** [comment]
I would like to change these to gaps=0 in the UI. I can do it from ~/.config/ml4w-hyprland-settings/hyprctl.json. It is not a problem. Latest update v2.9.6.2 works perfect!
![Screenshot-2024-10-08_18:09:53](https://github.com/user-attachments/assets/77927c54-7725-4bda-9b52-8b93459faf2b)
