### ISSUE TITLE
Cursor became faster using these dots 

### ISSUE THREAD

**Issue by 7Badu** [mylinuxforwork/dotfiles#279]
So, i dont know why, but when i installed these dots, my mouse cursor became incredibly faster on arch. Also, when i turn on raw input using any aplication, the cursor turns back to the normal speed

**Comment by mylinuxforwork** [comment]
@7Badu Can you try to modify the sensitivity in this file .config/hypr/conf/keyboard.conf

**Comment by mylinuxforwork** [comment]
@7Badu Any updates?

**Comment by mylinuxforwork** [comment]
@7Badu I will close this issue for now. Please reopen it in case of support needed.
