### ISSUE TITLE
[FEATURE]  Add noto-fonts-cjk to ml4w-hyprland-git Dependencies for Proper CJK Character Rendering

### ISSUE THREAD

**Issue by hambosto** [mylinuxforwork/dotfiles#285]
**Problem**
On Arch Linux, Chinese, Japanese, and Korean (CJK) characters display as unreadable squares or pixelated text in some applications.

**Solution**
Install the `noto-fonts-cjk` package with:

```bash
sudo pacman -S noto-fonts-cjk
```

This package provides proper rendering for CJK characters across the system.

**Alternatives**
1. Using other font packages, but `noto-fonts-cjk` is more comprehensive.
2. Asking users to install manually, but this leads to inconsistency.

**Additional Context**
Installing this package ensures CJK language compatibility without extra configuration.

**Before**
![image](https://github.com/user-attachments/assets/76e55668-fc00-4e4b-b680-1a9c9516bbf1)

**After**
![image](https://github.com/user-attachments/assets/3de2ca99-bbc4-40d9-b229-65963dc2f6a8)

**Comment by mylinuxforwork** [comment]
@hambosto  The package is ~300MB. What about mentioned this in the Wiki?

**Comment by hambosto** [comment]
@mylinuxforwork good idea to mention in Wiki, optional but maybe some people need it.

**Comment by hambosto** [comment]
@mylinuxforwork good idea to mention in Wiki, optional but maybe some people need it.
