### ISSUE TITLE
[FEATURE] Add option to change the shell to zsh

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#30]
**Is your feature request related to a problem? Please describe.**
Original by https://gitlab.com/ahnafbackup222
zsh has more features and has things like better autocomplete, so it would be a very nice option to have as an option in the installer. I just copied my Zsh configuration from .bashrc to .zshrc and it is working fine.

**Describe the solution you'd like**
Original by https://gitlab.com/bknight2k
Sounds good but could i suggest a enhancement from a generic .zsh files
Maybe have something like this
.zsh has only imports files
in $HOME/dotfiles/zsh create a modular structure
```
$HOME/dotfiles/zsh/.zsh
$HOME/dotfiles/zsh/zsh-aliases
$HOME/dotfiles/zsh/zsh-exports
$HOME/dotfiles/zsh/zsh-functions
```
This way people could maintain there own zsh files without having to manually update them for every time your dot files change. Ideally aliases and exports could be used with bash and zsh hopefully.

**Additional context**
Can be added as an option to the installer or to the ML4W Welcome App.

**Comment by NeussConsulting** [comment]
Can we somehow include Oh My Zsh here.

**Comment by dwilliam62** [comment]
I second the adding of ZSH    JaKoolit has a very nice config for it, if you want to get some ideas 

![image](https://github.com/user-attachments/assets/21a2356c-882e-4db0-a175-dd6ac7a98ec3)

**Comment by dwilliam62** [comment]
Oh!  If you do add ZSH   Do please also add a source for .zshrc-custom as you do for .bashrc

**Comment by mylinuxforwork** [comment]
> Oh! If you do add ZSH Do please also add a source for .zshrc-custom as you do for .bashrc

Of course.

**Comment by mylinuxforwork** [comment]
```
#           _
#   _______| |__  _ __ ___
#  |_  / __| '_ \| '__/ __|
# _ / /\__ \ | | | | | (__
#(_)___|___/_| |_|_|  \___|
#
# by Teodor Orzechowski (2023)
# -----------------------------------------------------
# ~/.zshrc
# -----------------------------------------------------

for f in ~/.config/zshrc/*; do source $f; done
```

**Comment by mylinuxforwork** [comment]
@dwilliam62 Which plugin manager for zsh would you sugges/prefer? Oh-My-ZSH or Zinit?

**Comment by ElectroPerf** [comment]
> @dwilliam62 Which plugin manager for zsh would you sugges/prefer? Oh-My-ZSH or Zinit?

oh my zsh is the way to go. also go with oh-my-posh as the prompt

**Comment by mylinuxforwork** [comment]
> > @dwilliam62 Which plugin manager for zsh would you sugges/prefer? Oh-My-ZSH or Zinit?
> 
> 
> 
> oh my zsh is the way to go. also go with oh-my-posh as the prompt
> 
> 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/fd1e71f3-9821-467f-a598-4687511d9fbc)
> 
> 
> 
> 

Thanks. Which oh my posh theme would you suggest as default?

**Comment by ElectroPerf** [comment]
> > > @dwilliam62 Which plugin manager for zsh would you sugges/prefer? Oh-My-ZSH or Zinit?
> > 
> > 
> > oh my zsh is the way to go. also go with oh-my-posh as the prompt
> > ![image](https://private-user-images.githubusercontent.com/76483474/356849348-fd1e71f3-9821-467f-a598-4687511d9fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTQ2MDcsIm5iZiI6MTcyMzcxNDMwNywicGF0aCI6Ii83NjQ4MzQ3NC8zNTY4NDkzNDgtZmQxZTcxZjMtOTgyMS00NjdmLWE1OTgtNDY4NzUxMWQ5ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MWFkZTg5OGVjYzkwYjdkOGQ3NjRjNTRmNjExYTI4MGVhMmY5NmRjZGRiMDk2NTYwZTdjY2U2MWZlYTVkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ukgW9rlJjqc-xAE5TJQLy0jE4ZFgDIx8DxoU7MhFBWM)
> 
> Thanks. Which oh my posh theme would you suggest as default?

https://github.com/ElectroPerf/dotfiles/blob/dots/.zshrc#L197

This sweet custom catpuccin theme

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/wiki/Switch-between-bash-and-zsh
