### ISSUE TITLE
[BUG] Wallpaper Color Scheme not consistent

### ISSUE THREAD

**Issue by Ahorts** [mylinuxforwork/dotfiles#301]
**Describe the bug**
Colour Scheme changes every other wallpaper. So if I change the wallpaper and the colour scheme changes, the next wallpaper does not change the color scheme. However, changing the wallpaper again changes the scheme to the new wallpaper.(alternating).

I noticed after look around that in the ``/home/user/.config/ml4w/cache`` folder that whenever I change the wallpaper, a file named ``wapaper_running`` is created. However, changing the wallpaper again results in the deletion of that file and the new colour scheme is not generated. 

I opened the ``wallpaper.sh`` file and noticed an if statement which deletes the file and exits the script without changing the colour scheme to match the new wallpaper. I ended up commenting out the exit part of the if statement and that seems to have fixed it.

```sh

if [ -f $waypaper_running ] ;then 
   rm $waypaper_running
   # exit
else
    touch $waypaper_running
fi

```
However, I doubt this is the right solution to fixing this bug.
Any thoughts?

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@Ahorts Thanks for reporting the issue. I have the same issue on my system. Working on it...

**Comment by Ahorts** [comment]
Ok. I will check it out
