### ISSUE TITLE
[BUG]  ML4w Dotfiles Settings icon does not launch settings

### ISSUE THREAD

**Issue by skinnypuppy** [mylinuxforwork/dotfiles#304]
**Describe the bug**

Clicking the left gear icon to open ML4W Dotfiles settings does not open anything.

**To Reproduce**

**Expected behavior**

Expected behavior would be to open the ML4W Dotfiles Settings app, it does work from the sidebar menu though.

**Screenshots**

![screenshot_08102024_165406](https://github.com/user-attachments/assets/9e0acd31-9064-4c59-8359-9e57654b8060)

**Distribution (please complete the following information):**
 - Arch Linux
 - EndeavourOS
 - Manjaro
 - ... 

I am using Vanilla Arch installed 10/08, have also tested on BlackArch and AthenaOS (both pentest ARCH distros)

**Additional context**

**Comment by mylinuxforwork** [comment]
@skinnypuppy You are right. Missed it to change with the new executable name. Will fix it.

**Comment by mylinuxforwork** [comment]
@skinnypuppy Just pushed an update to main branch.
