### ISSUE TITLE
[BUG] Installation issues on EndeavourOS libicui18n.so.73: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mati1414** [mylinuxforwork/dotfiles#305]
**Describe the bug**
Cannot install hyprland ML4W on Endevour OS

**To Reproduce**
1. Open terminal and run yay -S ml4w-hyprland-git or yay -S ml4w-hyprland

**Expected behavior**
Hyprland is installed

**Screenshots**
No screenshots, logs provided below

**Distribution (please complete the following information):**
 - EndeavourOS

**Additional context**
Attaching log from the installation:

[mati@R2D2 ~]$ yay -S ml4w-hyprland-git
AUR Dependency (1): aylurs-gtk-shell-1.8.2-3
AUR Explicit (1): ml4w-hyprland-git-2.9.6.2.r4.g0a89f07-1
Sync Make Dependency (4): meson-1.5.2-1, glib2-devel-2.82.1-2, npm-10.9.0-1, typescript-5.6.2-1
:: PKGBUILD up to date, skipping download: ml4w-hyprland-git
:: PKGBUILD up to date, skipping download: aylurs-gtk-shell
2 ml4w-hyprland-git                (Build Files Exist)
1 aylurs-gtk-shell                 (Build Files Exist)
==> Paczki do zbudowania od zera?
==> [N]one [A]Wszystkie [Ab]Anuluj [I]Zainstalowane [No]Nie zainstalowane lub (1 2 3, 1-3, ^4)
==> n
2 ml4w-hyprland-git                (Build Files Exist)
1 aylurs-gtk-shell                 (Build Files Exist)
==> Pokazać różnice?
==> [N]one [A]Wszystkie [Ab]Anuluj [I]Zainstalowane [No]Nie zainstalowane lub (1 2 3, 1-3, ^4)
==> n
==> Tworzenie pakietu: ml4w-hyprland-git 2.9.6.2.r4.g0a89f07-1 (śro, 9 paź 2024, 10:37:23)
==> Pobieranie źródeł...
-> Aktualizowanie ml4w-hyprland-git repozytorium git...
==> OSTRZEŻENIE: Pomijanie weryfikacji podpisów PGP plików źródłowych.
==> Sprawdzanie plików source za pomocą md5sums...
ml4w-hyprland-git ... Pominięto
==> Tworzenie pakietu: aylurs-gtk-shell 1.8.2-3 (śro, 9 paź 2024, 10:37:24)
==> Pobieranie źródeł...
-> Znaleziono aylurs-gtk-shell-1.8.2.tar.gz
==> OSTRZEŻENIE: Pomijanie weryfikacji podpisów PGP plików źródłowych.
==> Sprawdzanie plików source za pomocą sha256sums...
aylurs-gtk-shell-1.8.2.tar.gz ... Zgadza się
:: Usunąć zależności potrzebne do zbudowania po instalacji? [t/N] t
:: (1/2) Przetwarzam SRCINFO: ml4w-hyprland-git
:: (2/2) Przetwarzam SRCINFO: aylurs-gtk-shell
rozwiązywanie zależności…
szukanie sprzecznych pakietów...

Pakiet (9)         Nowa wersja  Zmiana

extra/ninja        1.12.1-1      0,38 MiB
extra/node-gyp     10.2.0-1      7,39 MiB
extra/nodejs-nopt  7.2.0-2       0,03 MiB
extra/python-tqdm  4.66.5-1      0,60 MiB
extra/semver       7.6.3-1       0,09 MiB
core/glib2-devel   2.82.1-2      1,19 MiB
extra/meson        1.5.2-1      12,73 MiB
extra/npm          10.9.0-1      8,76 MiB
extra/typescript   5.6.2-1      21,39 MiB

Do zainstalowania:  52,55 MiB

:: Kontynuować instalację? [T/n] t
(9/9) sprawdzanie kluczy w bazie                                                                                               [----------------------------------------------------------------------------] 100%
(9/9) sprawdzanie spójności pakietów                                                                                           [----------------------------------------------------------------------------] 100%
(9/9) wczytywanie listy plików                                                                                                 [----------------------------------------------------------------------------] 100%
(9/9) sprawdzanie konfliktów plików                                                                                            [----------------------------------------------------------------------------] 100%
:: Przetwarzanie zmian pakietu...
(1/9) instalowanie nodejs-nopt                                                                                                 [----------------------------------------------------------------------------] 100%
(2/9) instalowanie semver                                                                                                      [----------------------------------------------------------------------------] 100%
(3/9) instalowanie node-gyp                                                                                                    [----------------------------------------------------------------------------] 100%
Opcjonalne zależności dla node-gyp
gcc: to build C++ modules [zainstalowano]
make: to build C++ modules [zainstalowano]
python: to build C++ modules [zainstalowano]
(4/9) instalowanie npm                                                                                                         [----------------------------------------------------------------------------] 100%
Opcjonalne zależności dla npm
git: for dependencies using Git URL's [zainstalowano]
(5/9) instalowanie typescript                                                                                                  [----------------------------------------------------------------------------] 100%
(6/9) instalowanie ninja                                                                                                       [----------------------------------------------------------------------------] 100%
(7/9) instalowanie python-tqdm                                                                                                 [----------------------------------------------------------------------------] 100%
Opcjonalne zależności dla python-tqdm
python-requests: telegram [zainstalowano]
(8/9) instalowanie meson                                                                                                       [----------------------------------------------------------------------------] 100%
(9/9) instalowanie glib2-devel                                                                                                 [----------------------------------------------------------------------------] 100%
:: Uruchamianie po-transakcji...
(1/1) Arming ConditionNeedsUpdate...
==> Tworzenie pakietu: aylurs-gtk-shell 1.8.2-3 (śro, 9 paź 2024, 10:37:32)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> Pobieranie źródeł...
-> Znaleziono aylurs-gtk-shell-1.8.2.tar.gz
==> Sprawdzanie plików source za pomocą sha256sums...
aylurs-gtk-shell-1.8.2.tar.gz ... Zgadza się
==> Usuwanie istniejącego katalogu $srcdir/...
==> Rozpakowywanie źródeł...
-> Rozpakowywanie aylurs-gtk-shell-1.8.2.tar.gz za pomocą bsdtar
==> Źródła są gotowe.
==> Tworzenie pakietu: aylurs-gtk-shell 1.8.2-3 (śro, 9 paź 2024, 10:37:33)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> OSTRZEŻENIE: Użycie istniejącego drzewa $srcdir/
==> Usuwanie istniejącego katalogu $pkgdir/...
==> Rozpoczynanie build()...
node: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
==> BŁĄD: Wystąpił błąd w build().
Przerywam...
-> Failed to install layer, rolling up to next layer.error:błąd podczas budowania: aylurs-gtk-shell - exit status 4
==> Tworzenie pakietu: aylurs-gtk-shell 1.8.2-3 (śro, 9 paź 2024, 10:37:33)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> Pobieranie źródeł...
-> Znaleziono aylurs-gtk-shell-1.8.2.tar.gz
==> Sprawdzanie plików source za pomocą sha256sums...
aylurs-gtk-shell-1.8.2.tar.gz ... Zgadza się
==> Usuwanie istniejącego katalogu $srcdir/...
==> Rozpakowywanie źródeł...
-> Rozpakowywanie aylurs-gtk-shell-1.8.2.tar.gz za pomocą bsdtar
==> Źródła są gotowe.
==> Tworzenie pakietu: aylurs-gtk-shell 1.8.2-3 (śro, 9 paź 2024, 10:37:35)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> OSTRZEŻENIE: Użycie istniejącego drzewa $srcdir/
==> Usuwanie istniejącego katalogu $pkgdir/...
==> Rozpoczynanie build()...
node: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
==> BŁĄD: Wystąpił błąd w build().
Przerywam...
-> błąd podczas budowania: aylurs-gtk-shell-exit status 4
==> Tworzenie pakietu: ml4w-hyprland-git 2.9.6.2.r4.g0a89f07-1 (śro, 9 paź 2024, 10:37:35)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Brakujące zależności:
-> aylurs-gtk-shell
==> Sprawdzanie zależności potrzebnych do budowy...
==> BŁĄD: Nie udało się rozwiązać wszystkich zależności.
-> błąd podczas budowania: ml4w-hyprland-git-exit status 8
sprawdzanie zależności…
:: glib2 opcjonalnie wymaga glib2-devel: development tools
:: hyprland opcjonalnie wymaga meson: to build and install plugins using hyprpm
:: nodejs-lts-gallium opcjonalnie wymaga npm: nodejs package manager

Pakiet (9)   Obecna wersja  Zmiana

ninja        1.12.1-1        -0,38 MiB
node-gyp     10.2.0-1        -7,39 MiB
nodejs-nopt  7.2.0-2         -0,03 MiB
python-tqdm  4.66.5-1        -0,60 MiB
semver       7.6.3-1         -0,09 MiB
glib2-devel  2.82.1-2        -1,19 MiB
meson        1.5.2-1        -12,73 MiB
npm          10.9.0-1        -8,76 MiB
typescript   5.6.2-1        -21,39 MiB

Odzyskane miejsce na dysku:  52,55 MiB

:: Czy chcesz usunąć te pakiety? [T/n]
:: Przetwarzanie zmian pakietu...
(1/9) usuwanie typescript                                                                                                      [----------------------------------------------------------------------------] 100%
(2/9) usuwanie npm                                                                                                             [----------------------------------------------------------------------------] 100%
(3/9) usuwanie node-gyp                                                                                                        [----------------------------------------------------------------------------] 100%
(4/9) usuwanie semver                                                                                                          [----------------------------------------------------------------------------] 100%
(5/9) usuwanie nodejs-nopt                                                                                                     [----------------------------------------------------------------------------] 100%
(6/9) usuwanie glib2-devel                                                                                                     [----------------------------------------------------------------------------] 100%
(7/9) usuwanie meson                                                                                                           [----------------------------------------------------------------------------] 100%
(8/9) usuwanie python-tqdm                                                                                                     [----------------------------------------------------------------------------] 100%
(9/9) usuwanie ninja                                                                                                           [----------------------------------------------------------------------------] 100%
:: Uruchamianie po-transakcji...
(1/1) Arming ConditionNeedsUpdate...
-> Failed to install the following packages. Manual intervention is required:
aylurs-gtk-shell - exit status 4
ml4w-hyprland-git - exit status 8

**Comment by mylinuxforwork** [comment]
@mati1414 Please run yay to ensure that all packages are updated before starting the installation of the dotfiles. And try again.

**Comment by mati1414** [comment]
@mylinuxforwork thanks for quick response. My system is fully updated.
