### ISSUE TITLE
[BUG] i cant change my keyboard layout to german.

### ISSUE THREAD

**Issue by Gammastrahl** [mylinuxforwork/dotfiles#308]
**Describe the bug**
i cant change my keyboard layout to german. I set it on the setup and afterwards checked the keyboard.conf where its stated correctly but it still uses the US layout after reboot

**To Reproduce**
1. Go to '/home/admin/.config/hypr/conf/'
2. Click on 'keyboard.conf'
3. Set it to  
```
input {
    kb_layout = de
    kb_variant = de_nodeadkeys
    kb_model = pc105
    kb_options =
    numlock_by_default = true
    mouse_refocus = false
}
```
4. reboot the system

**Expected behavior**
It shouldve changed to the german keyboard

**Screenshots**
im sorry i dont know how to take a screenshot yet

**Distribution (please complete the following information):**
 - Arch Linux with kde plasma as second desktop enviroment 

**Additional context**
under plasma its working fine

**Comment by mylinuxforwork** [comment]
@Gammastrahl As a start, can you just try this?

```
input {
    kb_layout = de
    kb_variant = 
    kb_model =
    kb_options =
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus=false
    touchpad {
        natural_scroll = false
        scroll_factor = 1.0  # Touchpad scroll factor
    }
    sensitivity = 0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}
```

And then add additional settings one by one?

**Comment by Gammastrahl** [comment]
sadly it didnt changed much, i still only have

**Comment by Gammastrahl** [comment]
Still not working, y and z still changed.

sorry for closing, i dont use github this often

**Comment by mylinuxforwork** [comment]
> Still not working, y and z still changed or am i just stupid rn and the normal de layout is qwerty?
> 
> sorry for closing, i dont use github this often

No worries. 
Crazy that it's not working. 
Can you hover with your mouse over this icon on waybar? Which layout is shown? 
![image](https://github.com/user-attachments/assets/23642caf-d4ce-4df6-bca9-48fb3829ad66)

On my system I see "de".

**Comment by mylinuxforwork** [comment]
This is strange. What's your base system? Maybe your system settings overwrite the Hyprland settings?

**Comment by Gammastrahl** [comment]
Iam using arch linux on my Lenovo T450s with KDE Plasma. on plasma i already had the de layout same for the sddm. its only under hyprland

**Comment by Gammastrahl** [comment]
I completely wiped my drive and reinstalled Linux with KDE and than installed hyprland ontop, still facing the same issue. On KDE and SDDM i have the german layout but as soon as iam in hyprland i have the us one

**Comment by Gammastrahl** [comment]
It shows this but its not working 

```
> localectl status
System Locale: LANG=de_DE.UTF-8
    VC Keymap: de
   X11 Layout: de
    X11 Model: pc105

~
```

**Comment by Gammastrahl** [comment]
Im sorry @mylinuxforwork i didnt saw that you asked for the used path. 

Here is the Path i used `/home/admin/.config/hypr/conf/keyboard.conf`. This Path seems to open the same file as `/home/admin/dotfiles/.config/hypr/conf/keyboard.conf`

**Comment by Gammastrahl** [comment]
Any updates?

**Comment by mylinuxforwork** [comment]
> Any updates?

No. I cannot replicate this issue on any of my devices. I would suggest to open an issue or discussion on the Hyprland GitHub.

**Comment by mylinuxforwork** [comment]
@hofmannk69 @Gammastrahl Can you enter 

hyprctl devices

in a terminal?

**Comment by Gammastrahl** [comment]
As soon as i get home

**Comment by mylinuxforwork** [comment]
@hofmannk69 @Gammastrahl  And please try this command as well

hyprctl keyword input:kb_layout de

**Comment by Gammastrahl** [comment]
Okay now thats weird, i completely reinstalled hyprland right now. and now it seems to work without any specific model. when i set the model it isnt working anymore, also tried hyprland without your files and even there it isnt working.

Do you still want the output of hyperctl devices with the model settings?

**Comment by mylinuxforwork** [comment]
> Okay now thats weird, i completely reinstalled hyprland right now. and now it seems to work without any specific model. when i set the model it isnt working anymore, also tried hyprland without your files and even there it isnt working.
> 
> Do you still want the output of hyperctl devices with the model settings?

No. If it’s working then I am happy. Sometimes a combination of keyboard settings are invalid and reset it back to us.

**Comment by Gammastrahl** [comment]
Okay, de with de_nodeadkeys wont work but iam happy too. Just looked at your hyprland and as of now i think its pretty good.

I think this can be closed now, the problem is resolved
