### ISSUE TITLE
[BUG] Install with GIT (Rolling Release) - Dependency issue

### ISSUE THREAD

**Issue by Benjman** [mylinuxforwork/dotfiles#309]
**Describe the bug**
Attempting to install the ML4W Dotfiles project [according to the wiki](https://github.com/mylinuxforwork/dotfiles/wiki/Installation#installation-with-git-rolling-release) on a fresh installation of Arch Linux is broken because the dependency `gum` is not installed.

**To Reproduce**
1. [Follow the Arch Linux installation guide](https://wiki.archlinux.org/title/Installation_guide).
2. Follow the [Install with GIT (Rolling Release)](https://github.com/mylinuxforwork/dotfiles/wiki/Installation#installation-with-git-rolling-release) guide on this repo's wiki.
3. Step 4 unsuccessfully runs, producing the error:

```
/path/to/dotfiles/lib/install/packages/confirm_start.sh: line 16: gum: command not found
:: Installation canceled.
```

**Expected behavior**
This project should be expected to be built from a base installation of Arch Linux by either specify the need to install the `gum` dependency before running the setup script, or the installation script needs to account for this missing dependency and install it when it installs other packages.

**Distribution (please complete the following information):**
 - Arch Linux 6.11.2-arch1-1

**Additional context**
I tried to edit the wiki, but I think it's protected from public edits.

**Comment by Benjman** [comment]
Absolutely love this project, and I am hoping to contribute to it in a meaningful way soon. Thank you for all the work you've done for this project.

**Comment by mylinuxforwork** [comment]
@Benjman Thanks for testing. I will check the preconditions of the installer.

**Comment by mylinuxforwork** [comment]
@Benjman I have just pushed an update on the main branch. In case of an installation from the file system (not via AUR) the required packages for the installer will be checked.

**Comment by mylinuxforwork** [comment]
> Just tested and it works great. Thanks!

Great.
