### ISSUE TITLE
[BUG] Cannot install ml4w-hyprland-git via Arch AUR

### ISSUE THREAD

**Issue by manumoreno** [mylinuxforwork/dotfiles#313]
**Describe the bug**
First off, I would not call this a bug related to ML4W necessarily. However, I thought I'd bring this issue to your attention and that of your contributors/followers in the hope that they can provide some pointers.

I tried installing your ML4W dot files from the AUR repo and the install is failing. The error I get is shown in the attached screen capture. I did install the following packages to see if they would help resolve the issue:

```
pacman -S qt6-multimedia-gstreamer
pacman -S gstreamer-vaapi
pip install PyObject
```

**To Reproduce**
1. Run:  `yay -S ml4w-hyprland-git`

**Expected behavior**
Your ML4W dot files should install properly.

**Screenshots**
Included!

![screenshot_10102024_171811](https://github.com/user-attachments/assets/db008813-8028-4703-b6fd-f457d4e74b81)

**Distribution (please complete the following information):**
 - Arch Linux 6.11.2-arch1-1
 - Hyprland:
 
```
 hyprctl version
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2
```

**Additional context**
I've tried installing your dotfiles multiple times in recent months but the same error gets in the way. BTW, I've been using an older version and I'm really happy with it. I really appreciate all the work that you're doing.

**Comment by mylinuxforwork** [comment]
@manumoreno It is super important that all your packages are updated before running the installation of the dotfiles. Can you run yay and try again?

**Comment by mylinuxforwork** [comment]
I will close this issue by now. Please reopen if needed.
