### ISSUE TITLE
ZSH command not found: oh-my-posh

### ISSUE THREAD

**Issue by Dev-Sharbel** [mylinuxforwork/dotfiles#318]
Zsh warning/error:
`/home/user/.config/zshrc/20-customization:49: command not found: oh-my-posh`

**To Reproduce**
1. open a terminal

**Expected behavior**
No error.

**Screenshots**
![17286645181534810735822283420763](https://github.com/user-attachments/assets/b44dfb3d-ce28-4cb8-8456-acc96733ed1b)
![17286645854517004701119032280646](https://github.com/user-attachments/assets/4f46f906-d54d-49ed-ac2d-c1e1ec2a644b)

**Distribution (please complete the following information):**
 - Arch Linux
 - ML4W version 2.9.6.3

**Additional context**
Wanted to remove opacity from neovim, then realized it was from the terminal itself, went to zsh configs and followed a command to another file that was being evaluated with oh-my-posh to change the theme.

Wanted to modify that file to remove opacity (ohmyposh/zen.toml), never worked with this before so I got very confused. Then I noticed the error in the terminal and here I am.

**Comment by Dev-Sharbel** [comment]
I realized the opacity of the term is changed from alacritty's toml config, so I solved that.

But made this post for the error mentioned above xd.

**Comment by mylinuxforwork** [comment]
The installation of oh-my-posh failed. I am working on a fix.

**Comment by Dev-Sharbel** [comment]
Take your time and thank you for this awesome project!

**Comment by mylinuxforwork** [comment]
@Dev-Sharbel Should be fixed now. Had an issue with the post installation script. You can install it manually with yay -S oh-my-posh
