### ISSUE TITLE
[BUG] ml4w-hyprland-setup replaces wallpaper selection

### ISSUE THREAD

**Issue by dfd** [mylinuxforwork/dotfiles#319]
**Describe the bug**
I had been on an older version of ml4w-hyprland-git (a version shortly after the last dotfiles release) and upgraded to 2.9.6.3.
After reboot, my selected wallpaper, which I had added to the ml4w collection had been replaced by the ml4w default.  Not a big deal, but I assume this isn't expected.

**To Reproduce**
1. install an old version of ml4w-hyprland.
2. add a new image to the wallpaper collection and select it as the wallpaper
3. upgrade to ml4w-hyprland 2.9.6.3
4. Reboot
5. Check if your wallpaper selection has been overwritten.

**Expected behavior**
Expected the wallpaper selection to remain in tact after update.

**Distribution (please complete the following information):**
CachyOs

**Additional context**
None.

**Comment by Benjman** [comment]
I had this problem too. The setup script sets the wallpaper back to `default.jpg`. @mylinuxforwork if you think  #321 is acceptable, I could create another PR to persist wallpaper overrides through setup calls.

**Comment by mylinuxforwork** [comment]
@dfd I will check. @Benjman Thanks for the PR.

**Comment by mylinuxforwork** [comment]
@dfd I have just updated the ml4w-hyprland-git. This new version uses waypaper as wallpaper script. You can select a custom folder directly in the app. The old settings are not required anymore. You can also select swww if installed instead of hyprpaper.
Would be great if you could test it.

**Comment by dfd** [comment]
That didn't work for me.  After the installation and setup, I rebooted, then logged in from sddm, and saw a blank screen with no waybar or wallpaper.  SUPER + ENTER opened a terminal, so hyprland was running OK.

**Comment by mylinuxforwork** [comment]
> That didn't work for me. After the installation and setup, I rebooted, then logged in from sddm, and saw a blank screen with no waybar or wallpaper. SUPER + ENTER opened a terminal, so hyprland was running OK.

Can you change the wallpaper by opening waypaper. Then select a wallpaper or change the folder. Then reboot again.

**Comment by dfd** [comment]
oh you're right, that worked and restored waybar all at once!

**Comment by mylinuxforwork** [comment]
GreAt
