### ISSUE TITLE
[BUG] Update script error

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#323]
**Describe the bug**
![image](https://github.com/user-attachments/assets/c4ca5d65-aac2-474f-ad31-1c0a4278b4d7)

**Comment by mylinuxforwork** [comment]
@Benjman This happens when you try to update from an older version before 2.9.6 (I assume).
JUst update the packages with your AUR helper. Then just run ml4w-hyprland-setup

**Comment by Benjman** [comment]
@mylinuxforwork I didn't consider upgrades. Apologies if this is causing problems. This is now closed. Does this still need to be investigated?
