### ISSUE TITLE
[BUG] alias ls=eza gets overwritten by oh-my-zsh built in aliases

### ISSUE THREAD

**Issue by SamoutL** [mylinuxforwork/dotfiles#324]
**Describe the bug**
There are many aliases for ls (such as ls, la ,ll lt) which get loaded by oh-my-zsh.sh from .oh-my-zsh/lib/directories.zsh and somewhere else from oh my zsh config. These aliases overwrite custom ls aliases such as "alias ls='eza -a --icons" set in dotfiles/zshrc/10-aliases. 

I tried to load 10-aliases file after sourcing oh-my-zsh.sh by changing the file name to 40-aliases but this did not work.

I also tried commenting out ls aliases from .oh-my-zsh/lib/directories.zsh but alias ls='ls --color=tty' gets loaded from somewhere and overwrites the eza alias. I could not solve this yet.

**Distribution (please complete the following information):**
 - Arch Linux
 - Latest ml4w-hyprland 2.9.6.3

**Comment by SamoutL** [comment]
Solved this by adding:
```
unalias ls
alias ls='eza -a --icons'
```
to ~/.zshrc (will not persist over updates). For somereason adding unalias command to dotfiles/zshrc/custom/10-aliases does not work.

**Comment by mylinuxforwork** [comment]
Great. Thank you for testing. Will add this to the alias files.

**Comment by SamoutL** [comment]
I'll like to add to this. If you use 'eza --icons' autosuggestions gets broken. Use 'eza --icons=always $@' instead. [Reference](https://github.com/eza-community/eza/issues/964)

**Comment by Iss-in** [comment]
@mylinuxforwork please modify the eza alias per what samoutl said above, didnt want to create a new issue for something this minor and related. autosugestions are broken without =always tag

**Comment by mylinuxforwork** [comment]
> @mylinuxforwork please modify the eza alias per what samoutl said above, didnt want to create a new issue for something this minor and related. autosugestions are broken without =always tag

Will check. Thank you.
