### ISSUE TITLE
[BUG] Welcome apps update function broken

### ISSUE THREAD

**Issue by inffy** [mylinuxforwork/dotfiles#328]
**Describe the bug**
When I open the Welcome app and select the Install/Update dotfiles option I get a error in terminal:
![image](https://github.com/user-attachments/assets/59ae78ff-59f7-4bda-9f0c-92809c7d446e)

The command works straight from terminal. I have changed my terminal to Kitty

**To Reproduce**
1. Open ML4W Welcome App
2. Click the three dots
3. Select install/update

**Expected behavior**
Update script should run

**Screenshots**
![image](https://github.com/user-attachments/assets/59ae78ff-59f7-4bda-9f0c-92809c7d446e)

**Distribution (please complete the following information):**
 -  CachyOS (Arch Linux)
 

**Additional context**

**Comment by mylinuxforwork** [comment]
@inffy Thanks for reporting this issue. I am working on it already.

you can update by entering 

ml4w-hyprland-setup -m update

in a terminal.

**Comment by mylinuxforwork** [comment]
Fixed on main branch.
