### ISSUE TITLE
[BUG] Cannot get to desktop after post install

### ISSUE THREAD

**Issue by dhuxs** [mylinuxforwork/dotfiles#331]
**Describe the bug**
After running the post install script and rebooting, i no longer can login -i can enter my user and password, however after pressing login i get brought back to the login screen

**To Reproduce**
1. Reboot after post install
2. Login
3. Get brought back to the login screen

**Expected behavior**
I expected to be brought to the desktop

**Screenshots**
Dont have any

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Ive tried reinstalling once

**Comment by mylinuxforwork** [comment]
Can you try to uninstall xdg-desktop-portal-gtk?

yay -R xdg-desktop-portal-gtk

do you have a nvidia card?

**Comment by dhuxs** [comment]
Hello, yes i do have a nvidia card gtx1650

Upon opening terminal and it spits out these errors:

waybar: no process found
[LOG] Initializing xàph...
[CRITICAL] Couldn't connect to a wayland compositor
:: Thene: /ml4u-blur
ags: no process found
:: Use cached wallpaper blur-50x30-off-default.jpg
:: Generate new cached wallpaper square-default.jpg
(waybar:1197): Gtk-WARNING : 21:40:41.248: cannot open display: :2
(con.github.Aglur.ags:1199): Gtk-WARNING **: 21:40:41.303: cannot open
display: :2

Dne út 15. 10. 2024 21:19 uživatel Stephan Raabe ***@***.***>
napsal:

**Comment by Benjman** [comment]
Setting the wallpaper with the utility (`SUPER+Ctrl+W`) does set the wallpaper, and also shows waybar, but a fresh install is broken until this manual intervention is done.

**Comment by dhuxs** [comment]
Found out installing nvidia drivers fixed it

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing. @dhuxs Can you share the commands that you have ised to install NVidia drivers?

**Comment by dhuxs** [comment]
I used 'yay -S nvidia'

**Comment by mylinuxforwork** [comment]
Looks easy….
