### ISSUE TITLE
[BUG] Can't open the ml4w welcome, settings, and hyprland utilities

### ISSUE THREAD

**Issue by EnderNon** [mylinuxforwork/dotfiles#338]
**Describe the bug**
1: I can't open the settings app.

**To Reproduce**
1. Install dotfiles from stable (AUR "ml4w-hyprland")

**Expected behavior**
I wish to be able to find my zshrc backup pre-ml4w install, and I want to be able to start up the dotfiles settings app without error.

**Screenshots**

**Distribution (please complete the following information):**
Archlinux

**Additional context**

Here's an error I get when starting settings from terminal
```
❯ ml4w-settings

(process:19407): Adwaita-WARNING **: 23:23:27.964: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
:: Using Terminal alacritty

(ml4w-dotfiles-settings.py:19407): Gdk-WARNING **: 23:23:28.461: vkCreateWaylandSurfaceKHR(): A host memory allocation has failed. (VK_ERROR_OUT_OF_HOST_MEMORY) (-1)
/tmp/.mount_com.mliq0ZKj/AppRun: line 9: 19407 Segmentation fault      (core dumped) python ${EXEC}
❯

~
```

**Comment by EnderNon** [comment]
found the zsh backup but now I've got a nee issue: the uninstall utility does not actually restore everything to pre ml4w

**Comment by mylinuxforwork** [comment]
> found the zsh backup but now I've got a nee issue: the uninstall utility does not actually restore everything to pre ml4w

Currently working on the uninstaller.

**Comment by mylinuxforwork** [comment]
@EnderNon Uninstaller updated on main branch.
