### ISSUE TITLE
[BUG]  Steam games with EAC don't launch

### ISSUE THREAD

**Issue by greysonofusa** [mylinuxforwork/dotfiles#34]
**Describe the bug**
Starting steam games that use EAC crashes with an error

**To Reproduce**
1. Launch Steam
2. Start a game that uses EAC but works with linux like Chivalry 2 or Sea of Theives
3. Wait for pop up error to occur.
4. EAC not found

**Expected behavior**
The games start and run like normal on Linux.

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I have tested this with JaKooLit's hyprland installer and EAC games work on his installation.

**Comment by mylinuxforwork** [comment]
Hi. Thanks for testing. Unfortunately I am not a gamer and have no experiences with the requirements. 

Can you share some more insights or start a web search?

Maybe another user can help?

**Comment by jamesrahhh** [comment]
Are you using proton or gamescope?

**Comment by greysonofusa** [comment]
Should have been just proton from steam. I installed EAC via steam as well.
I think game scope is installed but I don't recall enabling it or adding
any start commands using it to steam.

**Comment by mylinuxforwork** [comment]
@greysonofusa @jamesrahhh Can we say that this is not a Dotfiles related issue and close therefore this issue?

**Comment by greysonofusa** [comment]
Ok I got the games to work by adding this launch code to the games with EAC
`unset SDL_VIDEODRIVER; %command%`

**Comment by mylinuxforwork** [comment]
Great. Thanks for texting and sharing the results.
