### ISSUE TITLE
[BUG]  Waypaper-git fails to start   Update to aur/waypaper instead of -git 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#341]
**Describe the bug**
Myself and another user reported that waypaper crashes on start 

**To Reproduce**
 Got to CLI, run waypaper.  Generates python crash 

![image](https://github.com/user-attachments/assets/4a54da58-5400-465d-8ea4-84960c3ce20b)

**Expected behavior**
The wallpaper selection app should appear

**Distribution (please complete the following information):**
 - Arch Linux
 - EndeavourOS
 - Manjaro
 - ... 

**Additional context**

I replaced waypaper-git with aur/waypaper    yay  -S aur/waypaper   This built from source and resolved the issue 

![image](https://github.com/user-attachments/assets/6f4b140e-080a-488d-84f6-766a0e784d55)

![image](https://github.com/user-attachments/assets/64ce89f5-21b3-4cfd-ab7a-371be7e25a61)

**Comment by kgncengiz** [comment]
I have exactly the same problem on 2 of my PCs.

**Comment by mylinuxforwork** [comment]
I am using already waypaper on the latest AUR pkgbuild https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ml4w-hyprland-git

This would solve the issue, right?

**Comment by dwilliam62** [comment]
Yes. The one from aur worked.

Don
