### ISSUE TITLE
[BUG]  Cannot move/rearrange panes on Obsidian app

### ISSUE THREAD

**Issue by Darkoreaper** [mylinuxforwork/dotfiles#347]
This is the exalt problem shown in this gif

https://forum.obsidian.md/uploads/default/original/3X/7/1/71dfd12bcfe05214c65ec811b4b7761c9197e558.gif

I have try [hyprdots](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/prasanthrangan/hyprdots&ved=2ahUKEwjZv6-miJ2JAxVv1TgGHbXGK9gQFnoECCkQAQ&usg=AOvVaw3fPIR7wpWVE0FBoXNUYfyc) 
 it is working there. So I think this is fixable. I love your Ml4w implement of hyprland 
 
I hope this will be fix ASAP

**Comment by mylinuxforwork** [comment]
@Darkoreaper How have you installed Obsidian on your system? With pacman, flatpak or as AppImage? 
And how do you start the app after the installation?

**Comment by mylinuxforwork** [comment]
@Darkoreaper This is not related to the ML4W Dotfiles. Please see this thread. It's an electron wayland issue. But it seams that there are fixes planned or workarounds possible.
https://forum.obsidian.md/t/cannot-move-rearrange-panes-when-running-under-wayland/42377/105

**Comment by Darkoreaper** [comment]
But when i tried obsidian on [hyprdots](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/prasanthrangan/hyprdots&ved=2ahUKEwjZv6-miJ2JAxVv1TgGHbXGK9gQFnoECCkQAQ&usg=AOvVaw3fPIR7wpWVE0FBoXNUYfyc) it work. i tried to understand it but couldnt figued it out myself

**Comment by mylinuxforwork** [comment]
> But when i tried obsidian on [hyprdots](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/prasanthrangan/hyprdots&ved=2ahUKEwjZv6-miJ2JAxVv1TgGHbXGK9gQFnoECCkQAQ&usg=AOvVaw3fPIR7wpWVE0FBoXNUYfyc) it work. i tried to understand it but couldnt figued it out myself

Pretty sure it's an electron issue. Maybe you can try to install another version of electron?

**Comment by Darkoreaper** [comment]
I think he has KDE implemented with hyprland 

![image](https://github.com/user-attachments/assets/7e11b1fe-1a91-4c48-9d4d-b15a632062b2)
https://github.com/flathub/md.obsidian.Obsidian?tab=readme-ov-file#broken-functionality-on-wayland

**Comment by Darkoreaper** [comment]
I have tried electron 20 - 32 versions
