### ISSUE TITLE
[Missing] hyprshade is missing from the 'Diagnosis' feature

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#35]
~/dotfiles/hypr/scripts/diagnosis.sh has not been updated with the new 2.9.3 feature hyprshade

**Comment by mylinuxforwork** [comment]
Thanks for testing. You‘re right. Will add this check to the diagnosis scripts.

**Comment by mylinuxforwork** [comment]
Solved and added to main branch. Just run the installer again.
