### ISSUE TITLE
[BUG] Other locations option not showing in nautils but it shows only from save to dialog 

### ISSUE THREAD

**Issue by joshwisehub** [mylinuxforwork/dotfiles#362]
**Describe the bug**
The Other location option is not showing on the nautils files manager

**To Reproduce**
1. Open the nautils files manager and observer the side bar

**Expected behavior**
The other location to appear so i can acess other disk drives or mounted storages 

**Screenshots**
![image](https://github.com/user-attachments/assets/664deb31-7e54-437c-98fe-745975560864)

**Distribution (please complete the following information):**
 - Arch Linux
 -Linux 6.11.4-arch2-1

**Comment by mylinuxforwork** [comment]
@joshwisehub I have the same effect on my system. Don't know the reason so far.

**Comment by mylinuxforwork** [comment]
![image](https://github.com/user-attachments/assets/ea9b5e2b-03fa-4b8a-93e7-c59232b1d085)

Seams to be a nautilus issue. Just tested on a fresh EndeavourOS installation. Same issue. Crazy. 
You can drag and drop folders to the sidebar to create a bookmark.

I will let the issue open. Maybe someone else can help.

**Comment by mylinuxforwork** [comment]
@joshwisehub We are not alone: https://unix.stackexchange.com/questions/784266/does-nautilus-require-a-package-to-show-user-directories-in-sidebar

**Comment by mylinuxforwork** [comment]
I will close it for know because it's not a dotfiles issue.
