### ISSUE TITLE
[BUG] Wireplumber causes audio/video playback to not start until audio configuration is reloaded

### ISSUE THREAD

**Issue by nfowlie** [mylinuxforwork/dotfiles#376]
**Describe the bug**
The latest update to ml4w makes wireplumber a dependency, replacing pipewire-media-session.  Wireplumber breaks audio/video playback until the audio profile is reloaded.

**To Reproduce**
1. Go to https://youtube.com
2. Click on any video to play
3. Video will buffer continuously until the audio profile is reloaded

**Expected behavior**
Audio and Video playback is expected to play without the need to reload audio profile.

**Screenshots**
Reloading the Profile seems to resolve temporarily solve the issue.
![image](https://github.com/user-attachments/assets/1b3aced7-88fa-434d-95ba-791312d645f5)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
This breaks a number of applications audio/video playback
- Youtube Videos
- VLC audio playback
- Jellyfin audio playback
- Audacity playback

**Comment by mylinuxforwork** [comment]
@nfowlie Thank you so much for testing. Was my fault. Just releases 2.9.6.4-2 without these dependencies. Should be available very soon as an update. Can you please try again?

**Comment by nfowlie** [comment]
@mylinuxforwork The update works.  However, I was able to get wireplumber working.  Pipewire now has two processes running, which seems to be the only difference compared to last night when the bug was occurring.  Helvum now shows a proper matching of media playback to output.

![wpctl status](https://github.com/user-attachments/assets/bc54f278-5aa8-41c2-a752-68218384c02a)

![image](https://github.com/user-attachments/assets/824bb5bf-16f0-4332-8ee4-1e72531830bb)

**Comment by mylinuxforwork** [comment]
Thanks for your feedback. Pipewire and audio settings will be usually installed with the distribution. That's why I will keep the dependencies out for now.
