### ISSUE TITLE
[BUG] Fresh installation on Arch. Rofi has trouble working.

### ISSUE THREAD

**Issue by FullStackPete** [mylinuxforwork/dotfiles#378]
**Describe the bug**
Rofi doesn't exactly work like it's supposed to - It shows failed to open theme  .config/ml4w/settings/rofi-font.rasi and .cache/wal/colors-rofi-pywal.rasi and 6 more errors

**To Reproduce**
1. Install ml4w with bash curl script
2. Rofi displays errors
**Expected behavior**
Rofi should display a see-through theme with the current wallpaper.

**Screenshots**
![image](https://github.com/user-attachments/assets/208e20f1-8edc-4363-a1ff-547ee052c8f3)

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@FullStackPete Do you mean the Hyprland Starter Package or the ML4W Dotfiles? When you mean the Dotfiles, I would suggest that you install the dotfiles with yay -S ml4w-hyprland and run ml4w-hyprland-setup after the installation.

**Comment by FullStackPete** [comment]
Hi! I meant the dotfiles. I run the configs, everything runs fine, whole system works ok, besides this rofi problem.

**Comment by mylinuxforwork** [comment]
Can you select a new wallpaper?
And what happens if you execute wal -h
Please try wal -i ~/wallpaper/default.jpg

**Comment by FullStackPete** [comment]
wal -h works as usual - shows wal options. Wal -i changed theme in my terminal, but rofi still displays those errors

**Comment by mylinuxforwork** [comment]
Can you check if the folder .config/ml4w/settings exists? The rofi-font.rasi is shipped with the ML4W Dotfiles and must be there.

**Comment by FullStackPete** [comment]
I don't have .config/ml4w/settings, but I do have ~/dotfiles/.settings and rofi-font.rasi is present here

**Comment by FullStackPete** [comment]
Hi, just wanted to post a quick update, that `ml4w-hyprland-setup` fixed the issue for me when I ran it again.
Issue can be closed for now, thanks for helping!

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing.
