### ISSUE TITLE
[BUG] Black screen after fresh install on cachyos

### ISSUE THREAD

**Issue by jamesmac10** [mylinuxforwork/dotfiles#379]
**Describe the bug**
No wallpaper, waybar, nothing. Keybindings do work, just a black screen though.

**To Reproduce**
-Install fresh install of cachyos with hyprland selected as window manager
-Install yay using pacman
-Install ml4w-hyprland using yay
-Run ml4w-hyprland-settings script
-Installed everything available, changed shell to alacritty and file manager to dolphin. Rebooted.

**Expected behavior**
To be greeted with the desktop after loggin in on sddm.

**Distribution (please complete the following information):**
 - Arch Linux
 I was previously having issues getting aliases to work after installing ml4w, but this time there are no alias issues. I was able to get everything to display  by changing the wallpaper to any of the wallpapers in the repo, at which time the wallpaper and waybar are now displaying.

**Comment by mylinuxforwork** [comment]
I will try to replicate. Keep you posted.

**Comment by mylinuxforwork** [comment]
@jamesmac10 Just installed the latest 2.9.6.4 of the ML4W Dotfiles in a KVM/Qemu virtual machine on top of CachyOS Hyprland without an issue.

![image](https://github.com/user-attachments/assets/fc7395d5-0573-4f4f-aa5d-4676423b7cb8)

**Comment by jamesmac10** [comment]
Oh thats great! Must have been an issue with something unrelated then. Perhaps user error haha. Thanks for checking that out!

**Comment by ShiroDN** [comment]
I am having the same problem on both a new install on my laptop and in KVM.

I tried debugging it, and it seems there is a cascading issue starting with Waypaper. Waypaper fails to set the wallpaper in `~/.config/hypr/scripts/wallpaper-restore.sh` due to the cache file at `~/.config/ml4w/cache/current_wallpaper`, which contains a hardcoded path with the username **raabe** instead of my username **tomas**. The issue is that the cache file is not regenerated on the first start.

If I delete the cache file, everything loads fine.

```
cat $HOME/.config/ml4w/cache/current_wallpaper
/home/raabe/wallpaper/default.jpg

echo $HOME
/home/tomas

```

**Comment by mylinuxforwork** [comment]
@ShiroDN @jamesmac10 Just pushed an update of the wallpaper-restore to the dev branch. https://github.com/mylinuxforwork/dotfiles/blob/dev/share/dotfiles/.config/hypr/scripts/wallpaper-restore.sh

Can you try to replace the code on your system with the new one? And restore the wrong content of $HOME/.config/ml4w/cache/current_wallpaper with /home/raabe/wallpaper/default.jpg

The execute the script ./wallpaper-restore.sh 

Thanks for your help. Will test as well on my system.

**Comment by SSYH** [comment]
I am seeing the same error as @jamesmac10 described after installing dotfiles today.
Blank screen after reboot (mouse does show tho).
I was eventually able to get the waybar to show using super-ctrl-T (change theme), after which waybar appeared and I was happier. However this didn't persist after logout/login; I have to super-ctrl-T again after each login.

**Comment by SSYH** [comment]
I tried deleting the cache file per @ShiroDN , but that didn't resolve anything for me.
FTR

**Comment by SSYH** [comment]
SUPER-SHIFT-W seems to **not** work (tested on 2 separate machines)

**Comment by ShiroDN** [comment]
@mylinuxforwork I can confirm that the fix resolved the issue; everything loads fine. I restored a vm snapshot and tested it on a fresh install.
