### ISSUE TITLE
[BUG] Cleanup your system removes used packages

### ISSUE THREAD

**Issue by z3r0d0n3** [mylinuxforwork/dotfiles#380]
**Describe the bug**
After the latest update when i try to cleanup system it will delete more than needed, which will eventually make the UI later unusable

**To Reproduce**
1. Go to 'Open Sidebar'
2. Click on 'Welcome App'
3. Click on Settings -> System -> Cleanup your system
4. It will remove packages that are actually being used

**Expected behavior**
Expected to remove only unused packages, not those which are in use

**Screenshots**
![image](https://github.com/user-attachments/assets/cbece627-ac45-4c87-a6b4-c804165589df)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
After cleaning up, the terminal wont start anymore, the application launcher wont start at well, the shutdown menu becomes unusable as well, thankfully i had timeshift and reversed it, but there is definitely something wrong with the latest cleanup

**Comment by mylinuxforwork** [comment]
Thanks for testing. I will check and provide an update as soon as possible.

**Comment by mylinuxforwork** [comment]
@z3r0d0n3 Thanks again for testing. I have removed the critical function from the cleanup script. Already pushed to main branch.
