### ISSUE TITLE
[BUG] missing dependencies zsh config

### ISSUE THREAD

**Issue by PrymalInstynct** [mylinuxforwork/dotfiles#382]
**Describe the bug**
When switching from bash to zsh in an existing ML4W configuration I found that a number of dependencies were missing.

**To Reproduce**
1. change shell
```
chsh -s $(which zsh)
```
2. Notice errors at the top of the terminal for missing dependencies
```
zsh-autosuggestions
zsh-syntax-highlighting
fast-syntax-highlighting
oh-my-posh
```

**Expected behavior**
Terminal starts with ZSH shell and no errors

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I was able to address the issue by installing the missing dependencies and symlinking some of them to the correct oh-my-zsh location.

```
yay -S zsh-syntax-highlighting zsh-fast-syntax-highlighting zsh-autosuggestions oh-my-posh
sudo ln -s /usr/share/zsh/plugins/zsh-autosuggestions~/.oh-my-zsh/custom/plugins/
sudo ln -s /usr/share/zsh/plugins/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/
sudo ln -s /usr/share/zsh/plugins/fast-syntax-highlighting ~/.oh-my-zsh/custom/plugins/
```

**Comment by mylinuxforwork** [comment]
You can also use the new Installation Options script and change the shell there. This will install all required plugins.

![image](https://github.com/user-attachments/assets/ec1dad3e-2da1-4078-8a7d-3a0c594693a2)

**Comment by PrymalInstynct** [comment]
makes sense, I must have missed that. thanks.
