### ISSUE TITLE
[BUG] How to remove chrome context menu "blur" in chromium ?

### ISSUE THREAD

**Issue by rn00gr** [mylinuxforwork/dotfiles#385]
In right click menu there a blur effect in background in chromium and also other browsers like Microsoft edge. 
Although for some reason context menu in Firefox is not disturbed .

I'm using Arch linux but i thing it's same in all the Linux distros.
![screenshot_30102024_182353](https://github.com/user-attachments/assets/e2f18a0b-ad25-462a-ba09-620f38d765c7)
![screenshot_30102024_184439](https://github.com/user-attachments/assets/797bccc2-020c-41cc-9044-4181ad4c37f4)

please help me to fix this issue.

**Comment by mylinuxforwork** [comment]
@rn00gr You can start chrome or chromium with flags: 
chromium --ozone-platform-hint=auto --ozone-platform=wayland

Please check this thread.
https://www.reddit.com/r/hyprland/comments/1ccwkml/how_to_remove_chrome_context_menu_blur_in_hyprland/
