### ISSUE TITLE
[BUG] cleanup script

### ISSUE THREAD

**Issue by hamody19** [mylinuxforwork/dotfiles#388]
**cleanup script wipe out the configurations**
why when i run the cleanup script it's wipe out the entire `ml4w` setup and the system configurations

**Comment by mylinuxforwork** [comment]
It os already fixed on main branch ml4w-hyprland-git.
https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/ml4w/scripts/cleanup.sh
