### ISSUE TITLE
[BUG] Copying certain texts and pictures changes keyboard layout

### ISSUE THREAD

**Issue by cap0bvious** [mylinuxforwork/dotfiles#389]
**Describe the bug**
I have two keyboard layouts: us and ru. When ru layout is active, copying a URL or some pictures that are probably stored as a URL causes keyboard to start typing in us layout until I press a key that isn't a letter or a number. Indicator on Waybar still shows ru, and changing layout with a shortcut results in us layout, forcing to change the layout back again. Described behaviour can be useful in some rare occurances, but mostly it's annoying

**To Reproduce**
1. Change layout to ru
2. Copy any URL adress
3. Layout is broken temporarily

**Expected behavior**
Expected behaviour is layout staying the same until I explicitely change it

**Distribution (please complete the following information):**
 - Arch Linux
 - Happened before on Manjaro too

**Additional context**
I tried googling the issue for several weeks, but couldn't find what can be causing described behaviour. It never happened in my DEs that I have used before. When it happened first in Manjaro, dotfiles were installed on top of KDE which is not ideal I guess, but even a proper installation of Arch still has this issue. I don't know if it's a bug or a weird feature, but I'd like to fix it

**Comment by mylinuxforwork** [comment]
Difficult to test exactly your scenario. Can you share your keyboard.conf?

**Comment by cap0bvious** [comment]
It's mostly default, I just added second layout and a toggle between both
`# ----------------------------------------------------- 
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = us, ru
    kb_variant = 
    kb_model =
    kb_options = grp:win_space_toggle
    numlock_by_default = true
    mouse_refocus = false
    
    # For United States
    # kb_layout = us
    # kb_variant = intl
    # kb_model = pc105
    # kb_options =

    follow_mouse = 1
    touchpad {
        # for desktop
        natural_scroll = false
        
        # for laptop
        # natural_scroll = yes
        # middle_button_emulation = true
        # clickfinger_behavior = false     
        scroll_factor = 1.0  # Touchpad scroll factor
    }
    sensitivity = 0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}

gestures {
    workspace_swipe = true
}`

**Comment by mylinuxforwork** [comment]
@cap0bvious How does your toggle looks like? 
Just tested it without a toggle on my system. No issues. So, it must be your toggle.

**Comment by cap0bvious** [comment]
Line `kb_options = grp:win_space_toggle` is responsible for the toggle. That's how Hyprland wiki explains implementing it. Now I've tried using a different bind and using a script to change layout instead of this default method, but the result didn't change

**Comment by cap0bvious** [comment]
I think I've found the culprit. Pretty obvious, but I didn't think about that. I use a Logitech gaming mouse configured through Piper. Copying and pasting are binded to its buttons, and only using these causes the issue. Keyboard hotkeys seem to be fine. The thing is other DEs I used didn't have this issue, so I thought it was an problem with Hyprland. I'll try to investigate this further
