### ISSUE TITLE
Start testing with Hyprland 0.42 and Aquamarin

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#39]
With Hyprland 0.42 it's not a wlroot compositor anymore. 

https://hyprland.org/news/independentHyprland/

Install hyprland-git and start testing with the lastest version.

**Comment by dwilliam62** [comment]
FYI:  I have been testing this with NIXOS and so far it's been very good.

**Comment by mylinuxforwork** [comment]
> FYI: I have been testing this with NIXOS and so far it's been very good.

Great. This is good news.

**Comment by dwilliam62** [comment]
So 0.42 was released today BTW 
https://hyprland.org/news/update42/

**Comment by mylinuxforwork** [comment]
@dwilliam62 Will install it now and use it for the day.

**Comment by mylinuxforwork** [comment]
@dwilliam62 No issues found so far.

**Comment by mylinuxforwork** [comment]
Everything is working fine.
