### ISSUE TITLE
[BUG] Hyprland crash on starting

### ISSUE THREAD

**Issue by Xeinel** [mylinuxforwork/dotfiles#390]
**Describe the bug**
I just installed ml4w yesterday. When I launch it, it crashes and I have to enter a gnome session to execute `ml4w-hyprland-setup` before launching again the Hyprland session. To launch the hyprland session, I have to logout and change the session. Launching it by using `Hyprland` command in my terminal doesn't work and en error is thrown. My OS is an ArchLinux one.

**To Reproduce**
1. Go to a terminal
2. Enter `Hyprland` in my terminal
3. See error

OR

1. Reboot or logout
2. Try to launch the Hyprland session
3. See that it crashes and my computer come back to login screen.

**Expected behavior**
I would like to know if you have any solution to fix this problem on ArchLinux OS.
[hyprlandCrashReport5145.txt](https://github.com/user-attachments/files/17587306/hyprlandCrashReport5145.txt)

**Distribution (please complete the following information):**
 - Arch Linux

Thanks in advance

**Comment by mylinuxforwork** [comment]
The wayland session couldn't be initialized with Hyprland and Aquamarin. Do you have an NVIDIA card?

**Comment by mylinuxforwork** [comment]
Will close this issue for now. Please re-open if the issue still persists.
