### ISSUE TITLE
[BUG] After clean install waybar is not auto started, waypaper is broken

### ISSUE THREAD

**Issue by DusanNikcevic** [mylinuxforwork/dotfiles#394]
**Describe the bug**
When installing dotfiles via AUR I was faced with multiple issues:

- Waypaper was not working
- Waybar does not start on boot.

I have solved one of these issues

- Had to install screeninfo with yay -S python-screeninfo   to get wallpapers to work

**To Reproduce**
Install dotfiles via AUR

**Expected behavior**
I would expect to have waybar start on boot and to have wallpaper loaded

**Distribution (please complete the following information):**
 - Garuda Linux (KDE Lite)

**Additional context**

**Comment by mylinuxforwork** [comment]
@DusanNikcevic Just pushed an update to the main branch. You can test it with yay -S ml4w-hyprland-git and ml4w-hyprland-setup

**Comment by DusanNikcevic** [comment]
@mylinuxforwork thanks for quick update. I have discovered though that all of my issues were tied into waypaper not starting due to missing dependency. Now everything works like charm, thanks for the awesome product!

**Comment by alucryd** [comment]
I can reproduce the broken waypaper but haven't found a way to fix it. It works fine on my desktop, but it just hangs on my laptop. Calling waypaper in a terminal never returns, and I guess this prevents waybar from loading. Any idea waht could be preventing waypaper from working properly?
