### ISSUE TITLE
[BUG] No focus fallback don't work

### ISSUE THREAD

**Issue by Veicm** [mylinuxforwork/dotfiles#395]
**Describe the bug**
It is not possible to turn off the focus fallback any more. Property since the last aur update of ml4w-hyprland-git which I istalled a few minutes ago.

**To Reproduce**
1. open the hyprland settings app
2. Click on "No Focus Fallback"
3. See error (Nothing will hapen)

**Expected behavior**
It should turn off the Focus Fallback

**Screenshots**
N/A

**Distribution (please complete the following information):**
 - EndeavourOS

**Additional context**
My Version: ml4w-hyprland-git    2.9.6.4.r21.gd80771f-1

**Comment by mylinuxforwork** [comment]
@Veicm Thanks again for bringing this up. It's implemented in the latest main branch.
