### ISSUE TITLE
[FEATURE] some kind of backup with snapshot funtionality

### ISSUE THREAD

**Issue by Stewart86** [mylinuxforwork/dotfiles#405]
**Is your feature request related to a problem? Please describe.**
One of the most common downside of using Arch Linux is the rolling releases. It can be catastrophic for user of Arch not have a some sort of backup to their system before an update.

Although it is pretty straightforward to setup a snapshot system like [Timeshift](https://wiki.archlinux.org/title/Timeshift), but an all rounded complete solution like using [snap-pac](https://github.com/wesbarnett/snap-pac) to auto create a snapshot on updates then include the snapshot in grub boot option with [grub-btrfs](https://github.com/Antynea/grub-btrfs), can be tedious to setup.

**Describe the solution you'd like**
Some kind of set and forget backup system that saves life.

**Describe alternatives you've considered**
Use NixOS instead of Arch 😉 

However, also noting that user might not have choosen to use btrfs and grub bootloader on their `archinstall` the proposed solution will not work.

**Comment by mylinuxforwork** [comment]
@Stewart86 Thanks for bringing this issue up. Making a backup is a super individual topic. And from my perspective closer to the Arch system and not related to the dotfiles. 

The dotfiles updater detects if timeshift is installed and offer to make a backup. This comes out of the box. 

![image](https://github.com/user-attachments/assets/78c313ab-947a-4c35-9f62-b57276d7ca0e)

What do you think?

**Comment by Stewart86** [comment]
Yes this makes sense.. It is more specifically for the distro-level concern than a compositor level one. However like many things, etc shell, terminal, browser? They are not required for the compositor to work properly? I don't know? In my mind I was just thinking that I only need `archinstall` and `ml4w-hyprland-setup` and I have fully rebuilt a system. In fact it is almost complete solution now, it's just missing a few things, one of which happened to be a good snapshot solution. If that was your initial intention to create this dotfiles, I think you should aim to create an installer that allow all hands off. Hack, you could even wrap `archinstall` and user would just need to call one line command and get everything up and running.

Yes, those utilities that I've mentioned might be more of necessities,but a robust snapshot backup is also a necessity for Arch based distro. Could be a rather gray area? Of cause if you say that you are trying to make this install script be compatible with other distributions then this will not be that important (still important imo), but you could also conditionally enable this feature based on distro?

ps: alternatively maybe the `linutil`by Chris Titus Tech might be a better solution.

**Comment by Stewart86** [comment]
Oh actually just discovered that this issue is not relevant at all as it is already built. Found a file `installtimeshift.sh` in the repo that does exactly this. So I'm closing this issue.
