### ISSUE TITLE
[BUG] ML4W breaks latest HyprLand 0.45.0 (git) build 

### ISSUE THREAD

**Issue by armenr** [mylinuxforwork/dotfiles#411]
**Describe the bug**
Looks like certain settings/configs are no longer valid.

**To Reproduce**
I had to comment these settings out in order to get things working again...
```
    # drop_shadow = true
    # shadow_range = 30
    # shadow_render_power = 3
    # col.shadow = 0x66000000
```

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@armenr Thanks for testing. Let me check.

**Comment by mylinuxforwork** [comment]
@armenr Can you send a screenshot wit the error message in hyprland-git?

**Comment by Kenotic** [comment]
Does this help? Like @armenr I had to comment out those 4 lines and it worked just fine.

![githubhypr1](https://github.com/user-attachments/assets/c164560a-2b20-43d2-bf95-7d4a53d0a9ad)

**Comment by mylinuxforwork** [comment]
Great. That’s helpful.

**Comment by mylinuxforwork** [comment]
https://github.com/hyprwm/Hyprland/releases/tag/v0.45.0
https://wiki.hyprland.org/Configuring/Variables/#shadow

**Comment by mylinuxforwork** [comment]
@armenr Just tested with 0.45.0 and pushed an update to the main release. I have replace the former shadow definition with the new one in all decoration variation:

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
    }

In addition, I have updated the Hyprland Settings App with the new shadow keywords.
