### ISSUE TITLE
[BUG] Using the hyprland setup  after the orginal changes keyboard layout

### ISSUE THREAD

**Issue by AresOverload** [mylinuxforwork/dotfiles#415]
**Describe the bug**
Using hyprland setup to reinstall dotfiles and key

**To Reproduce**
1. use hyprland setup after the first setup (reinstall dot files)
2. reboot

 
 
**Expected behavior**
i wanted to install the dotfiles  is by running the setup and it worked then my layout was German
also i couldent change it back to US

What i did to fix it was  reinstalling arch itself

 - Arch Linux

**Additional Notes**
Archinstall
Nvidia Drivers

**Comment by AresOverload** [comment]
No, i reinstalled arch lol

**Comment by AresOverload** [comment]
But if its about the issue i did restore my keyboard layout

**Comment by mylinuxforwork** [comment]
@AresOverload I just tested the restore of the keyboard.conf again without issues. It is important that the keyboard.conf is selected in the restore list. Please see the screenshot:

![image](https://github.com/user-attachments/assets/716efdca-90da-43f7-b8eb-a2a17d777381)

If it's not selected, you will overwrite it with the default file. But I will change the default keyword layout to us to be more compatible with most of the users.
