### ISSUE TITLE
[BUG] Kitty kitten theme somehow always overwrittten ?

### ISSUE THREAD

**Issue by seratg** [mylinuxforwork/dotfiles#416]
**Describe the bug**
Probably not a bug, but I cannot figure out how my kitty theme is being overwritten.

I did comment out the line `include $HOME/.cache/wal/colors-kitty.conf` and set a custom theme with kitten, but it is always launched with colors conf.

**To Reproduce**
Launching a new terminal always uses colors-kitty.conf ?

Hitting the update button in the waybar, launcher kitty with the theme i set in kitten.

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@seratg Everytime you change the wallpaper, the file $HOME/.cache/wal/colors-kitty.conf will be written by pywal.
I would suggest that you additionally add your theme.

**Comment by seratg** [comment]
I don't think that this is the issue, as it happen even when I don't include `colors-kitty.conf` in kitty.conf.

I just tried to update `colors-kitty.conf` with a custom theme, it still wouldn't take the new theme.

**Comment by mylinuxforwork** [comment]
> I don't think that this is the issue, as it happen even when I don't include `colors-kitty.conf` in kitty.conf.
> 
> I just tried to update `colors-kitty.conf` with a custom theme, it still wouldn't take the new theme.
> 
> Besides, as I mentioned, the update kitty terminal does start with the correct theming. However, as soon as I create another tab in that terminal window, the new tab doesnt have the correct theming.

Can you share a screenshot?

**Comment by seratg** [comment]
Ok, the call to `cat ~/.cache/wal/sequences` in zshrc autostart file was causing the issue to overwrite the kitty theme.
