### ISSUE TITLE
[BUG] Error message in decorations.conf (on Hyprland 0.44.1)

### ISSUE THREAD

**Issue by Veicm** [mylinuxforwork/dotfiles#424]
**Describe the bug**
After updating to the newest aur version of "ml4w-hyprland-git" a error massage will appear at the top of the screen.

**To Reproduce**
1. Upadate to ml4w-hyprland-git   2.9.6.5.r14.g2f5c80f-1
2. execute "ml4w-hyprland-setup"
3. See error

**Expected behavior**
Nothing should happen 

**Screenshots**
![screenshot_10112024_155506](https://github.com/user-attachments/assets/da271d03-2274-43bf-8cbc-d14d536439f6)

**Distribution (please complete the following information):**
 - EndeavourOS

**Additional context**
The white line on the picture not on the real error massage but there is my real name.
I will downgrade to the latest stable release for now but hope the bug will be fixed.

**Comment by mylinuxforwork** [comment]
@Veicm Please check: https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#issues-after-upgrading-to-hyprland-0450

**Comment by Veicm** [comment]
Thank you
