### ISSUE TITLE
[BUG] Preparing Hyprland 0.45.0: update decoration:shadow error 

### ISSUE THREAD

**Issue by duu261** [mylinuxforwork/dotfiles#425]
I think the update of hyprland cause this

notify decoratoin:shadow not exist
at conf/hypr/decorations

And also the ML4W HYPRLAND APPS not working / cannot start
fresh install no modify  on pc and update on laptop also get this

**Screenshots**
![image](https://github.com/user-attachments/assets/85ff17ac-c3ec-406c-8f01-c5f8513a8bd7)

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@duu261 Please check https://github.com/mylinuxforwork/dotfiles/wiki/Troubleshooting#issues-after-upgrading-to-hyprland-0450

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/issues/424

**Comment by duu261** [comment]
Ive updated the dotfiles already but the error still there i just can hide it with "hyprctl seterror disable" and also the ML4W Hyprland Setting app can not start the GUI

**Comment by duu261** [comment]
And is seem the shadow didnt even works

**Comment by mylinuxforwork** [comment]
> Ive updated the dotfiles already but the error still there i just can hide it with "hyprctl seterror disable" and also the ML4W Hyprland Setting app can not start the GUI

No. I mean the upcoming Hyprland update to 0.45.0 The ml4w-hyprland-git is already prepared for the update but will show this error on 0.44.1.
