### ISSUE TITLE
[BUG] Black screen after install ML4W

### ISSUE THREAD

**Issue by CatNghia369** [mylinuxforwork/dotfiles#426]
**Describe the bug**
Black screen after install ML4W

**Expected behavior**
hyprland shows up with ML4W

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by CatNghia369** [comment]
> @CatNghia369 I need more details. Do you have an NVIDIA card? What happens if you restart your system and try again? Was it an update or fresh installation? Can you open a terminal with SUPER + Return?

I need more details. Do you have an NVIDIA card: Nope, I don't use NVIDIA, I use Intel
What happens if you restart your system and try again: The same
Was it an update or fresh installation: Fresh installation
I can use shortcuts (only)

**Comment by kidfromjupiter** [comment]
I recently updated to 2.9.6.6 and can confirm. Waybar doesn't start unless I toggle the waybar setting. And background is not set

**Comment by mylinuxforwork** [comment]
> I recently updated to 2.9.6.6 and can confirm. Waybar doesn't start unless I toggle the waybar setting. And background is not set

What was your earlier ML4W version?

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing and your feedback.
