### ISSUE TITLE
[BUG] Default applications defined in ML4W Settings not install by default

### ISSUE THREAD

**Issue by Stewart86** [mylinuxforwork/dotfiles#427]
**Describe the bug**
Seeing that default app comes with it's shortcuts, intuitively I tried launching them with the shortcut keys. Which I then realised that they were not installed. In particularly, default calculator, emoji picker and editor were not installed by default.
 
**To Reproduce**
1. Go to Open Sidebar
2. Click on Settings App
3. Go to System
4. See Default Applications

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
Let me check.
