### ISSUE TITLE
[BUG] Hyprland settings app not working

### ISSUE THREAD

**Issue by smuyo** [mylinuxforwork/dotfiles#428]
I installed ML4W in a fresh Arch Linux installation.
The Hyprland settings app does not open. No matter where I try to open it from, it does not work. 
If I try to open it from the terminal (using ml4w-hyprland) it prints a warning about an adwaita theme not being supported and then does nothing. 
The welcome and dotfiles settings apps work as expected.
Hyprland version 0.45.
ML4W version 2.9.6.5

**Comment by mylinuxforwork** [comment]
@Kenotic @smuyo Please update the ML4W Dotfiles to 2.9.6.6 (released today) and run ml4w-hyprland-setup to install the latest version of the Hyprland Settings app. 

The warning is not critical.

**Comment by FrankelJb** [comment]
I'm having the same issue. Settings stopped working with new update. I tried to install the AppImage from the other settings repo but that failed. I've rerun the settings and I can only open Hyprland App and not Settings App.

**Comment by smuyo** [comment]
> @Kenotic @smuyo Please update the ML4W Dotfiles to 2.9.6.6 (released today) and run ml4w-hyprland-setup to install the latest version of the Hyprland Settings app.
> 
> The warning is not critical.
Thanks, this solved the issue!

**Comment by mylinuxforwork** [comment]
> > @Kenotic @smuyo Please update the ML4W Dotfiles to 2.9.6.6 (released today) and run ml4w-hyprland-setup to install the latest version of the Hyprland Settings app.
> > The warning is not critical.
> 
> Thanks, this solved the issue!

Great.
