### ISSUE TITLE
[FEATURE] Option to install Flatpak during installation

### ISSUE THREAD

**Issue by kerbyyy** [mylinuxforwork/dotfiles#43]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but it would be nice to have an option to whether or not install Flatpak as well.

**Describe the solution you'd like**
During installation, the user can choose if they want to install Flatpak support or not.

**Comment by mylinuxforwork** [comment]
Thanks for your request. Which flatpack apps are you using and are importing for you? On Arch you can install nearly all apps as aur with yay or paru.

**Comment by kerbyyy** [comment]
Yes, it's true that most apps are already available in the AUR, but sometimes I use an app from the AUR just to discover they're buggy or even worse, outdated. Some of the common apps I use with Flatpak are Viber, and Modrinth (a Minecraft Launcher). I think having it as an option would be a nice little addition for us people who use some Flatpak from time to time.

**Comment by mylinuxforwork** [comment]
OK. Will add it to the installer.

**Comment by mylinuxforwork** [comment]
@kerbyyy Merged into main release. Please run the installer again.

**Comment by bknightInfo** [comment]
Hi @mylinuxforwork 

As discussed on discord this is how I implemented my Flatpak solution

functions
_isInstalledFlatpak() {
    package="$1";
    check="$(flatpak list --columns="application" | grep "${package} ")";
    if [ -n "${check}" ] ; then
        echo 0; #'0' means 'true' in Bash
        return; #true
    fi;
    echo 1; #'1' means 'false' in Bash
    return; #false
}


_installPackagesFlatpak() {
     toInstall=();
    for pkg; do
        sudo flatpak install -y flathub "${pkg[@]}";
        if [[ $(_isInstalledFlatpak "${pkg}") == 0 ]]; then
            echo ":: ${pkg} is installed.";
            toInstall+=("${pkg}");
            continue;
        fi;
    done;

    sudo flatpak install -y flathub "${toInstall[@]}";
}

echo -e "$CNT - Installing flatpaks, this may take a while..."
_installPackagesFlatpak "${packagesFlatpak[@]}";

not sure how this compares to your script

**Comment by mylinuxforwork** [comment]
Looks great. Let me check...

**Comment by mylinuxforwork** [comment]
@bknightInfo I just added the (optional) installation of flatpak to the installer. 

`sudo pacman -S flatpak`

Your functions are flatpak installation utilities. I will add both to the library.sh for the installer and the scripts.sh for the hook and post installation scripts.

**Comment by mylinuxforwork** [comment]
@bknightInfo Added to https://github.com/mylinuxforwork/dotfiles/blob/main/.install/includes/library.sh and https://github.com/mylinuxforwork/dotfiles/blob/main/.install/includes/scripts.sh
