### ISSUE TITLE
[BUG] Touchpad doesn't work correctly after ml4f-hyprland-setup and updating Hyprland

### ISSUE THREAD

**Issue by Svarshick** [mylinuxforwork/dotfiles#430]
Before updating and reinstalling configs I could change workspace with three fingers swipe. Now I can't. I used config after default installation with ml4f script

 - Arch Linux

**Comment by mylinuxforwork** [comment]
Have you restored your settings during the update process.

**Comment by Aissi17** [comment]
in your  ``conf/layouts/default.conf``  set  ``workspace_swipe`` to  true

**Comment by MalaskaDeividas** [comment]
this didnt help^

**Comment by yyyxam** [comment]
> this didnt help^

For me it did actually!

**Comment by Svarshick** [comment]
> in your `conf/layouts/default.conf` set `workspace_swipe` to true

It helped. Thanks. I am sorry for late answer

>Have you restored your settings during the update process.

No, I forgot that I didn't before updating. Then I slightly changed config. Your preset is excellent. I only added screen record. Why wouldn't you add it?
