### ISSUE TITLE
[BUG]  Sidebar won't open

### ISSUE THREAD

**Issue by RafTeog** [mylinuxforwork/dotfiles#44]
**Describe the bug**
Whenever I left click on the sidebar button (next to the date, the one that says "Open Sidebar" when mouse hoovered), it does not open. I tried to reinstall the dotfiles (forcing option) and, after the reboot, it opened. After a second reboot, it stopped opening again. Right now it is not opening when left clicked. 

OBS: Right click works fine, opens the welcome app.

**To Reproduce**
1. Go to waybar
2. Click on side bar button
3. See error: left click does not work

**Expected behavior**
The menu with all apps

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
AMD hardware, no other DEs or possible conflicting packages installed, only normal programs.

Thank you for the amazing work!
Rafael

**Comment by Pryka** [comment]
Do you have eww package installed?

This one - https://aur.archlinux.org/packages/eww

**Comment by RafTeog** [comment]
I do
<aur/eww 0.6.0-1 (+26 1.87) (Installed)
    Standalone widget system made in Rust>
is there a connection? Should I remove it?

**Comment by mylinuxforwork** [comment]
What is the stand alone widget system?

**Comment by mylinuxforwork** [comment]
Which version will be shown when you enter

`eww -V`

**Comment by RafTeog** [comment]
> What is the stand alone widget system?

Hey sir, I just coppy-pasted the output of pacman -Ss. That's what it returned. I have only the ones used by this config. The ssd drive where I have this arch instalation has nothing else going on.

**Comment by RafTeog** [comment]
eww 0.5.0 d87c2fdbfdc012e76d229e4e9ea3325bc0f23e89<<< done

**Comment by RafTeog** [comment]
after yet another reboot, it is now working. So strange.

**Comment by mylinuxforwork** [comment]
But great that is working now. Will close this issue for now.
