### ISSUE TITLE
[BUG] Running ml4w-hyprland-setup after update does not respect previous configs

### ISSUE THREAD

**Issue by mgeldi** [mylinuxforwork/dotfiles#440]
**Describe the bug**
When I run the setup after an update, I always end up with my own changes not being copied over to the "updated" dot files.
E.g. my main important changes which I _always_ have a problem with:
- nvim (my own nvim dot files): When I press "No" when it asks me to copy the new nvim dotfiles, it basically leaves me with a symlink in my .config/ folder that points to a non existing dotfiles/.config/nvim. OR: If I hit yes, it'll overwrite my own config with the standard ml4w one
- .config/hypr/monitors/default.conf (my own monitor config in there)
- .config/hypr/keybindings/default.conf (changed some keybinds for my own HHKB type layout)

I always end up needing to redo this. I remember though that it did ask me to create a backup and then also copy over from that backup - I clearly remember having selected all the files, but they weren't copied over - e.g. I'm left with a broken monitor setup.

**To Reproduce**
1. With own changes of dotfiles, run a ml4w-hyprland-setup after update
2. Hit yes on backup, select all files to be backed up and confirm
3. After update, monitors immediately flicker, indicating the monitors/default.conf was overwritten by the defaults of ml4w - in fact, not a single one of my own conflicting dotfiles is untouched.

**Expected behavior**
I run an update, I hit create backup, I select which files to copy over from the backup. Then ideally I run a merge on two conflicting ones if there's some sort of new hyprland requirements to fix them up. Once I'm done running the script, I should have the latest changes of upstream without having messed up my own dotfiles.

**Screenshots**
Not needed

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I was thinking if this is even a bug or not, but the way the script presents the options to backup and then copy over the existing ones to the new dotfiles does suggest that it should work like this.

**Comment by mylinuxforwork** [comment]
Thanks for testing. I will check.

**Comment by Neo-29** [comment]
Confirmed

**Comment by mylinuxforwork** [comment]
I will test with the upcoming 2.9.7 when I update from 2.9.6.7.
