### ISSUE TITLE
[BUG] Invalid keyboard layout passed. Error at startup.

### ISSUE THREAD

**Issue by electricsteve** [mylinuxforwork/dotfiles#441]
**Describe the bug**
When I login to hyprland this error pops up for a split seconds, it always goes away, but it bothers me. I somehow managed to get it now by connecting to a bluetooth device, but this was good because now I could take a screenshot.

**To Reproduce**
1. Login
2. Look at the top

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/user-attachments/assets/2cc4118c-c061-4243-bbed-9b3c5b76c4dc)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I set the variant as qwerty when installing and the layout to us.

**Comment by electricsteve** [comment]
Also now the error is stuck on my screen till i restart.

**Comment by mylinuxforwork** [comment]
Thank for bringing this up. Can you share the content of your .config/hypr/conf/keyboard.conf

**Comment by electricsteve** [comment]
[keyboard (Copy).txt](https://github.com/user-attachments/files/17748172/keyboard.Copy.txt)

**Comment by mylinuxforwork** [comment]
@electricsteve Thank you. I will test on my system and come back to you soon. Have you tested if it’s working without querty as keyboard variant, means just

`kb_variant =`

**Comment by electricsteve** [comment]
Ok so with that set to nothing it works, maybe I shouldn't have chosen the variant at startup, because it's unneeded, but it's still a bug that it's causing an error, even that it's allowed to be chosen.

**Comment by mylinuxforwork** [comment]
Unfortunately, I cannot test for valid keyboard configurations during the installer. The number of possible combinations is too high.
