### ISSUE TITLE
Problem with installing dotfiles

### ISSUE THREAD

**Issue by justinsus1** [mylinuxforwork/dotfiles#442]
ml4w-hyprland -setup

(process:3063): Gtk-WARNING **: 22:46:24.534: Unknown key gtk-modules in /home/justin_sus1/.config/gtk-4.0/settings.ini

(process:3063): Adwaita-WARNING **: 22:46:24.551: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
:: Using configuration in: /home/justin_sus1/.config/ml4w-hyprland-settings
:: hyprctl.sh updated in /home/justin_sus1/.config/ml4w-hyprland-settings
:: Using default settings.json in /tmp/.mount_ML4W_HQftopR/usr/bin
Traceback (most recent call last):
  File "/tmp/.mount_ML4W_HQftopR/usr/bin/ml4w-hyprland-settings.py", line 86, in do_activate
    self.initUI()
  File "/tmp/.mount_ML4W_HQftopR/usr/bin/ml4w-hyprland-settings.py", line 134, in initUI
    value = self.getKeywordValue(i["keyword"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ML4W_HQftopR/usr/bin/ml4w-hyprland-settings.py", line 360, in getKeywordValue
    colorhex = custom_val.split(" ")[0]
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'custom_val' where it is not associated with a value

i have know idea what is happening 

arch linux

**Comment by mylinuxforwork** [comment]
I will check on a minimal Arch Installation as soon as possible.

have you installed an Arch profile?

**Comment by mylinuxforwork** [comment]
@justinsus1 Can you share the content of your .config/gtk-4.0/settings.ini

**Comment by mylinuxforwork** [comment]
Cannot confirm any issues.
