### ISSUE TITLE
the CPU and RAM widgets from the sidebar was not working

### ISSUE THREAD

**Issue by FR33R00T5** [mylinuxforwork/dotfiles#444]
the solution was to change the code in the config.js file from the ags folder.
i had to change the "mem" into "speicher" and the "cpu's" into "%CPU's". 
 
i run one system with endeavour and the other one with cachy and the problem was on both.

**Comment by mylinuxforwork** [comment]
This looks strange.
Can you share more details?

**Comment by mylinuxforwork** [comment]
@FR33R00T5 Can you share a screenshot of your code changes.
Please note that ags has recently changed the code base. Maybe this is the reason.

**Comment by keremenci** [comment]
I can +1. It seems ags changed the entire interface.
```
keremenci@archaon ~/.config 
> ags -t sidebar
Error: unknown shorthand flag: 't' in -t
Usage:
  ags [command]

Available Commands:
  run         Run an app
  request     Send a request to an instance
  list        List running instances
  inspect     Open up Gtk debug tool
  toggle      Toggle visibility of a Window
  quit        Quit an instances
  types       Generate TypeScript types
  bundle      Bundle an app
  init        Initialize a project directory
  help        Help about any command

Flags:
  -h, --help      help for ags
  -v, --version   version for ags

Use "ags [command] --help" for more information about a command.
```

**Comment by mylinuxforwork** [comment]
> I can +1. It seems ags changed the entire interface.
> 
> ```
> keremenci@archaon ~/.config 
> > ags -t sidebar
> Error: unknown shorthand flag: 't' in -t
> Usage:
>   ags [command]
> 
> Available Commands:
>   run         Run an app
>   request     Send a request to an instance
>   list        List running instances
>   inspect     Open up Gtk debug tool
>   toggle      Toggle visibility of a Window
>   quit        Quit an instances
>   types       Generate TypeScript types
>   bundle      Bundle an app
>   init        Initialize a project directory
>   help        Help about any command
> 
> Flags:
>   -h, --help      help for ags
>   -v, --version   version for ags
> 
> Use "ags [command] --help" for more information about a command.
> ```

Yes. And I cannot find a fix on the ags wiki.

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/issues/443

**Comment by mylinuxforwork** [comment]
@keremenc I will close this issue for now. The ags issue is still open. See link above.

**Comment by FR33R00T5** [comment]
i'm sorry-i had a strange,long day of work! -thanks for thinking about my issue! the only thing i can say: i found the solution just with chatgpt. it seems my systems runs in german. i have no idea this will help or not ;) at the end i'm just happy it runs like it should! thank you for your great work and engagement!!!
