### ISSUE TITLE
[BUG] wal does not initialize cache

### ISSUE THREAD

**Issue by varandru** [mylinuxforwork/dotfiles#447]
**Describe the bug**
A lot of things fail to load due to missing css files in .cache/wal

**To Reproduce**
Fresh installation of ml4w-dotfiles. Try to launch "All Keybindings" from the welcome menu. 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/6aaff178-00ba-4d84-b8b5-d8e4ee2cdddd)

**Distribution (please complete the following information):**
 - Manjaro

**Additional context**
The problem persists for both waybar and any way you could launch rofi. I tried to copy them directly and new errors popped up.

**Comment by mylinuxforwork** [comment]
First try to reboot.

Then run ml4w-hyprland-setup again.

If it is still not working:
Is the status bar available? If yes please click on the wallpaper icon, or enter waypaper in a terminal, select a wallpaper and try again.

if isn’t working, check if pywal is installed.

Enter wal -h

if not run yay -S python-pywal

**Comment by mylinuxforwork** [comment]
@varandru Any updates?

**Comment by varandru** [comment]
Sorry for the late response. The problem is on the work PC, only checked email today. 

The problem does persist. wal is installed: 
```
wal -h
Usage: wal [OPTION] -i '/path/to/dir'

Flags:
  -a                      Set terminal background transparency. *Only works in URxvt*
  -c                      Delete all cached colorschemes.
  -f '/path/to/colors'    Load colors directly from a colorscheme file.
  -h                      Display this help page.
  -i '/path/to/dir'       Which image to use.
     '/path/to/img.jpg'
  -n                      Skip setting the wallpaper.
  -o 'script_name'        External script to run after 'wal'.
  -q                      Quiet mode, don't print anything.
  -r                      Reload current colorscheme.
  -t                      Fix artifacts in VTE Terminals. (Termite, xfce4-terminal)
  -x                      Use extended 16-color palette.
```

I can start waybar manually, but it starts with default settings. The background has been set manually, in waypaper, to the one I prefer. It did not cause the cache to appear, sadly. Now, unless I comment out the path to these files, I can't even start rofi as a launcher: same error. Had to launch it from CLI to get here.

**Comment by varandru** [comment]
Commenting out the `@import "~/.cache/wal/colors-rofi-pywal"` line in rofi/config.rasi makes rofi at least operational, although the errors are to be expected: 
![image](https://github.com/user-attachments/assets/7f97ce36-4afa-4acf-9494-8b4ef94dd9be)

**Comment by varandru** [comment]
Also, this is off-topic: is adventure game studio critical for anything? I currently would love to pull it out of the system.

**Comment by varandru** [comment]
Some progress achieved: running wal manually (with my wallpaper as the argument) and then running the wallpaper.sh script seems to have achieved some positive results: 
1. I have a bar now. That's nice. 
2. Rofi sees invalid configuration, but at least it starts. That's also nice. 
3. More places scream about ags at me. Unless I'm missing something and a game engine is critical for my desktop to work, I'll try to disable them.

**Comment by varandru** [comment]
> Also, this is off-topic: is adventure game studio critical for anything? I currently would love to pull it out of the system.

Found an answer in another thread, that was a stupid question. In case someone else finds this:
* Adventure Game Studio is not, in fact, needed. 
* aylurs-gtk-shell is the ags that's actually used in the setup, and it has its own problems at the moment (#443)

**Comment by mylinuxforwork** [comment]
@varandru The script installs aylurs-gtk-shell. But the command to execute aylurs-gtk-shell is ags. Please check ags -h

**Comment by mylinuxforwork** [comment]
@varandru I will close this issue for now. Please reopen if there are still open questions. Or write to this issue.
