### ISSUE TITLE
[BUG] Cursor conf auto resets with every restart

### ISSUE THREAD

**Issue by xk7PRO2** [mylinuxforwork/dotfiles#448]
**Describe the bug**
The cursor.conf file in the `~/.config/hypr/conf` auto resets **Bibata-Modern-Ice** after I try to change anything in the file. I tried to change it to **Bibata-Modern-Classic** that is installed on the system and when I manually try the`hyprctl set cursor` command it works

**To Reproduce**
1)Just edit the file.
2)Restart

**Expected behavior**
I expected the cursor to change.

**Screenshots**
-

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
-

**Comment by mylinuxforwork** [comment]
@xk7PRO2 Hi. After changing the cursor in nwg-look, please open the welcome app, settings and then select Refresh GTK Settings.

I know, it’s not really intuitive but should work.

**Comment by xk7PRO2** [comment]
It worked. So the GTK settings was resetting the file?

**Comment by mylinuxforwork** [comment]
Yes. Thanks for testing.
