### ISSUE TITLE
[BUG] "Open Sidebar" button / icon in waybar does nothing right after install

### ISSUE THREAD

**Issue by SSYH** [mylinuxforwork/dotfiles#451]
**Describe the bug**
"Open Sidebar" button / icon in waybar does nothing right after install

**To Reproduce**
1. Installing on MacBook Pro (2013) (2880x1800), 16G, 256G SSD
2. Click on LL icon (Open Sidebar) ... get nada
Actually, this is now on every one of my ml4w-dotfiles installs... not just the MBP

**Expected behavior**
Expect  something to happen.

**Screenshots**
n/n given description

**Distribution (please complete the following information):**
 - EndeavourOS, fresh install, then fresh ml4w-dotfiles install

```
[sam@mbp101 ~]$ whereis ml4w-sidebar
ml4w-sidebar:
[sam@mbp101 ~]$ which ml4w-sidebar
which: no ml4w-sidebar in (/usr/lib/ccache/bin/:/usr/lib/ccache/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
[sam@mbp101 ~]$ 
```

**Comment by mylinuxforwork** [comment]
@SSYH Please see https://github.com/mylinuxforwork/dotfiles/issues/443
