### ISSUE TITLE
Click on Date in waybar does not open calendar flyout

### ISSUE THREAD

**Issue by JohRest** [mylinuxforwork/dotfiles#455]
Normally when I click on the date in the upper right corner I get a popup window / flyout showing the current month.

Now I can click, but nothing happens.

**Expected behavior**
Current Month is displayed in a small window below the date.

**Screenshots**
![image](https://github.com/user-attachments/assets/d807f2e8-5dfd-45a6-9628-b1a1a3b59616)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@JohRest It's due to the ags v2 update. I am currently testing 2.9.6.7 with ags  v2 support. Will release the new version today.

**Comment by JohRest** [comment]
Thanks for the info! I will close this ticket due to that.
