### ISSUE TITLE
[BUG] Removing package doesnt remove the apps

### ISSUE THREAD

**Issue by EyesWithoutFace** [mylinuxforwork/dotfiles#458]
**Describe the bug**

**To Reproduce**
1. Go to ML4W Welcome
2. Click on three dots
3. Click on uninstall
4. . Remove ml4w-hyprland-git

**Expected Behavior**
It uninstalls everything including the apps

**Distribution (please complete the following information):**
 -Arch Linux derivative (CachyOS)

**Additional context**
I am on KDE Plasma now. I shouldn't have these apps. I removed the AUR package, I removed the dotfiles.... Why are they still here?
![image](https://github.com/user-attachments/assets/bb200681-e0f4-4ce4-a214-73f73b4d3cdb)

**Comment by mylinuxforwork** [comment]
Thanks. Will check for 2.9.7
What happens when you try to start one of the apps? Maybe there is just the .desktop files left.

**Comment by EyesWithoutFace** [comment]
> Thanks. Will check for 2.9.7 What happens when you try to start one of the apps? Maybe there is just the .desktop files left.
Only app that works is ml4w welcome. Even when I had your dotfiles and hyprland enabled only that app worked.

**Comment by mylinuxforwork** [comment]
Can you check if ml4w desktop files are still there?

.local/share/applications

If yes, please remove them. It's from legacy versions.

**Comment by mylinuxforwork** [comment]
Will be fixed with 2.9.7

**Comment by EyesWithoutFace** [comment]
> Can you check if ml4w desktop files are still there?
> 
> .local/share/applications
> 
> If yes, please remove them. It's from legacy versions.

Could you tell me how to safely remove them? it wont let me with right click delete
