### ISSUE TITLE
ML4W Dotfiles Settings -> Format Specifications -> 404 error

### ISSUE THREAD

**Issue by legymhueck** [mylinuxforwork/dotfiles#46]
**Describe the bug**
The url behind the button "Format Specifications" in the "Clock Format" section has obviously changed.
The button calls "https://fmt.dev/latest/syntax.html#chrono-specs", which produces a "404 file not found" error.
The correct site, I think, is: https://fmt.dev/latest/syntax/#chrono-format-specifications

**To Reproduce**
1. Press button "Format Specifications" in ML4W Dotfiles Settings

**Expected behavior**
Get the format specs site for clock display

**Distribution (please complete the following information):**
 - Arch Linux
 - ML4W Dotfiles 2.9.3

**Additional context**
Thanks again for this awesome project!

**Comment by mylinuxforwork** [comment]
@legymhueck Moved your issue to the Dotfiles repository.

**Comment by mylinuxforwork** [comment]
Push the fix to the main branch. You can run the installer again. Thanks again for testing.
