### ISSUE TITLE
[BUG] AUR still in aur/ml4w-hyprland-git 2.9.6.6 

### ISSUE THREAD

**Issue by mrjxtr** [mylinuxforwork/dotfiles#462]
**Describe the bug**
I wanted to check what version of ml4w I have installed using `yay -Ss` because it tells me what I have installed. But it mentions that I have 2.9.6.7 installed but when the AUR package is still at 2.9.6.6

**To Reproduce**
running the command `yay -Ss ml4w` in terminal

```
❯ yay -Ss ml4w
aur/ml4w-hyprland-git 2.9.6.6.r10.gaba4b89-1 (+0 0.00) (Installed: 2.9.6.7.r0.g9a2f4c5-1)
    The ML4W Dotfiles for Hyprland - An advanced and full-featured configuration for the dynamic tiling window manager Hyprland including an easy to use installation script for Arch based Linux distributions.
aur/ml4w-hyprland 2.9.6.7-4 (+3 0.93) 
    The ML4W Dotfiles for Hyprland - An advanced and full-featured configuration for the dynamic tiling window manager Hyprland including an easy to use installation script for Arch based Linux distributions.
```

**Expected behavior**
AUR packaged should be the latest 2.9.6.7

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
I am still trying to figure out ho to make the sidebar with AGS to work and it mentiones that 2.9.6.7 fixes it, I wanted to update but through the ML4W welcome app and when it asked my what version of ml4w i have installed so I sis `yay -Ss ml4w` and now here I am.

**Comment by mylinuxforwork** [comment]
Fixed.
