### ISSUE TITLE
ML4W Dotfiles 2.9.7.0BETA now on main branch

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#464]
Hi Arch & Fedora users,

I have just pushed the version ML4W Dotfiles 2.9.7.0BETA no on the main branch. **This new version comes in addition to Arch support now with Fedora support.**

You can find the new installation instructions for Arch and Fedora here: https://github.com/mylinuxforwork/dotfiles/wiki/Installation-2.9.7.

Arch users can still install the latest git version with `yay -S ml4w-hyprland-git`

> The new version is still in testing and I will commit several fixes and improvement the next days.

Please feel free to test with me and share your findings as issues on GitHub.

**Comment by Neo-29** [comment]
Tested.
But still broken on qemu./virtmanager
Unfortunately

**Comment by mylinuxforwork** [comment]
> Tested. But still broken on qemu./virtmanager Unfortunately

Yes. Unfortunately. You need to downgrade to 0.45.0 to make it work on VMs. But as far as I know the Hyprland team is already working on the issue.

**Comment by Neo-29** [comment]
> > Tested. But still broken on qemu./virtmanager Unfortunately
> 
> Yes. Unfortunately. You need to downgrade to 0.45.0 to make it work on VMs. But as far as I know the Hyprland team is already working on the issue.

Tks for the tip and update.
If any "good news" don't hesitate to post here, we'll party 😉😉😉😉😉

**Comment by mylinuxforwork** [comment]
> > > Tested. But still broken on qemu./virtmanager Unfortunately
> > 
> > 
> > Yes. Unfortunately. You need to downgrade to 0.45.0 to make it work on VMs. But as far as I know the Hyprland team is already working on the issue.
> 
> Tks for the tip and update. If any "good news" don't hesitate to post here, we'll party 😉😉😉😉😉

Me too.

**Comment by mylinuxforwork** [comment]
> > > > > Tested. But still broken on qemu./virtmanager Unfortunately
> > > > 
> > > > 
> > > > Yes. Unfortunately. You need to downgrade to 0.45.0 to make it work on VMs. But as far as I know the Hyprland team is already working on the issue.
> > > 
> > > 
> > > Tks for the tip and update. If any "good news" don't hesitate to post here, we'll party 😉😉😉😉😉
> > 
> > 
> > Me too.
> 
> Downgrading to 0.45 didn't work at all

Have you downgraded aquamarine too?

**Comment by Neo-29** [comment]
> > > > > > Tested. But still broken on qemu./virtmanager Unfortunately
> > > > > 
> > > > > 
> > > > > Yes. Unfortunately. You need to downgrade to 0.45.0 to make it work on VMs. But as far as I know the Hyprland team is already working on the issue.
> > > > 
> > > > 
> > > > Tks for the tip and update. If any "good news" don't hesitate to post here, we'll party 😉😉😉😉😉
> > > 
> > > 
> > > Me too.
> > 
> > 
> > Downgrading to 0.45 didn't work at all
> 
> Have you downgraded aquamarine too?

Yes... Nothing works

**Comment by mylinuxforwork** [comment]
@Neo-29 Have you tried this https://github.com/mylinuxforwork/dotfiles/wiki/Installation-in-a-KVM-virtual-machine

**Comment by Neo-29** [comment]
> @Neo-29 Have you tried this https://github.com/mylinuxforwork/dotfiles/wiki/Installation-in-a-KVM-virtual-machine

Of course.

**Comment by mylinuxforwork** [comment]
@Neo-29 It seams that the bug has been fixed on Hyprland side. I can see a PR addressing this issue. Fingers cross that the next Hyprland release includes the fix.

**Comment by Neo-29** [comment]
You should wait before closing the issue.
Just experience😉
