### ISSUE TITLE
[BUG]  upgrade to 2.9.6.7.r62.g0ddf097-1 showed errors for missing packages that the diags said were there 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#465]
**Describe the bug**
updated  ml4w-git  2.9.6.x to 2.9.6.7  ml4w-setup reported missing packages 
hyprlock, dunst, waypaper ....   

However the files were there 

**To Reproduce**
1. yay -Syu 
2. ml4w-hyprland-setup 
3
**Expected behavior**
should not report missing pacakges 

**Screenshots**
Attached install log

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

[20241122084501-log.txt](https://github.com/user-attachments/files/17871308/20241122084501-log.txt)

**Comment by mylinuxforwork** [comment]
@dwilliam62 Does this error still exists with 2.9.7.0 latest commit?

**Comment by ajboni** [comment]
It just happened to me in 2.9.7.0BETA and last week version

**Comment by dwilliam62** [comment]
> @dwilliam62 Does this error still exists with 2.9.7.0 latest commit?

I don't believe so, but there is no revision info just 0BETA   What is the proper way to update it with Fedora?  I re-ran the install script   Then also ran the ml4w-hyprland-setup which I believe just re-did the same as the install script

**Comment by abravot01** [comment]
Hello, im also having the same issue

Running Arch

[hyprland_ml4w_error.txt](https://github.com/user-attachments/files/17896640/hyprland_ml4w_error.txt)

**Comment by mylinuxforwork** [comment]
@ajboni @abravot01 @dwilliam62 I have finally again a working Arch VM ;-) Can confirm it. I will check.

**Comment by PrymalInstynct** [comment]
I am having the same issue when trying to upgrade to the 2.9.7 BETA from 2.9.6

```
:: ERROR - Some required commands are not available:
dunst waybar hyprpaper hyprlock hypridle hyprshade wal gum wlogout ags magick waypaper
```

**Comment by mylinuxforwork** [comment]
@PrymalInstynct @dwilliam62 Found the issue and it's fixed on main branch (rolling release ml4w-hyprland-git)

**Comment by PrymalInstynct** [comment]
Your fix appears to have addressed the reported issue.
