### ISSUE TITLE
[BUG]  upgrade to 2.9.6.7.r62.g0ddf097-1  reset all preferences (editor, waybar, hyprlock, etc) 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#466]
**Describe the bug**
Upgraded to 2.9.6.7-git   reset all my settings.  editor, filemangers,  decorations, hyprlock, waybar settings like chatgpt

**To Reproduce**
1  yay -Syu 
2  ml4w-hyrpland-setup

**Expected behavior**
Settings would be retained

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux
 - 
 - ... 

**Additional context**
Install log 
[20241122084501-log.txt](https://github.com/user-attachments/files/17871343/20241122084501-log.txt)

**Comment by dwilliam62** [comment]
> Thanks for testing. Have you chosen restore during the update?

I accepted the defaults and I have automation.sh set up to restore  I believe that shows in the log as well

**Comment by mylinuxforwork** [comment]
> > Thanks for testing. Have you chosen restore during the update?
> 
> I accepted the defaults and I have automation.sh set up to restore I believe that shows in the log as well

Can you please make another change in your settings and run the setup again?

**Comment by mylinuxforwork** [comment]
@dwilliam62 Just pushed a new update to the main branch with a fix for kitty and nvim.

**Comment by mylinuxforwork** [comment]
@dwilliam62 And the restore of settings should also work again.

**Comment by ajboni** [comment]
It also reset my custom.conf and autostart.conf

tried the latest version. Same issue. I'm using automation.sh and I had no restore prompt

**Comment by mylinuxforwork** [comment]
> It also reset my custom.conf and autostart.conf
> 
> tried the latest version. Same issue. I'm using automation.sh and I had no restore prompt

Do you use 2.9.7.0Beta?

**Comment by ajboni** [comment]
yes! just updated via the AUR. The backup folder didn't have my modifications as well. had to use 2.9.6.7 files. Let me know if you need me to do some testing or logs, I  will be around for a bit.

**Comment by dwilliam62** [comment]
> @dwilliam62 And the restore of settings should also work again.

I just upgraded to latest rolling release and it still resets everything   All my preferences, the screen resolution, etc..

**Comment by mylinuxforwork** [comment]
> > @dwilliam62 And the restore of settings should also work again.
> 
> I just upgraded to latest rolling release and it still resets everything All my preferences, the screen resolution, etc..

Have you updated from 2.9.6.7 or updated 2.9.7.0BETA? Have you rebuild the package during yay -S ml4w-hyprland-git

**Comment by dwilliam62** [comment]
> > > @dwilliam62 And the restore of settings should also work again.
> > 
> > 
> > I just upgraded to latest rolling release and it still resets everything All my preferences, the screen resolution, etc..
> 
> Have you updated from 2.9.6.7 or updated 2.9.7.0BETA? Have you rebuild the package during yay -S ml4w-hyprland-git

Yes   I jist tried another VM  same thing   All my preferences are reset. 

![Screenshot_24-Nov_15-54-13_25773](https://github.com/user-attachments/assets/17adb951-39e9-4b93-9760-2ea2262136bc)

![Screenshot_24-Nov_15-54-24_26589](https://github.com/user-attachments/assets/92cd1936-e51d-417b-b499-5dce3c288757)
![Screenshot_24-Nov_16-00-00_21540](https://github.com/user-attachments/assets/faeac096-099a-45c3-a829-59c0936cc023)
![Screenshot_24-Nov_16-00-13_16863](https://github.com/user-attachments/assets/e7e572a7-7dda-4d10-978f-3886c69884ee)


Before and after the update and runj ml4w-hyprland-setup

**Comment by mylinuxforwork** [comment]
@dwilliam62 You have updated to 2.9.6.7 and not to 2.9.7.0, right?

**Comment by dwilliam62** [comment]
> @dwilliam62 You have updated to 2.9.6.7 and not to 2.9.7.0, right?

I am running the rolling release it shows as 2.9.7.0  as the screenshot shows

**Comment by mylinuxforwork** [comment]
@dwilliam62 Just updated from 2.9.6.7 to 2.9.7.0 and the ml4w settings could be restored. 

Before:

![screenshot_25112024_111813](https://github.com/user-attachments/assets/a2ddde71-4633-4659-8ea2-d8e876527b68)

After:

![screenshot_25112024_112446](https://github.com/user-attachments/assets/e682b7fa-6681-4b31-b713-d3f35b1ea1a3)

I haven't used the automation.sh. Maybe this is the problem. I will continue testing.

**Comment by mylinuxforwork** [comment]
@dwilliam62 Can confirm that the reason is obviously an issue with the automation.sh. I will check.

**Comment by mylinuxforwork** [comment]
@dwilliam62 @ajboni  Fixed on rolling release. Please also see the updated automation.tpl https://github.com/mylinuxforwork/dotfiles/blob/main/share/templates/automation.tpl

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing.
