### ISSUE TITLE
[BUG]  SDDM error Fedora 41 sequoia theme 

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#467]
**Describe the bug**

**To Reproduce**
 install ml4w select optional SDDM theme , reboot 

**Expected behavior**
SDDM theme would be applied 

**Screenshots**
![image](https://github.com/user-attachments/assets/d9b006d3-92db-45a1-87ea-14213a63cd16)

**Distribution (please complete the following information):**
Fedora 41

**Comment by dwilliam62** [comment]
sudo systemctl disable lightdm 
sudo dnf install sddm  sddm-themes
sudo systemctl enable sddm 
sudo systemctl stop lightdm  
reboot 
I set it to elarun for the time being  it did prompt me to install the sequoia theme 

This is a VM in case you were wondering 
suod dnf install aquamarine-0.4.5   that will downgrade it  then edit /etc/dnf/dnf.conf 

excludepackages=aquamarine 
exlcludepackages=hyprland 

The 2nd one isn't really needed as the hyprland won't update w/o updated aquamarine b/c of package maintainer set dependencies

**Comment by dwilliam62** [comment]
Where are the appimages for Fedora?  I can't find them and they won't start

**Comment by mylinuxforwork** [comment]
Here are the app images. https://github.com/mylinuxforwork/dotfiles/tree/main/share/apps

Will be installed to /usr(bin

**Comment by enessmr** [comment]
You must install all QT5/6 dependencies

**Comment by dwilliam62** [comment]
> You must install all QT5/6 dependencies

Do you happen to know what those are there are many qt5/6 pkgs

**Comment by dwilliam62** [comment]
> Here are the app images. https://github.com/mylinuxforwork/dotfiles/tree/main/share/apps
> 
> Will be installed to /usr(bin

That worked!   Apps are working

**Comment by dwilliam62** [comment]
dnf install qt6-qt5compat to resolve sddm issue 
![image](https://github.com/user-attachments/assets/ceca26cf-860c-4c32-bd99-57ae4b296e9c)

**Comment by dwilliam62** [comment]
> You must install all QT5/6 dependencies

thank you
