### ISSUE TITLE
[BUG]  Fastfetch  reports pacman in Fedora ML4W

### ISSUE THREAD

**Issue by dwilliam62** [mylinuxforwork/dotfiles#470]
**Describe the bug**
Your default config.jsonc shows (pacman) under packages 

![image](https://github.com/user-attachments/assets/d3aa6827-12a5-41fa-bb8a-575222c8e675)

 
![image](https://github.com/user-attachments/assets/c085a761-82c6-4114-a9af-ba7d581f93e5)

**Comment by mylinuxforwork** [comment]
Fixed with latest commit. Thanks for testing.
