### ISSUE TITLE
[BUG] Apps, waybar theme, clock, clipboard button has stopped working 

### ISSUE THREAD

**Issue by Corrosivex** [mylinuxforwork/dotfiles#472]
**Describe the bug**

After reinstalling the dotfiles, now my "Apps" button doesn't work. It doesn't matter if I try clicking it with left click (show apps) or right click (show shortcuts) If I try to open the apps list with the shortcut, it also doesn't open.

The clock on the top right of the screen also has disappeared.

The clipboard button doesn't work anymore, and the button to change the waybar theme has broken too.

**To Reproduce**

I dont know, I just have tried to uninstall with the button on the right corner of the Welcome thing, and after reinstalling again (either stable or beta version), it keeps breaking.

**Expected behavior**

**Screenshots**
I'll add later.

**Distribution (please complete the following information):**

 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@Corrosivex Can you check if rofi is installed successfully?

Just enter rofi in a terminal

**Comment by Corrosivex** [comment]
It says:

(process:1572): Rofi-WARNING : Failed to set locale.

**Comment by mylinuxforwork** [comment]
> It says:
> 
> (process:1572): Rofi-WARNING : Failed to set locale.

Can you check https://forum.manjaro.org/t/rofi-failed-to-set-locale/134438/6

**Comment by Corrosivex** [comment]
> > It says:
> > (process:1572): Rofi-WARNING : Failed to set locale.
> 
> Can you check https://forum.manjaro.org/t/rofi-failed-to-set-locale/134438/6

Fixed!.

For some weird reason, it was only using en_US.UTF-8 UTF-8 despite having selected es_ES.UTF-8 on the dotfiles installer.

After using `vim/etc/locale.gen` and then uncommenting the Spanish keyboard layout, and after that `sudo locale-gen && reboot` now works everything fine.

Thank you for your help!.
