### ISSUE TITLE
[FEATURE] "Install Printer" Support for Fedora 41 (2.9.7.0BETA)

### ISSUE THREAD

**Issue by Iprobablydontknowwhatimdoing** [mylinuxforwork/dotfiles#476]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I was looking through the various awesome scripts included with your dotfiles, and found that the "Install Printers" script does not work for fedora.

**Describe the solution you'd like**
Adding support for fedora into the ML4W dotfiles, removing it from the menu, or checking if you're running fedora and telling you that script is only avalable on arch

**Describe alternatives you've considered**
It's not a dealbreaker for me, just something I noticed. While I don't think it's necessary to get it working now, a clear indication that it is not available for fedora would be nice, so I know what will work and what won't.

**Additional context**
The drivers for my printer are not easily available, and so I eventually have to find them on the website. I don't know if something like what that script was would be even possible on fedora.

**Comment by mylinuxforwork** [comment]
@Iprobablydontknowwhatimdoing I am thinking about to remove this script again. Because every printer setup is individual and should be not related to the dotfiles. I want to clean up a bit with 2.9.7 and reduce the complexity.

**Comment by mylinuxforwork** [comment]
@Iprobablydontknowwhatimdoing Removed all specific Arch menu items from the welcome app. Latest commit.
