### ISSUE TITLE
[FEATURE] Remove Pacman Scripts from Fedora Dotfiles

### ISSUE THREAD

**Issue by Iprobablydontknowwhatimdoing** [mylinuxforwork/dotfiles#477]
**Is your feature request related to a problem? Please describe.**
This is just an additional thing that might be nice to polish off the fedora dotfiles before a full release. Related to the "Install Printer script" feature request.
**Describe the solution you'd like**
Removing Arch-only references (e.g. pacman config, unlock databases, etc.) from the ML4W welcome app, dotfile settings app (default AUR helper), and scripts.
**Describe alternatives you've considered**
I doubt leaving them there would cause much confusion (anyone who can successfully install hyprland probably knows that references to yay or the AUR do not apply to them), but it would add a bit more polish and declutter the menus.
**Additional Context**

**Comment by mylinuxforwork** [comment]
@Iprobablydontknowwhatimdoing Thanks for your feedback. Will work on it.

**Comment by mylinuxforwork** [comment]
@Iprobablydontknowwhatimdoing Removed all specific Arch menu items from the welcome app. Latest commit.
