### ISSUE TITLE
[BUG] Waybar don't start on Arch after the upgrade to the lastest kernel LTS and zen 

### ISSUE THREAD

**Issue by Firebleudark** [mylinuxforwork/dotfiles#478]
I just did my update on ArchLinux like everyday. This update was pretty important because I upgrade my laptop to the lastest kernel lts and zen (6.12).
When I reboot my pc, all work fine except waybar, I decided to start waybar on the terminal but the configuration is not the correct one (picture).

Do you have a solution ?
![screenshot_24112024_044117](https://github.com/user-attachments/assets/0a22d4ad-7f88-4fde-b1c3-9368abdd2646)

**Comment by Firebleudark** [comment]
Update : I launch the script /toggle.sh and everything work fine even when I reboot, waybar launch automatically. BUT my waybar is in black not in white (picture).
![screenshot_24112024_045340](https://github.com/user-attachments/assets/ed21c208-d51b-4fbf-bc3c-8ee01ac64cfa)

**Comment by mylinuxforwork** [comment]
@Firebleudark You can change the theme by hovering over the settings wheel icon within the left section and then the 3 dots.
