### ISSUE TITLE
[BUG] Hyprland not Loading after SDDM Successful Login

### ISSUE THREAD

**Issue by stoyanovgeorge** [mylinuxforwork/dotfiles#485]
**Describe the bug**
The Hyprland doesn't start after successfully login in SDDM

**To Reproduce**
1. Start your PC
2. log in to the SDDM login screen using your password and press enter
3. At this point the login screen just hangs and nothing happens and my user is not logged into Hyprland, I need to press Ctrl + Alt + FX to manually login to Hyprland

**Expected behavior**
Loading of Hyprland after successful login

**Screenshots**
None

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Found the culprit and a workaround. My `/usr/lib/systemd/user/hyprland-session.service` was botched and I had typo on two of the lines: 

```
ExecStart=/usr//usr/bin/Hyprland
ExecStop=/usr//usr/bin/hyprctl dispatch exit
```

So I just removed the first `/usr/` from it and after restarting the login was working correctly. 

```
ExecStart=/usr/bin/Hyprland
ExecStop=/usr/bin/hyprctl dispatch exit
```

I am not sure if this is an issue with the repo, but I would presume so. I have installed it yesterday. 

---

And one other thing the `ml4w-diagnosis` script was also not placed in my scripts directory, so I needed to manually copy it there. 

---

Great work, by the way, your dotfiles are top-notch and very well-structured!

**Comment by Stewart86** [comment]
Sounds like a duplicate of #453. By any chance you are running on a VM?

**Comment by mylinuxforwork** [comment]
@stoyanovgeorge The wrong paths in hyprland-session.service is already reported to the Hyprland team. Shoudl be fixed in upcoming releases of Hyprland.

**Comment by mylinuxforwork** [comment]
@stoyanovgeorge Let me check the diagnosis issue.

**Comment by mylinuxforwork** [comment]
@stoyanovgeorge Cannot replicate the issue with 2.9.7.0RC1. Everything is working fine.

![image](https://github.com/user-attachments/assets/d9c3fe0f-830a-439a-b126-c2f500dc788b)

**Comment by stoyanovgeorge** [comment]
@Stewart86 no, I am running on my desktop, not VM. 
@mylinuxforwork strange, why it didn't work on my side, but good to know that it is working on your side. Closing the ticket.

**Comment by mylinuxforwork** [comment]
@stoyanovgeorge Thanks for your feedback. Please update to the latest 2.9.7.0RC1 and try again. https://github.com/mylinuxforwork/dotfiles/wiki/Installation

**Comment by Plite7067** [comment]
I've just had both problems on arch using the aur package version 2.9.7.0-1
