### ISSUE TITLE
[BUG] Fcitx5 doesn't work on electron or qt programs after installing the theme

### ISSUE THREAD

**Issue by ZeroHzzzz** [mylinuxforwork/dotfiles#486]
**Describe the bug**
Fcitx5 do not work fine after i install the theme.But it did work before installation .And he still works after I uninstalled the theme, so i think it is a bug about this theme. and My env has set to :
 XMODIFIERS=@im=fcitx
 GTK_IM_MODULE=fcitx
 QT_IM_MODULE=fcitx
but nothing change. No error output. Shouldn't be able to enable the input method as nothing happens when I use the win+space shortcut, and switching manually doesn't work either

You may be able to reproduce the problem in an electron-based application like extra/obsidian 1.7.7-1 or a qt application like aur/wechat 4.0.0.23-13

**Expected behavior**
Using fcitx5 to input Chinese

**Distribution (please complete the following information):**
 - Arch Linux x86_64
 - Hyprland(wayland), GTK2/3

**Comment by Stewart86** [comment]
@ZeroHzzzz I am also using Fcitx5 and it is working fine on my end without additional configuration. I also do not use the env. Maybe try removing it? 

I also have custom theme for fcitx5, I don't think the theme matter?

**Comment by mylinuxforwork** [comment]
Can someone of you share a screenshot of fcitx5? Never used it before.

**Comment by ZeroHzzzz** [comment]
> @ZeroHzzzz I am also using Fcitx5 and it is working fine on my end without additional configuration. I also do not use the env. Maybe try removing it?
> 
> I also have custom theme for fcitx5, I don't think the theme matter?

I configured it as per the fcitx5 wiki. But as you said, it works fine without setting env, I use it on another preset theme prasanthrangan and end-4 and it works fine, no environment variables are configured, but then only ml4w doesn't work

**Comment by Stewart86** [comment]
@mylinuxforwork you can see some screenshot in this [discussion](https://github.com/hyprwm/Hyprland/discussions/421) 

Was just trying across a few apps that I am using. I think only Brave is having issue with it. Most of my chat apps are working fine, and it's working with ther terminal too. I don't know why brave wasn't working now, it used to work before as I remembered.

**Comment by Stewart86** [comment]
by using `Brave --enable-wayland-ime` I am able to use fcitx5 now. 你看！ （you see in chinese)

**Comment by marshalby2** [comment]
> > by using `Brave --enable-wayland-ime` I am able to use fcitx5 now. 你看！ （you see in chinese)
> 
> 我试过了，但是没有用。很神奇就是了，wiki上面其他两个主题上使用都没有问题

我也是和你一样的问题， 安装这个主题之前，我的微信是可以输入中文的，安装后就不可以了

**Comment by ZeroHzzzz** [comment]
> > > by using `Brave --enable-wayland-ime` I am able to use fcitx5 now. 你看！ （you see in chinese)
> > 
> > 
> > 我试过了，但是没有用。很神奇就是了，wiki上面其他两个主题上使用都没有问题
> 
> 我也是和你一样的问题， 安装这个主题之前，我的微信是可以输入中文的，安装后就不可以了

在启动的时候传入两个环境变量，XMODIFIERS=@im=fcitx和QT_IM_MODULE=fcitx，可以写到desktop文件里面
