### ISSUE TITLE
[FEATURE] Should include `xdg-desktop-portal-gtk` by default

### ISSUE THREAD

**Issue by Stewart86** [mylinuxforwork/dotfiles#487]
**Is your feature request related to a problem? Please describe.**
After taking days, with breaks in between, and multiple attempts of trying to get some of the apps that I've installed to open URLs in the browser, I have managed to found out that we are missing the `xdg-desktop-portal-gtk` packages with many of the apps are using the `org.freedesktop.portal.OpenUri` command to open links.

A simple `pacman -S xdg-desktop-portal-gtk` actually fixed all my trouble with URLs in apps like Obsidian, BetterBird, etc.

**Describe the solution you'd like**
Highly suggest that this package be included in the default list of things needed to be installed.

**Describe alternatives you've considered**
We could also use `xdg-desktop-portal-kde` but since I see the bash script located in `~/.config/hypr/scripts/xdg.sh` is looking for `xdg-desktop-portal-gtk` if it exist use it, then we should do the GTK one.

**Comment by mylinuxforwork** [comment]
@Stewart86 Yes. I agree. In earlier versions, the xdg-desktop-portal-gtk was the reason for the not loading waybar. But I found the issue and could fix it in 2.9.7. Will add xdg-desktop-portal-gtk as default again and remove it from the options script.

**Comment by mylinuxforwork** [comment]
Done. Just pushed an update to the main release with 2.9.7.0RC2. Thanks again.
