### ISSUE TITLE
[BUG] ML4W Welcome app in 2.9.7.0RC2 doesn't show Arch specific scripts under System

### ISSUE THREAD

**Issue by TomekBobrowicz** [mylinuxforwork/dotfiles#491]
**Describe the bug**

ML4W Welcome app in 2.9.7.0RC2 doesn't show Arch specific scripts under System. Its working using old 2.9.6.6 version

**Expected behavior**

This should be easily accessed as in 2.9.6.6 version from ML4W Welcome app - Settings - system. Settings like install printers or timeshift are missing there. They can be accessed from terminal in  ~/.config/ml4w/scripts/arch/ 
 
![image](https://github.com/user-attachments/assets/bf9e6fd3-b513-44df-9ead-0cb081ddeebf)

**Distribution (please complete the following information):**

 - Arch Linux. Fresh install of ml4w-hyprland-git

**Comment by mylinuxforwork** [comment]
@TomekBobrowicz Due to the Fedora support, I had to move the scripts to the folder. Will add an easy access to these system scripts in the next minor release.
