### ISSUE TITLE
[BUG] Flatpak apps don't run 

### ISSUE THREAD

**Issue by matheusmelo18** [mylinuxforwork/dotfiles#495]
**Describe the bug**
Apps Flatpak don't open 
**To Reproduce**
1. Go to 'Apps'
2. Click on 'Discord "flatpak" 

**Expected behavior**

**Screenshots**

**Distribution (please complete the following information):**
 - Fedora 40

**Additional context**

**Comment by mylinuxforwork** [comment]
@matheusmelo18 Thanks for testing. Can you open the apps from the command line?

**Comment by PerfMonk** [comment]
Same for me on Fedora 41. The script that start the browser should be modified to run a flatpak .
"flatpak run one.ablaze.floorp" in my case.  It can be changed in custom configuration=>Default Applications=>Browser.
It just not that easy to find if your are not familiar with the project (wich is my case).
Congratulations! I like it very much this Hyprland rice ;=)

**Comment by mylinuxforwork** [comment]
@PerfMonk Thank you. You have explained it perfectly.

**Comment by feikedonia** [comment]
I can reprecate the problem on EndeavourOS.
- Installed the Discord flatpak via KDE discover
- Started the Discord app via the App menu, as mentioned
- Discord didn't open, htop didn't show any procces with the 'discord' search string.

However:
I have installed other flatpakapps, namely Signal Messenger, which runs fine

**Comment by mylinuxforwork** [comment]
@feikedonia I would say it is not a dotfiles issue. It's coming obviously from wayland and electron apps. 

That's why I will close the issue for now because I cannot fix it through the dotfiles.
