### ISSUE TITLE
[FEATURE] Customize screen shader intensity

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#5]
Currently, We cannot modify Screen Shader. It would be great if we would be able to adjust screen shader according to our selfs.

**Comment by mimi0000oo** [comment]
Yes, that would be a great feature! I don't use the screenshader at the moment as I think it is too intense! I would love to see this implemented!

**Comment by crashbit666** [comment]
Ei! You can modify the blue light filter 
❯ cat /usr/share/hyprshade/shaders/blue-light-filter.glsl

Here it is. You can modify these vales:
const float temperature = 3000.0;
const float temperatureStrength = 0.8;

**Comment by mylinuxforwork** [comment]
@mimi0000oo @crashbit666 Just added three shaders with different intensities to the main branch. https://github.com/mylinuxforwork/dotfiles/tree/main/share/dotfiles/.config/hypr/shaders
