### ISSUE TITLE
[BUG] Timeshift is not opening in version 2.9.7.0

### ISSUE THREAD

**Issue by Koushikg88** [mylinuxforwork/dotfiles#519]
**Describe the bug**
If I open Timeshift in hyprland, its asking for root password as usual. But after providing the password no window for timeshift is showing.

**To Reproduce**
1. Go to apps 
2. Click on Timeshift
3. Provide root password and press enter
4. See error - no window is opening for timeshift

**Expected behavior**
A widow contains my snapshots should appear 

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@Koushikg88 Please open timeshift with sudo

`sudo timeshift --list`

**Comment by Koushikg88** [comment]
yes its showing the snapshots in terminal. So the gui is available for use in here?

**Comment by FR33R00T5** [comment]
"yay -S xorg-xhost " solved the problem for me

**Comment by Koushikg88** [comment]
> "yay -S xorg-xhost " solved the problem for me

yes, thanks @FR33R00T5 , it worked for me too
