### ISSUE TITLE
Turn off pywal for terminal

### ISSUE THREAD

**Issue by pilladipesh33** [mylinuxforwork/dotfiles#52]
Hey, I was wondering if there's a way I can add my own colors for alacritty instead of using color generated from wallpaper

**Comment by mylinuxforwork** [comment]
@pilladipesh33 Thanks for your request. 
This is currently not possible. But there is already an existing request related to that issue.
Please follow https://github.com/mylinuxforwork/dotfiles/issues/3

I will close this issue as duplicate.
