### ISSUE TITLE
[BUG] After a fresh install on arch oh-my-posh command error 

### ISSUE THREAD

**Issue by lisztor** [mylinuxforwork/dotfiles#521]
**Describe the bug**
When lauchin kitty using SUPER + enter we get at the first line "bash: oh-my-posh: command not found" and oh-my-bash doesn't launch

**To Reproduce**
1 - Launch kitty
The issue is located in ~/.config/bashrc/20-customization line 9 : " eval "$(oh-my-posh init bash --config $HOME/.config/ohmyposh/zen.toml)" "

**Expected behavior**
oh-my-posh have to be launched 

**Screenshots**
![image](https://github.com/user-attachments/assets/638aa1aa-6032-4623-9cd8-a27ed0173dc5)

**Distribution**
 - Arch Linux

**Comment by lisztor** [comment]
Oh i found the issue it's just that oh-my-posh didn't got installed

**Comment by mylinuxforwork** [comment]
Right. That’s the reason. In that case you have to install it manually.
