### ISSUE TITLE
[BUG] Waybar does mot appear on logon.

### ISSUE THREAD

**Issue by kghosh222** [mylinuxforwork/dotfiles#523]
**Describe the bug**
On  logging in, waybar is missing.
**To Reproduce**
1. Log in
2. See error - No Waybar

**Expected behavior**
Waybar should automatically appear

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
To make Waybar appear, it is necessary to press CTRL+Meta+B a few times.

**Comment by kghosh222** [comment]
I forgot to add, I am on ML4W Ver. 2.9.7.0BETA

**Comment by Neo-29** [comment]
Confirmed
To make Waybar appear, it is necessary to press CTRL+Meta+B a few times.

see #545 

in complement

**Comment by Neo-29** [comment]
Could be reproduced with "toggle show waybar" too.

**Comment by mylinuxforwork** [comment]
@kghosh222 Is it working now?

**Comment by kghosh222** [comment]
After upgrading to 2.9.7.1,

The waybar behaviour has not changed. After login, I must do a meta+ctrl+B
at least two times to make waybar appear.
Additionally, the screen remains devoid of any wallpaper (black screen).
I am using wpaperd to cycle through wallpapers.
Adding exec-once = wpaperd to custom.conf does not work.
I have to open a terminal and type wpaperd -d to start the cycling of
wallpapers.










*Best Regards...,K.Ghosh-------------------------------Mail:
***@***.*** ***@***.***>Skype: kunal.ghosh4Web:
gkssystems.blogspot.com <http://gkssystems.blogspot.in>Debian GNU/Linux
user No.301508*

**Comment by mylinuxforwork** [comment]
@kghosh222 Please check https://github.com/mylinuxforwork/dotfiles/issues/546 There was a big Python update.

**Comment by kghosh222** [comment]
Updated to 2.9.7.3, and waybar and wallpaper are back at startup.
Thanks.

When can we expect an ML4W Hyprland version for Debian?
I used the one at https://github.com/JaKooLit/Debian-Hyprland, and it
kind-of works, but not satisfactorily.
I believe you will do a much better job :)).










*Best Regards...,K.Ghosh-------------------------------Mail:
***@***.*** ***@***.***>Skype: kunal.ghosh4Web:
gkssystems.blogspot.com <http://gkssystems.blogspot.in>Debian GNU/Linux
user No.301508*

**Comment by mylinuxforwork** [comment]
@kghosh222 Thanks for testing. Great that it’s working again. I will definitely look into Debian support but I haven’t made a plan yet.
