### ISSUE TITLE
[FEATURE] Improve installupdate.sh for Fedora

### ISSUE THREAD

**Issue by PerfMonk** [mylinuxforwork/dotfiles#526]
Hi,

I just wanted the script to install update to be improved for fedora.  The Arch part does check for timeshift to take a snapshot and then check for flatpak if any other update.  The fedora part did only a dnf upgrade and no snapshot, no flatpak update.

I have made a small modification of the script to add the snapshot and flatpak to the fedora update.

Here is a copy of your script with my modifications. 
I just have modified the _isInstalledAUR to _isInstalled and have added the package check for fedora.
Then copied your Arch code to make the snapshot and update flatpak for Fedora.

 You may use it in any way  to create an improved installupdates.sh for all.

```

❯ cat installupBT.sh 
#!/bin/bash
#  ___           _        _ _   _   _           _       _             
# |_ _|_ __  ___| |_ __ _| | | | | | |_ __   __| | __ _| |_ ___  ___  
#  | || '_ \/ __| __/ _` | | | | | | | '_ \ / _` |/ _` | __/ _ \/ __| 
#  | || | | \__ \ || (_| | | | | |_| | |_) | (_| | (_| | ||  __/\__ \ 
# |___|_| |_|___/\__\__,_|_|_|  \___/| .__/ \__,_|\__,_|\__\___||___/ 
#                                    |_|                              

sleep 1
clear
install_platform="$(cat ~/.config/ml4w/settings/platform.sh)"
figlet -f smslant "Updates"
echo

# ------------------------------------------------------
# Confirm Start
# ------------------------------------------------------

if gum confirm "DO YOU WANT TO START THE UPDATE NOW?" ;then
    echo 
    echo ":: Update started."
elif [ $? -eq 130 ]; then
        exit 130
else
    echo
    echo ":: Update canceled."
    exit;
fi

**###Check package###
_isInstalled() {
   package="$1";
   case $install_platform in
	arch)
	 check="$($aur_helper -Qs --color always "${package}" | grep "local" | grep "${package} ")";
	;;
	fedora) 
	 check="$(rpm -qa|grep ${package})"
	;;
        *)
  	;;
    esac

   if [ -n "${check}" ] ; then
       echo 0; #'0' means 'true' in Bash
       return; #true
   fi;
echo 1; #'1' means 'false' in Bash
return; #false
}
##########**

# Check if platform is supported
case $install_platform in
    arch)
        aur_helper="$(cat ~/.config/ml4w/settings/aur.sh)"

        if [[ $(_isInstalled "timeshift") == "0" ]] ;then                                        
            echo
            if gum confirm "DO YOU WANT TO CREATE A SNAPSHOT?" ;then
                echo
                c=$(gum input --placeholder "Enter a comment for the snapshot...")
                sudo timeshift --create --comments "$c"
                sudo timeshift --list
                sudo grub-mkconfig -o /boot/grub/grub.cfg
                echo ":: DONE. Snapshot $c created!"
                echo
            elif [ $? -eq 130 ]; then
                echo ":: Snapshot skipped."
                exit 130
            else
                echo ":: Snapshot skipped."
            fi
            echo
        fi

        if [[ $(_isInstalled "flatpak") == "0" ]] ;then
            flatpak upgrade
        fi
    ;;
    fedora)
        sudo dnf upgrade
        if [[ $(_isInstalled "flatpak") == "0" ]] ;then
            flatpak upgrade
        fi
    ;;
    *)
        echo ":: ERROR - Platform not supported"
        echo "Press [ENTER] to close."
        read
    ;;
esac

notify-send "Update complete"
echo 
echo ":: Update complete"
echo 
echo 

echo "Press [ENTER] to close."
read

```
~/dotfiles/.config/ml4w/scripts
❯ 

The script works well on my Fedora 41.  I hope it would help you improve ML4W for Fedora users.

Regards,
               BT

**Comment by mylinuxforwork** [comment]
@PerfMonk Thank you so much. I have just pushed an update to the main branch incl. your improvements. Can you test on your side? https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/ml4w/scripts/installupdates.sh

**Comment by PerfMonk** [comment]
Sorry I won't be able to test. I have decided to keep only parts of your
config.  I wanted more control on my desktop and ml4w goes  sort of against
that .  There is too much going backward that it makes me feel that loose
control of my environment. Too much rice 😁
I will work by myself to  have a more consistent and nice theming .
I have nothing against ml4w but just find that it makes personal
configuration very complicated.

I wish you great success with ml4w 👍🏻

Regards,
         Bernard Tremblay


Le jeu. 12 déc. 2024 14:07, Stephan Raabe ***@***.***> a
écrit :
