### ISSUE TITLE
[FEATURE] Alacritty Replacement

### ISSUE THREAD

**Issue by Lavn1sh** [mylinuxforwork/dotfiles#53]
**Alacritty** is good but it **can't preview images** in programs like yazi ( a terminal file manager) by default.
So it might be better to switch alacritty with **kitty** or **wezterm**.

**Comment by mylinuxforwork** [comment]
@Lavn1sh This is already possible and described here:
https://github.com/mylinuxforwork/dotfiles/wiki/Change-the-default-terminal

I will close this issue because it’s already possible.
