### ISSUE TITLE
[BUG] RSync error

### ISSUE THREAD

**Issue by NeoFax75** [mylinuxforwork/dotfiles#531]
**Describe the bug**
Tried updating with the "Update now" button. It errors out with no error message. So try to run ./setup-arch.sh it gets to backing up the dotfiles folder and I get a rsync error.

**To Reproduce**
1. Go to 'Update now'
2. See error

rsync: [Receiver] getcwd(): No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at util1.c(1122) [Receiver=3.3.0]
:: SUCCESS - Current backup archived in /home/neofax/.ml4w-hyprland/archive/20241216154711
rsync: [Receiver] getcwd(): No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at util1.c(1122) [Receiver=3.3.0]
:: SUCCESS - Backup of /home/neofax/.gtkrc-2.0 created in /home/neofax/.ml4w-hyprland/backup
:: SUCCESS - Backup of /home/neofax/.config/fastfetch created in /home/neofax/.ml4w-hyprland/backup/config/
:: SUCCESS - Backup of /home/neofax/.config/kitty created in /home/neofax/.ml4w-hyprland/backup/config/
:: SUCCESS - Backup of /home/neofax/.config/qt6ct created in /home/neofax/.ml4w-hyprland/backup/config/
:: SUCCESS - Backup of /home/neofax/.config/rofi created in /home/neofax/.ml4w-hyprland/backup/config/
:: SUCCESS - Backup created in /home/neofax/.ml4w-hyprland/backup
rsync: [Receiver] getcwd(): No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at util1.c(1122) [Receiver=3.3.0]
:: ERROR - AN ERROR HAS OCCURED. Preparation of /home/neofax/.ml4w-hyprland/2.9.7.1RC2/ failed

**Expected behavior**
Expected to update to rolling release.

**Distribution (please complete the following information):**
 - EndeavourOS

**Comment by mylinuxforwork** [comment]
@NeoFax75 To update please run the installation command in your terminal. https://github.com/mylinuxforwork/dotfiles/wiki/Installation
