### ISSUE TITLE
[BUG] hyprshade button stopped working

### ISSUE THREAD

**Issue by XiovV** [mylinuxforwork/dotfiles#535]
**Describe the bug**
I installed package updates and ran the ml4w update script. After a reboot, I noticed the bug with the hyprshade button described below.

**To Reproduce**
1. Click on the hyprshade button to activate the blue light filter
2. Notification pops up saying "Hyprshade activated with [blank]"

**Expected behavior**
Click on the hyprshade button and turn on the blue light filter

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
@XiovV I cannot reproduce your issue. Maybe hyprshade isn't installed successfully? Can you see the folder .config/hypr/shaders/ with files in it?

**Comment by XiovV** [comment]
@mylinuxforwork seems like the issue was that hyprshade got uninstalled somehow. Installing hyprshade fixed the issue. Not sure why it got uninstalled. Thank you for your help!

**Comment by mylinuxforwork** [comment]
> @mylinuxforwork seems like the issue was that hyprshade got uninstalled somehow. Installing hyprshade fixed the issue. Not sure why it got uninstalled. Thank you for your help!

Great.
