### ISSUE TITLE
[BUG] When I update my time spec to "%H%M%S" the seconds display, but then only update at "00". 

### ISSUE THREAD

**Issue by SSYH** [mylinuxforwork/dotfiles#537]
**Describe the bug**
When I update my time spec to "%H%M%S" the seconds display, but then only update at "00". 
(time showing in waybar)

**To Reproduce**
1. Go to dotfiles setttings, and set time to anything ending in %H%M%S or %H%M%0S

**Expected behavior**
Time updates each second.

**Screenshots**
![image](https://github.com/user-attachments/assets/d747e88f-90fc-498c-a2bf-e686c251b39f)

**Distribution (please complete the following information):**
 - Arch Linux

Would like for this time to update each second, instead of just showing %H%M00 after the first display.

**Comment by mylinuxforwork** [comment]
@SSYH Unfortunately, It is not possible to update the time every second. The clock Module in waybar is made to show hours, minutes and more but I would not suggest to reload the module every second.

**Comment by SSYH** [comment]
That's too bad...
I know for some machines, this would be a heavy overhead, but gnome lets me do this... and there are circumstances where this is very useful for me. I will look for (ask for?) a different clock module... if one does this.

**Comment by SSYH** [comment]
FTR:

`"interval": 1`

in ~/.config/waybar/modules.json
will do what I want

```
  // Clock
  "clock": {
      "format": "{:%y %m%d %a %H%M%S}",
      "interval": 1,
    "on-click": "flatpak run com.ml4w.calendar",
    "timezone": "",
    "tooltip": false
  },
```
