### ISSUE TITLE
[SOLVED] Can't login after recent Hyprland upgrade.

### ISSUE THREAD

**Issue by f0-x** [mylinuxforwork/dotfiles#539]
**Describe the bug**
I enter my login details then after submitting, it redirects me back to login screen.

**To Reproduce**
1. Go to 'Login Screen'
2. Try to login
3. Directs to a black screen 
4. Redirects back to login screen.

**Expected behavior**
A successful login.

**Screenshots**
![1000041175.gif](https://github.com/user-attachments/assets/c64f9f54-794a-4254-bab7-1a21a462b9d7)

**Distribution (please complete the following information):**
 
 - EndeavourOS 

**Additional context**

**Comment by f0-x** [comment]
UPDATE: I opened tty3 and logged in successfully. But after Starting Hyprland with Hyprland command, I get

![20241221_093928.jpg](https://github.com/user-attachments/assets/3dae4f15-3479-49f1-8c8d-018a33a400cb)



```
[1] 2137 segmentation fault (core dumped) Hyprland
```

**Comment by f0-x** [comment]
UPDATE 1 :  I opened tty3 and logged in successfully. But after Starting Hyprland with Hyprland command, I get

```
[1] 2137 segmentation fault (core dumped) Hyprland
```

UPDATE 2 : I downgraded my Hyprland version from Cache by following this [guide](https://github.com/hyprwm/Hyprland/issues/4653).

**Comment by mylinuxforwork** [comment]
There are currently some issues with 0.46.2 of Hyprland and the required dependencies. You can install yay -S hyprutils-git hyprland-qtutils manually.

**Comment by f0-x** [comment]
Thank you so much. Installing those packages solved it 😊 @mylinuxforwork, but I still don't quite understand what the issue was in first place?

**Comment by mylinuxforwork** [comment]
Great. I assume that not all arch packages have been updated and aligned with 0.46.2

**Comment by Neo-29** [comment]
> Great. I assume that not all arch packages have been updated and aligned with 0.46.2

Downgrading causes an issue today
No update possible due to unsolvable dependencies problems.
Can you check if you've got the same?

**Comment by mylinuxforwork** [comment]
Just installed the latest version of Hyprland on yarch Linux KVM without any issues.

**Comment by Neo-29** [comment]
> Just installed the latest version of Hyprland on yarch Linux KVM without any issues.

So you mean last  version of hyprland is ok now?

**Comment by Neo-29** [comment]
> Just installed the latest version of Hyprland on yarch Linux KVM without any issues.

Excellent work.
All fixed and cherry on the cake, with last `hyprland`version 💪💪💪👍👍👍👍👍

**Comment by mylinuxforwork** [comment]
Great. Thanks for testing.
