### ISSUE TITLE
[BUG]  Some adjustments to proceed in script 

### ISSUE THREAD

**Issue by Neo-29** [mylinuxforwork/dotfiles#544]
**Describe the bug**

see screenshot

**To Reproduce**
1. execute script
2. see error (not impacting the installation)

![ml4issue](https://github.com/user-attachments/assets/396a5dde-ba89-4284-9096-a1988cd11693)

**Expected behavior**
no errors prompted

**Screenshots**
see above

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
Thanks. Will check.

**Comment by mylinuxforwork** [comment]
@Neo-29 Fixed in main branch.
