### ISSUE TITLE
[BUG]  waybar does not reload after theme change by ml4 settings

### ISSUE THREAD

**Issue by Neo-29** [mylinuxforwork/dotfiles#545]
**Describe the bug**
waybar doest not reload after any theme change

**To Reproduce**
1. change waybar theme with tool
2.  see screenshot
![image](https://github.com/user-attachments/assets/589be27e-6980-4d48-b39b-aa7482f4756d)

**Expected behavior**
waybar should reload

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by s4msy** [comment]
isn't this the same behavior as of #543

**Comment by Neo-29** [comment]
> isn't this the same behavior as of #543
> 
> Edit: nice Screenshot, btw.

Could be...
If the issue is waybar not reloading

**Comment by mylinuxforwork** [comment]
I will install it today again on a fresh Arch minimal setup.

**Comment by mylinuxforwork** [comment]
@s4msy Solved in rolling release.

**Comment by Neo-29** [comment]
> @s4msy Solved in rolling release.

You mean git version?

**Comment by mylinuxforwork** [comment]
> > @s4msy Solved in rolling release.
> 
> You mean git version?

Yes.

**Comment by Neo-29** [comment]
> > > @s4msy Solved in rolling release.
> > 
> > 
> > You mean git version?
> 
> Yes.

Nice! Will test that soon
