### ISSUE TITLE
[SOLVED] Wallpaper not loading. Grey screen. ctrl + super + w and shift + super + w keybindings doesnt work and the waybar doesnt appear after login, after upgrading

### ISSUE THREAD

**Issue by HectorPaulo** [mylinuxforwork/dotfiles#546]
**Describe the bug**
ctrl + super + w and shift + super + w keybindings doesnt work and the waybar doesnt appear after login, about the waybar, is possible to show it by settings but if i reboot the system the problem still there.

**Expected behavior**
i want the wallpaper and waybar to be shown, maybe there is a file i have to modify?

**Screenshots**
![screenshot_22122024_172843](https://github.com/user-attachments/assets/57b07705-e1b7-42bf-892a-e03af2db0a5e)

**Distribution: **
 - Arch Linux

**Comment by HectorPaulo** [comment]
i tried to fix it reinstalling the dotfiles but the problem persists

**Comment by SaraanshS** [comment]
You need to reload the waybar after logging in using (super+shift+b) keybind. I am having the same issues with the wallpaper and waybar. I am not sure what is the bug with wallpaper as well but hope it gets fixed soon.

**Comment by mylinuxforwork** [comment]
A user found a solution. The reason could be your Python version. Can you try

I found a temporary solution, I added the following line in my custom.conf: env = PYTHONPATH,/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH Also added this in my ZSH custom init file: export PYTHONPATH=/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH

And then reboot.

**Comment by mylinuxforwork** [comment]
> A user found a solution. The reason could be your Python version. Can you try
> 
> I found a temporary solution, I added the following line in my custom.conf: env = PYTHONPATH,/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH Also added this in my ZSH custom init file: export PYTHONPATH=/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH
> 
> And then reboot.

I have just updated all packages on my Arch system with yay. There was a massive python update. Have now the same issue on my system.

**Comment by mylinuxforwork** [comment]
Adding this line to the custom.conf fixed the issue on my side:

`env = PYTHONPATH,/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH `

The latest Arch updates installed Python 3.13. Waypaper requires 3.12 for know. Adding the Path to Python 3.12 brings waypaer back.

**Comment by Anders1974** [comment]
After updating python, you will need to rebuild the following packages: python-screeninfo, python-imageio, waypaper

**Comment by mylinuxforwork** [comment]
> After updating python, you will need to rebuild the following packages: python-screeninfo, python-imageio, waypaper

Can you share the rebuild command?

**Comment by Anders1974** [comment]
> > After updating python, you will need to rebuild the following packages: python-screeninfo, python-imageio, waypaper
> 
> Can you share the rebuild command?

Yesterday I decided by experience.  yay -s python-screeninfo python-imageio waypaper.  And everything worked

**Comment by SaraanshS** [comment]
> > > After updating python, you will need to rebuild the following packages: python-screeninfo, python-imageio, waypaper
> > 
> > 
> > Can you share the rebuild command?
> 
> Yesterday I decided by experience. yay -s python-screeninfo python-imageio waypaper. And exit . Everything worked


This worked for me aswell. Rebuilding and installing these helped!

**Comment by Neo-29** [comment]
However, This doesn't fix waybar not reloading

**Comment by Tyrn** [comment]
Manjaro Linux:
```
~> python -V
Python 3.12.7
```
Python 3.12, as required. The same set of problems.

**Comment by HectorPaulo** [comment]
i changed my version of python but nothing happened, so i made a script to show the waybar and wallpaper from the wallpapers directory, i made it to change the wallpaper each hour (it changes the color palette too) 'cause i like that it change at a specific time. any other thing like change the waypaper or make it work with keybindings i didn't even try, maybe when i have more time. i changed hyprland.conf (here is where the script will be called), launch.sh, themeswitcher.sh and the script is change_wallpaper.sh. i dont know if what i made works for you but i found it interesting.

![image_2024-12-23_111125163](https://github.com/user-attachments/assets/e0fbbc99-b908-4271-b6c3-97ad81113dff)

![image_2024-12-23_112339336](https://github.com/user-attachments/assets/4f66d583-4466-4ecb-bdd1-9dc76a15022e)

![image_2024-12-23_112401724](https://github.com/user-attachments/assets/c264f06a-28ca-458a-85ac-1fa1fc7c7c0b)

**change_wallpaper.sh**
#!/bin/bash

WALLPAPER_DIR="$HOME/wallpaper"

# Seleccionar un fondo de pantalla al azar
while true; do
    WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
    echo "Changing wallpaper to $WALLPAPER"
    swaybg -i "$WALLPAPER" -m fill &
    
    # Generar paleta de colores con pywal
    wal -i "$WALLPAPER" -q
    
    # Cambiar el tema de Waybar sin mostrar el menú
    echo "Changing Waybar theme"
    ~/.config/waybar/launch.sh
    
    sleep 3600
done

**hyprland.conf**
exec-once = ~/.config/hypr/change_wallpaper.sh # <-- only this line at the end

**themeswitcher.sh**
#!/bin/bash
#  _____ _                                       _ _       _                
# |_   _| |__   ___ _ __ ___   ___  _____      _(_) |_ ___| |__   ___ _ __  
#   | | | '_ \ / _ \ '_ ` _ \ / _ \/ __\ \ /\ / / | __/ __| '_ \ / _ \ '__| 
#   | | | | | |  __/ | | | | |  __/\__ \\ V  V /| | || (__| | | |  __/ |    
#   |_| |_| |_|\___|_| |_| |_|\___||___/ \_/\_/ |_|\__\___|_| |_|\___|_|    
#                                                                           
# by Stephan Raabe (2024) 
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Default theme folder
# ----------------------------------------------------- 
themes_path="$HOME/.config/waybar/themes"

# ----------------------------------------------------- 
# Initialize arrays
# ----------------------------------------------------- 
listThemes=""
listNames=""
listNames2=""

# ----------------------------------------------------- 
# Read theme folder
# -----------------------------------------------------
sleep 0.1
options=$(find $themes_path -maxdepth 2 -type d)
for value in $options; do
    if [ ! $value == "$HOME/.config/waybar/themes/assets" ] && [ ! $value == "$themes_path" ]; then
        if [ $(find $value -maxdepth 1 -type d | wc -l) = 1 ]; then
            result=$(echo $value | sed "s#$HOME/.config/waybar/themes/#/#g")
            IFS='/' read -ra arrThemes <<< "$result"
            listThemes[${#listThemes[@]}]="/${arrThemes[1]};$result"
            if [ -f $themes_path$result/config.sh ]; then
                source $themes_path$result/config.sh
                listNames+="$theme_name\n"
                listNames2+="$theme_name~"
            else
                listNames+="/${arrThemes[1]};$result\n"
                listNames2+="/${arrThemes[1]};$result~"
            fi
        fi
    fi
done

# ----------------------------------------------------- 
# Show rofi dialog
# ----------------------------------------------------- 
if [ "$1" == "--select" ]; then
    listNames=${listNames::-2}
    choice=$(echo -e "$listNames" | rofi -dmenu -replace -i -config ~/.config/rofi/config-themes.rasi -no-show-icons -width 30 -p "Themes" -format i)
    IFS="~"
    input=$listNames2
    read -ra array <<< "$input"
# ----------------------------------------------------- 
# Set new theme by writing the theme information to ~/.config/ml4w/settings/waybar-theme.sh
# ----------------------------------------------------- 
    if [ "$choice" ]; then
        echo "Loading waybar theme..."
        echo "${listThemes[$choice+1]}" > ~/.config/ml4w/settings/waybar-theme.sh
        ~/.config/waybar/launch.sh
        notify-send "Waybar Theme changed" "to ${array[$choice]}"
    fi
else
    # Recargar Waybar con el tema actual
    ~/.config/waybar/launch.sh
fi

**launch.sh**
#!/bin/bash
#  ____  _             _    __        __          _                 
# / ___|| |_ __ _ _ __| |_  \ \      / /_ _ _   _| |__   __ _ _ __  
# \___ \| __/ _` | '__| __|  \ \ /\ / / _` | | | | '_ \ / _` | '__| 
#  ___) | || (_| | |  | |_    \ V  V / (_| | |_| | |_) | (_| | |    
# |____/ \__\__,_|_|   \__|    \_/\_/ \__,_|\__, |_.__/ \__,_|_|    
#                                           |___/                   
# by Stephan Raabe (2023) 
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Quit all running waybar instances
# ----------------------------------------------------- 
killall waybar
pkill waybar
sleep 0.5

# ----------------------------------------------------- 
# Reload AGS
# -----------------------------------------------------

echo ":: Reload ags"
ags quit &
sleep 0.1
ags run &

# ----------------------------------------------------- 
# Default theme: /THEMEFOLDER;/VARIATION
# ----------------------------------------------------- 
themestyle="/ml4w;/ml4w/light"

# ----------------------------------------------------- 
# Get current theme information from ~/.config/ml4w/settings/waybar-theme.sh
# ----------------------------------------------------- 
if [ -f ~/.config/ml4w/settings/waybar-theme.sh ]; then
    themestyle=$(cat ~/.config/ml4w/settings/waybar-theme.sh)
else
    touch ~/.config/ml4w/settings/waybar-theme.sh
    echo "$themestyle" > ~/.config/ml4w/settings/waybar-theme.sh
fi

IFS=';' read -ra arrThemes <<< "$themestyle"
echo ":: Theme: ${arrThemes[0]}"

if [ ! -f ~/.config/waybar/themes${arrThemes[1]}/style.css ]; then
    themestyle="/ml4w;/ml4w/light"
fi

# ----------------------------------------------------- 
# Loading the configuration
# ----------------------------------------------------- 
config_file="config"
style_file="style.css"

# Standard files can be overwritten with an existing config-custom or style-custom.css
if [ -f ~/.config/waybar/themes${arrThemes[0]}/config-custom ] ;then
    config_file="config-custom"
fi
if [ -f ~/.config/waybar/themes${arrThemes[1]}/style-custom.css ] ;then
    style_file="style-custom.css"
fi

# Check if waybar-disabled file exists
if [ ! -f $HOME/.cache/waybar-disabled ] ;then 
    waybar -c ~/.config/waybar/themes${arrThemes[0]}/$config_file -s ~/.config/waybar/themes${arrThemes[1]}/$style_file &
fi

**I pasted the codes here 'cause i couldn't attached 'em**

**Comment by HectorPaulo** [comment]
i forgot, the script works with swaybg
