### ISSUE TITLE
[BUG] Power Menu View mismatch in ml4w-hyprland 2.9.7.1

### ISSUE THREAD

**Issue by Koushikg88** [mylinuxforwork/dotfiles#549]
**Describe the bug**

In new ml4w-hyprland 2.9.7.1
If power button on waybar is pressed, the power menu is showing like below:
![screenshot_23122024_171103](https://github.com/user-attachments/assets/6392d224-da6f-4c8f-a12c-b8de1eb0a917)

But if I press mod+ctrl+q, the power menu is coming like below:
![screenshot_23122024_171120](https://github.com/user-attachments/assets/56bacc5a-a22c-42e1-b07d-6d8c56068b55)

**To Reproduce**
1. Press power button on waybar
2. Check the power menu
3. Press mod+ctrl+q
4. Again check the power menu

**Expected behavior**
The views should be same 

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
Thanks for testing. Will fix.

**Comment by mylinuxforwork** [comment]
@Koushikg88 Updated the main branch with the fix.
