### ISSUE TITLE
[BUG] Mission Center windowrules issues

### ISSUE THREAD

**Issue by dianaw353** [mylinuxforwork/dotfiles#55]
**Describe the bug**
Mission Center preferences window displays behind the main window

**To Reproduce**
1. Open Mission Center
2. Click hamburger menu > preferences

**Expected behavior**
Mission Center preferences window should be displayed on (user preference: top of the main window or in the center of the screen)

**Screenshots**

**Distribution (please complete the following information):**
- All

**Additional context**
A fix i found is to change the windowrules title to class so it captures all missioncenter windows. Here is a example on how to achieve that https://github.com/dianaw353/dotfiles/blob/main/roles/hyprland/files/hypr/config/windowrules/default.conf

**Comment by mylinuxforwork** [comment]
@dianaw353 Thanks for reporting the issue. I will check.

**Comment by mylinuxforwork** [comment]
@dianaw353 Fixed on main branch. Thank you.
