### ISSUE TITLE
[BUG] ML4W Modern Light theme: no tray

### ISSUE THREAD

**Issue by Tyrn** [mylinuxforwork/dotfiles#551]
**Describe the bug**
"Close into tray" apps just vanish.

**To Reproduce**
Open any app, like Qbittorrent, configured to stay in tray if closed, then close it. It vanishes from sight. System monitor shows it running, as expected.

NB It's quite possible that there's no bug, I just don't know where to look.

**Comment by Tyrn** [comment]
Looks like you have to relogin after changing the Status Bar Theme

**Comment by mylinuxforwork** [comment]
![image](https://github.com/user-attachments/assets/595c79b3-d334-4460-a979-7bfbe0af3608)

Tray is working on my side.

**Comment by Tyrn** [comment]
On my, too. Just after Super+Shift+B it works as in the description. Requires relogin to work normally.
