### ISSUE TITLE
[BUG] Hyprland does not lock anymore before suspend

### ISSUE THREAD

**Issue by jabruniessner** [mylinuxforwork/dotfiles#552]
Just today I reinstalled ml4w after some things broke on my system. Unfortunately the my system is not locking before suspend anymore.

**Comment by Tyrn** [comment]
Check `.config/hypr/hypridle.conf`. I wanted the opposite behavior, *not* to lock before suspend. I had to comment out the relevant line:
```
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    # before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}
```

**Comment by jabruniessner** [comment]
That does not seem to be the issue.

The line is not commented out

But thanks for the help

**Comment by jabruniessner** [comment]
Just in case this helps:

When I simply type 

loginctl lock-session 

into the terminal.

Nothing happens either

**Comment by jabruniessner** [comment]
It turns out a recent system upgrade broke a hypridle dependency. It seems to have nothing to do with the dotfiles.

Closing!
