### ISSUE TITLE
[BUG] The Settings (?) Module missing from Waybar

### ISSUE THREAD

**Issue by Tyrn** [mylinuxforwork/dotfiles#555]
**Describe the bug**
This may not be a bug. Likewise, I'm not sure this is the Settings Module :)

I mean the cogwheel icon to the left. At some point, it vanished. What do I have to do to trace it?

**Comment by mylinuxforwork** [comment]
Yes. I have removed it from way at and moved it completely to the sidebar. Was a required change due to stability reasons. 

Hope it's Okay for you.
