### ISSUE TITLE
[BUG] Waybar not showing up on boot and appear when Show Waybar option is untoggled

### ISSUE THREAD

**Issue by GdcDot** [mylinuxforwork/dotfiles#558]
**Describe the bug**
On every boot waybar is not showing up, but when I untoggle the _Show Waybar_ option in the settings app, Waybar activates.

**To Reproduce**
1. Boot Linux
2. Open settings app
3. Untoggle Show Waybar
4. Waybar is displayed

**Expected behavior**
Waybar is activated when loging in.

**Screenshots**
![NoWaybar](https://github.com/user-attachments/assets/90d9d37a-c5d8-4758-8a2b-cf82965529f7)
![Waybar](https://github.com/user-attachments/assets/f1bbdce3-ac2d-4953-b901-a5c866822272)

**Distribution (please complete the following information):**
 - CachyOs

**Comment by mylinuxforwork** [comment]
@GdcDot Which version of the dotfiles have you installed?

**Comment by mrjxtr** [comment]
@GdcDot I think I had this issue once, and it was even before updating to the current version, there might be a slight delay when you first toggle "show waybar" or maybe it does not apply the change directly at first even the the GUI already updated. So, when it shows that it's off, it is actually on, and if it's on, it is actually off.

What I did to resolve this is I just clicked the toggle in rapid succession until it corrected itself and never touched it again 🤣

**Comment by mylinuxforwork** [comment]
@GdcDot Especially with an initial installation, a second reboot can help and could fix the waybar issue.

**Comment by GdcDot** [comment]
> @GdcDot Which version of the dotfiles have you installed?

I'm on 2.9.7.2, but for whatever reasons it works now.

**Comment by mizma** [comment]
I think I have the same issue after updating to 2.9.7.2 and still have the issue on 2.9.7.3 right now.
I turned on debug log for hyprland and I can see that the ~/.config/hypr/scripts/xdg.sh is being launched but doesn't seem to be launching waybar.  

after launching, I can run ~/.config/waybar/launch.sh manually and that will bring up waybar without touching the toggle.

I'm on EndeavourOS

**Comment by JohRest** [comment]
I have the same issue. Haven't tried to use the toggle yet...

**Comment by JohRest** [comment]
I tried the toggle... it brings up waybar. But that does not survive a reboot... after rebooting the system, waybar is again not started...

**Comment by mrjxtr** [comment]
My theory is that this is probably a mismatch between the toggle state of the GUI and the config file.

Because there are times where I clicked the area around the button and not the button itself but the changes applied but the toggle stayed the same. This could mean that the config file already changed but on the GUI, since you technically did not click the toggle button, it did not change.

What do you think? @mylinuxforwork

**Comment by edzhabs** [comment]
I also experienced this after running the update. untoggling it shows my waybar

**Comment by mylinuxforwork** [comment]
I will check the toggle. Keep you posted.

**Comment by mylinuxforwork** [comment]
@mizma @JohRest I can confirm the issue with the toggle from the settings app. I will work on it.
