### ISSUE TITLE
[BUG] Settings Waybar Module icon missing after update

### ISSUE THREAD

**Issue by mrjxtr** [mylinuxforwork/dotfiles#565]
**Describe the bug**
The settings module for Waybar fails to show after update. 

What I tried:
Toggling on and off in settings
Changing Themes (settings does not show in all themes and is broken in starter theme)
Reboot and Shutdown PC
Restarting Waybar

**To Reproduce**
1. Full System update
2. Run `ml4w-hyprland-setup`

**Expected behavior**
Settings module to show on Waybar

**Screenshots**

![image](https://github.com/user-attachments/assets/5e89b4f5-9e44-4c40-a395-4918bc0ccd93)

**Distribution (please complete the following information):**
 - Arch Linux
 -ML4W v.2.9.7.3
 
 # Update
 
 I was able to add modules manually here `/home/mrjxtr/dotfiles/.config/waybar` by editing the config file of the specific theme I want to use.
 
 in my case `/home/mrjxtr/dotfiles/.config/waybar/themes/ml4w-modern/white/config`
 
 Added:
 ```
     // Modules Left
    "modules-left": [
        "group/settings",
    ],
```

**Comment by mylinuxforwork** [comment]
I have removed the settings icon completely from waybar due to stability reasons. You can access the features from the sidebar. 

But I forgot to remove the toggle from the settings app.

**Comment by mrjxtr** [comment]
Oh, I see... so that was intentional... I kinda like the `group/settings` would the stability issues affect me a lot if I keep it on?

**Comment by mylinuxforwork** [comment]
No. There are just minor side effects. I can bring it back again but hide it by default.

**Comment by mrjxtr** [comment]
> No. There are just minor side effects. I can bring it back again but hide it by default.

I think that would be the best option 💯
