### ISSUE TITLE
[BUG] Python virtualenv has poor dependency isolation

### ISSUE THREAD

**Issue by nadecancode** [mylinuxforwork/dotfiles#566]
**Describe the bug**
Due to https://github.com/mylinuxforwork/dotfiles/blob/d2c7783c53a8d6ca442390bf487f4814beae1e81/share/dotfiles/.config/hypr/conf/ml4w.conf#L124, all packages installed in the system will also load in virtualenv.

**To Reproduce**
1. Install virtualenv
2. Install any package while having virtualenv activate
3. Boom (e.g. numpy)

**Expected behavior**
Virtualenv dependencies should be isolated

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
Problem can be solved by manually unsetting `PYTHONPATH` but I wonder why is that env set in the first place since by default that's where the system should look for packages anyways.

**Comment by mylinuxforwork** [comment]
@nadecancode That was a quickfix as Python has been updated recently. How to fix it? Can this be removed now?

and what’s currently not working on your system if this line is still in?

**Comment by nadecancode** [comment]
> @nadecancode That was a quickfix as Python has been updated recently. How to fix it? Can this be removed now?
> 
> and what’s currently not working on your system if this line is still in?

See the issue I’ve referenced here. Basically numpy can’t be imported at all.

**Comment by mylinuxforwork** [comment]
> > @nadecancode That was a quickfix as Python has been updated recently. How to fix it? Can this be removed now?
> > and what’s currently not working on your system if this line is still in?
> 
> See the issue I’ve referenced here. Basically numpy can’t be imported at all.
> 
> If `PYTHONPATH` env change needs to be kept from Hyprland init then it's better to unset `PYTHONPATH` when the shell initializes (so relevant packages will still see the PYTHONPATH while python virtualenv will no longer get confused) Although I believe this (the PYTHONPATH change) can be removed already.

Will test on my systems as well.

**Comment by Onyoursix** [comment]
Thanks for finding this! I was going INSANE trying to figure out why my virtual environments were being overwritten by system packages. 

I commented out that line in the ml4w.conf and that seems to have fixed my issue!

**Comment by nadecancode** [comment]
> Thanks for finding this! I was going INSANE trying to figure out why my virtual environments were being overwritten by system packages.
> 
> I commented out that line in the ml4w.conf and that seems to have fixed my issue!

No problem, it took me couple hours to debug as well. I recommend unsetting that env in zshrc or whatever init you have though since until @mylinuxforwork confirms this env is no longer needed, it is better to let hyprland keep this env change

**Comment by mrjxtr** [comment]
I'm also have a similar issue with Conda... I was looking everywhere for a fix and found nothing so I used time shift to a time where i have not updated to the new ml4w update and checked if the bug was there, ad it was not, everything was fine..

The i updated everything except for ml4w, and still no issues... I update the ml4w after all than and then ran `conda activate` and there it was... When running a project with nympy it for some reason uses the system python's numpy and there is a problem with `openssl` as well whenever activating conds.

**Comment by mylinuxforwork** [comment]
@nadecancode @Onyoursix Just pushed an update to the main branch (rolling release) for 2.9.7.4. The env configuration for python is disabled again. Thanks for testing.

**Comment by mrjxtr** [comment]
> @nadecancode @Onyoursix Just pushed an update to the main branch (rolling release) for 2.9.7.4. The env configuration for python is disabled again. Thanks for testing.

Thanks for this 🚀

### I would also like to take not for those who are having a similar issue but with Conda... this also fixed my issue.

I did the manual edit of `/dotfiles/.config/hypr/conf/ml4w.conf` removing `PYTHONPATH` line and I also ran `unset PYTHONPATH` on my shell.
after a reboot, It fixed my Conda issue... 

But updating to the main branch (rolling release) for 2.9.7.4. should also work

**Comment by wicaksonoleksono** [comment]
@mrjxtr 
Thanks for the rep, i can only temporarily ```unset PYTHONPATH```, but then after i opened new session of termiunal the issue presist.

**Comment by nadecancode** [comment]
> @mrjxtr Thanks for the rep, i can only temporarily `unset PYTHONPATH`, but then after i opened new session of termiunal the issue presist.

Either upgrade to the latest dotfiles ver or add unset in your zsh / bash init

**Comment by mrjxtr** [comment]
> @mrjxtr 
> Thanks for the rep, i can only temporarily ```unset PYTHONPATH```, but then after i opened new session of termiunal the issue presist.   

@wicaksonoleksono did you delete the PYTHONPATH line in this file? `~/dotfiles/.config/hypr/conf/ml4w.conf`

You need to delete this line and reboot.

**Comment by wicaksonoleksono** [comment]
> > @mrjxtr Thanks for the rep, i can only temporarily `unset PYTHONPATH`, but then after i opened new session of terminal the issue presist.
> 
> Either upgrade to the latest dotfiles ver or add unset in your zsh / bash init

i unset this in my zshrc and upgrade it to the rolling release, but the issue still presist. i tried it using pipenv and conda it also still do that when i run depedencies such as numpy. Hmm this is weird  . it still uses 2x.xx version of numpy for some reason. This can be replicated if you run your app under code / vscode. 
```
Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there
```

**Comment by mrjxtr** [comment]
Have you deleted it from the `~/dotfiles/.config/hypr/conf/ml4w.conf`?

**Comment by wicaksonoleksono** [comment]
> Have you deleted it from the `~/dotfiles/.config/hypr/conf/ml4w.conf`?

Yes i did, and i rebooted it

**Comment by mrjxtr** [comment]
> > Have you deleted it from the `~/dotfiles/.config/hypr/conf/ml4w.conf`?
> 
> Yes i did, and i rebooted it 

Then I would suggest you roll back your system to a previous backup... If you've been using timeshift, go back to a backup before updating and try to update everything again but this time making sure to update to the latest rolling release.

**Comment by wicaksonoleksono** [comment]
It seems the root cause of the issue lies in the Wayland wallpaper manager (waypaper), which depends on python-imageio. This dependency is pulling in a system-wide installation of NumPy (v2.x.x), and that version is conflicting with the Conda environment’s NumPy installation. Since python-imageio relies on the system's global Python, it forces the system's NumPy into the execution path, breaking the isolation provided by Conda. the November version doesnt have python-imageio installed.

**Comment by wicaksonoleksono** [comment]
@mrjxtr @nadecancode,
It worked! I had accidentally set the PYTHONPATH directly in my hyprland.conf. Thank you so much; that repository was extremely helpful.

**Comment by wicaksonoleksono** [comment]
It worked! I had accidentally set the PYTHONPATH directly in my hyprland.conf. Thank you so much; that rep was extremely helpful.
