### ISSUE TITLE
[BUG] Settings button not working when changing Waybar to default's theme

### ISSUE THREAD

**Issue by N-Dayz** [mylinuxforwork/dotfiles#571]
**Describe the bug**
Changed the Waybar to its default theme and the green icon (ML4W) stop working because it couldn't find ML4W Dotfiles AppImage. I was able to go back to another working Waybar theme by using rofi and opening WL4W Welcome App directly.

**Screenshots**

![waybar_bug](https://github.com/user-attachments/assets/f29af33f-16dd-4335-9aef-f61db3745e76)

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mylinuxforwork** [comment]
Thanks for testing. Will fix it.

**Comment by mylinuxforwork** [comment]
@N-Dayz Fixed on main branch. You can install the rolling release with yay -S ml4w-hyprland-git and rebuild the package.
