### ISSUE TITLE
[BUG] Unable to change SSDM wallpaper through ML4WW settings

### ISSUE THREAD

**Issue by N-Dayz** [mylinuxforwork/dotfiles#572]
**Describe the bug**

I had a working **ssdm** before installing ML4W, I tried to change the wallpaper by using the settings and the bellow error appeared. I am using the latest version: v2.9.7.3

**Screenshots**

![image](https://github.com/user-attachments/assets/c7fb9556-1497-4304-9e36-5aa05b308c40)

**Distribution (please complete the following information):**
 - Arch Linux

I am new to github + open source, feedback is always welcome.

**Comment by mylinuxforwork** [comment]
Which theme are you using? The Wallpaper change works only with the sequoia theme.

**Comment by N-Dayz** [comment]
I can confirm the issue was on my end. I had a different sddm.conf. Maybe the rule of thumb should be that we shouldn’t attempt to change the wallpaper through ML4W if the SDDM configuration is either different or altered. Or perhaps there could be an option to force a sddm.conf copy from backup? I think it depends on how much we, as a community, want newcomers to rely on the GUI versus encouraging them to read the manual and troubleshoot their own configs, etc.

You can probably close this.

**Comment by mylinuxforwork** [comment]
Yes. A backup makes sense. Will check.
