### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by i0day** [mylinuxforwork/dotfiles#574]
**Describe the bug**
ml4w-sidebar
error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: window not found

when I run ml4w-sidebar I got above error message. I am on 2.9.7.3 stable

I was working few months ago on the old version.

**Distribution (please complete the following information):**
 - Artix linux

**Comment by mylinuxforwork** [comment]
Can you check your ags version? It requires 2.0.x

**Comment by i0day** [comment]
ags -v
ags version 2.0.1

**Comment by i0day** [comment]
I updated the ags to version 2.2.1 still have the same problem

**Comment by mylinuxforwork** [comment]
Maybe and issue with Artix Linux?

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/issues/575
