### ISSUE TITLE
[FEATURE] Add nwg-dock as an option

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#58]
A dock could improve the usability of the ML4W Dotfiles installation by giving easy access to often used and running apps. 

Implementation based on
https://github.com/nwg-piotr/nwg-dock-hyprland

Requires modification in the stylesheet.

Hide the dock in Fullscreen mode.

**Comment by dwilliam62** [comment]
Suggest you make it optional.   Adding a dock sort of defeats the design of WMs.  To get away from using mouse to start programs making it more of a DE.  The sooner a new user gets away from mouse centric use the better a WM will improve their workflow.

**Comment by mylinuxforwork** [comment]
> Suggest you make it optional. Adding a dock sort of defeats the design of WMs. To get away from using mouse to start programs making it more of a DE. The sooner a new user gets away from mouse centric use the better a WM will improve their workflow.

Will be definitely optional.

**Comment by valtoree** [comment]
Hi love your work. I would love a dock pls pls 🙏

**Comment by dwilliam62** [comment]
The package is available in the various repos,  and you can install it
yourself anytime.

 Regards,
Don

**Comment by mylinuxforwork** [comment]
@valtoree 
you can install it with 

```
yay -S nwg-dock-hyprland
```

Then add 

```
exec-once = nwg-dock-hyprland -x -i 40 -mb 10
```

to .config/hypr/conf/custom.conf

I am currently testing it.

**Comment by valtoree** [comment]
Looks really good on new release. Well done @mylinuxforwork

**Comment by mylinuxforwork** [comment]
Thanks for your feedback.
