### ISSUE TITLE
[FEATURE] Add flatpak to packages update script - installupdates.sh

### ISSUE THREAD

**Issue by Pryka** [mylinuxforwork/dotfiles#62]
Now that we have Flatpak support in dotfiles it would be nice to include it in updates script also - **installupdates.sh**

Something like:
```
if [[ $(_isInstalledYay "flatpak") == "0" ]] ;then
        flatpak upgrade
fi
```
Should be enough?

**Comment by mylinuxforwork** [comment]
@Pryka That makes absolutely sense. Thank you very much for reporting this issue.

**Comment by mylinuxforwork** [comment]
@Pryka Already pushed to the main branch. Thank you.
