### ISSUE TITLE
[FEATURE] SDL_VIDEODRIVER=wayland - is not ideal for gamers.

### ISSUE THREAD

**Issue by Pryka** [mylinuxforwork/dotfiles#63]
Some games are using old SDL version that is compiled without Wayland support. That means they will not likely want to run - crash on startup - if **SDL_VIDEODRIVER** is set to Wayland.

There is a simple solution to that, add **SDL_VIDEODRIVER=x11** in Steam game properties, but that solution will only work for Steam games and you can set this on per game basis which is very nice.

The easy solution for other games is to not set **SDL_VIDEODRIVER** globally at all and let SDL decide what driver to use - x11 or wayland. - remove **env = SDL_VIDEODRIVER,wayland** from **ml4w.conf** - I'm not sure how leaving it blank works, so there is a change all SDL stuff will run against x11 which is definitely not expected outcome.

Setting up **SDL_VIDEODRIVER** system wide to x11 is also not ideal cause it will just force everything to run against SDL without wayland even if it is supported.

I think that ideal solution would be to add ability in game-mode to run it with **SDL_VIDEODRIVER** set to x11 if game fails to start with **env = SDL_VIDEODRIVER,wayland** some kind of switch/toggle.

This is convoluted issue and honestly I don't know if anything should be done to "fix" it now... I just wanted to state it. For now i just export manually  SDL_VIDEODRIVER with x11 if some game fails to run and revert it back to wayland after gaming session with affected game.

**Comment by mylinuxforwork** [comment]
Thanks for bringing this up and your super detailed explaination. Will think about it how to implement this switch.

**Comment by mylinuxforwork** [comment]
Just added a new wiki page to cover this topic. And I have pushed an update to the main branch.
https://github.com/mylinuxforwork/dotfiles/wiki/Switch-SDL-Videodriver-between-Wayland-and-x11
