### ISSUE TITLE
[BUG] got error pywal after reboot installation 

### ISSUE THREAD

**Issue by n2ng-dev** [mylinuxforwork/dotfiles#66]
I use dotfiles rolling-release
After installation and reboot in home screen got error an error (see screenshot)
And no wallpaper show
Rofi apps launcher got error theme

Sorry for my bad English 

Thankyou

![20240727_002148.jpg](https://github.com/user-attachments/assets/fba821fa-be96-4c2b-bb39-358dc6f24fdd)

![20240727_002333.jpg](https://github.com/user-attachments/assets/eb07cb75-cda8-41d4-ba16-2ff943dc46a2)

**Comment by mylinuxforwork** [comment]
@n2ng-dev Can you try to install pywal again with

yay -S python-pywal

**Comment by n2ng-dev** [comment]
I have done it.
But still got same error

![20240727_014702.jpg](https://github.com/user-attachments/assets/a64750fb-8612-46d0-9af6-b8e8e5515489)

**Comment by mylinuxforwork** [comment]
Let me install the dotfiles again from scratch on EndeavourOS.

**Comment by mylinuxforwork** [comment]
@n2ng-dev I have just installed the dotfiles on EndeavourOS and minimal Arch again. No issues with pywal (But with eww https://github.com/mylinuxforwork/dotfiles/issues/68)

**Comment by n2ng-dev** [comment]
Can you explain with minimal arch ? 
Im using Arch Linux latest iso
Still same error eww & pywal

**Comment by mylinuxforwork** [comment]
Ok. Thanks for testing. I have an Arch Linux installed based on an older Arch ISO but updated with the latest packages. Will install the latest Arch ISO and try again.

**Comment by mylinuxforwork** [comment]
@n2ng-dev Can you try 

`yay -S pywal-git`

**Comment by n2ng-dev** [comment]
Error like this


![IMG_20240727_180134_058.jpg](https://github.com/user-attachments/assets/db523f12-79cd-43d2-89af-61a0b352b33f)

![IMG_20240727_180133_723.jpg](https://github.com/user-attachments/assets/800adfbb-5dc0-464d-be52-ea52834513b9)

**Comment by n2ng-dev** [comment]
Conflig with python-pywal

**Comment by mylinuxforwork** [comment]
But that looks like pywal could be installed. What happens if you enter wal in a terminal?

**Comment by mylinuxforwork** [comment]
@n2ng-dev Installer installed python-pywal without any issues on latest Arch ISO with minimal installation.

![image](https://github.com/user-attachments/assets/9f841dab-1b38-434e-83a6-e6c372926f61)

**Comment by n2ng-dev** [comment]
![IMG_20240727_184538_780.jpg](https://github.com/user-attachments/assets/7bd5b85e-bd93-431d-afec-002a0831f7f1)

Like this

**Comment by mylinuxforwork** [comment]
It is working.

**Comment by n2ng-dev** [comment]
wal -i pathtoimage. Error No valid image file


![Uploading 20240727_205853.jpg …]()

**Comment by mylinuxforwork** [comment]
Sure. Please replace pathtoinage with a path to a wallpaper on your system.

**Comment by n2ng-dev** [comment]
Yeah sorry for my bad

Works perfectly 

But now Sidebar won't open

**Comment by mylinuxforwork** [comment]
Yes. There is currently an issue with eww. I have already opened an issue.
