### ISSUE TITLE
[BUG] unable to move or resize windows using mouse.

### ISSUE THREAD

**Issue by jasonwitty** [mylinuxforwork/dotfiles#67]
**Describe the bug**

Unable to move or resize windows using mouse despite this feature working as expected before running installation script. keybindings appear to be configured as expected and as they were configured with the previous garuda hypr installation. all other main mod functions appear to be working. What could be causing a conflict here?

current:

```
bindm = $mainMod, mouse:272, movewindow # Move window with the mouse
bindm = $mainMod, mouse:273, resizewindow # Resize window with the mouse
```

previously:

```
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
```

**To Reproduce**

hold mod key over window, use left or right mouse button to resize or move windows. nothing occurs.

**Expected behavior**

windows can be moved or resized.

**Distribution (please complete the following information):**

garuda / hyprland

**Additional context**

nvidia GPU, proprietary driver, glorious model 0 mouse, intel 12900 cpu
no modifications made to the default dotfiles after install other than monitor settings and trying some different themes.

**Comment by mylinuxforwork** [comment]
@jasonwitty Can you check that resize_on_border = true is set? See the configuration of https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/hypr/conf/windows/default.conf below.

```
# ----------------------------------------------------- 
# General window layout and colors
# name: "Default"
# ----------------------------------------------------- 

general {
    gaps_in = 10
    gaps_out = 14
    border_size = 3
    col.active_border = $color11
    col.inactive_border = rgba(ffffffff)
    layout = dwindle
    resize_on_border = true
}
```

**Comment by mylinuxforwork** [comment]
@jasonwitty Maybe there is a special Garuda setting overwriting the Dotfiles configuration?

**Comment by jasonwitty** [comment]
i am not sure. after running garuda-update and restarting one additional time (i had restarted once after install already), resizing, swapping windows and moving floating windows with the mod key now appears to be working as expected.

**Comment by jasonwitty** [comment]
i think i figured something out here, garuda comes with nextcloud setup and when you open the dolpin file manager it loads a popup for you to log into your account. occasionally this pop up appears normally as a floating window
