### ISSUE TITLE
[BUG] i have an issue whit my audio, i have a laptop huawei d14

### ISSUE THREAD

**Issue by eversson007** [mylinuxforwork/dotfiles#72]
I have problems with the audio on my laptop, huawei d14, I have arch linux with hyprland, in the audio control you can see that the output device works but there is no audio even with my audiophones.

**Comment by mylinuxforwork** [comment]
@eversson007 What happens if you click on the Volume Module in Waybar?

![image](https://github.com/user-attachments/assets/2c03976e-64b8-44b7-a741-acf37f3e9143)

**Comment by eversson007** [comment]
> @eversson007 What happens if you click on the Volume Module in Waybar?
> 
> ![image](https://github.com/user-attachments/assets/2c03976e-64b8-44b7-a741-acf37f3e9143)
> 
> 

The normal menu appears and in pavucontrol it looks like the audio will work. That's from Firefox and sometimes the videos can't be played either. 🥲

**Comment by eversson007** [comment]
> @eversson007 What happens if you click on the Volume Module in Waybar?
> 
> ![image](https://github.com/user-attachments/assets/2c03976e-64b8-44b7-a741-acf37f3e9143)
> 
> 

The normal menu appears and in pavucontrol it looks like the audio will work. That's from Firefox and sometimes the videos can't be played either. 🥲

**Comment by mylinuxforwork** [comment]
Do you have another Desktop Environment installed? Does the sound works there?
