### ISSUE TITLE
[BUG] Accessing Mission Center from Way Bar occasionally does not portray what it used to.

### ISSUE THREAD

**Issue by soulstirrings** [mylinuxforwork/dotfiles#73]
**Description of the bug** 

> Accessing Mission Center from Way Bar occasionally does not portray what it used to.

**Expected behavior** 

> It should open Mission Center directly and portray the graphs properly.

**Distribution**
 
>  Arch Linux
 
**Additional context** 

>  It is happening occasionally. One can not predict it. My assumption is doing memory consumption tasks. 

@hasecilu @mylinuxforwork @jamesrahhh Honorably, I want the developers to notice this issue and fix it.

**Screenshot**

[screenshot_28072024_182402.zip](https://github.com/user-attachments/files/16404325/screenshot_28072024_182402.zip)

**Comment by mylinuxforwork** [comment]
Thanks for testing.
Sometimes I can take some time for Mission Center to load all information. But this is not a dotfiles related issue.
That's why I would like to close this issue again. OK?
