### ISSUE TITLE
[BUG]  Automatically set current wallpaper as SDDM wallpaper.

### ISSUE THREAD

**Issue by kmr-ankitt** [mylinuxforwork/dotfiles#74]
**Describe the bug**
It would be good if the current wallpaper be set as SDDM wallpaper.

**To Reproduce**

**Expected behavior**
SDDM wallpaper should be updated.

**Screenshots**

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mylinuxforwork** [comment]
@kmr-ankitt Setting the current wallpaper automatically as SDDM background is unfortunately not possible. This requires sudo privileges. 

But you can change the background with the Ml4W Welcome app.

![image](https://github.com/user-attachments/assets/9924c4f4-4b22-44a3-a568-365567042165)

Select "set wallpaper"

**Comment by mylinuxforwork** [comment]
https://github.com/mylinuxforwork/dotfiles/wiki/Wallpapers#wallpaper-for-sddm
