### ISSUE TITLE
[BUG] Problems after installation in the top menu

### ISSUE THREAD

**Issue by DeZ4p** [mylinuxforwork/dotfiles#86]
**Describe the bug**

**To Reproduce**
First of all, a special thanks for this wonderful work, because I really couldn't have a comprehensive and good hyperland for several days.  I thank you very much

I installed it completely and without errors, everything is working fine now, but I don't have the top menu.  Even in the second photo, I entered that path in your config file, but it gave me other errors.
What should I do to bring up the top menu without error and complete?

**Screenshots**
![IMG_20240731_024104](https://github.com/user-attachments/assets/6caac255-83a8-407c-aee4-e507ed5feffb)
![IMG_20240731_024057](https://github.com/user-attachments/assets/a789833a-1038-4ef7-9968-bb4f01fd5c2d)

**Distribution (please complete the following information):**
 - parch linux (base arch)

**Additional context**

**Comment by mylinuxforwork** [comment]
It seams that pywal could not be installed successfully.

Can you run `ml4w-diagnosis` in a terminal?

What happens if you enter `wal` in a terminal?

Try `yay -S python-pywal`

**Comment by DeZ4p** [comment]
> It seams that pywal could not be installed successfully.
> 
> Can you run `ml4w-diagnosis` in a terminal?
> 
> What happens if you enter `wal` in a terminal?
> 
> Try `yay -S python-pywal`

The pictures that I have taken say it all, besides, I did not edit any of your files, that is, I did not manipulate it to say that I ruined it!  After the successful installation, I came across this page that I sent you above.  Here are new pictures from wal
![IMG_20240731_091349](https://github.com/user-attachments/assets/7bd3b974-b87a-47e9-8558-bcd4ad2eb06f)

![IMG_20240731_091431](https://github.com/user-attachments/assets/2e15d0e1-fa38-47f6-a659-57c2fa15506b)

![IMG_20240731_091525](https://github.com/user-attachments/assets/646e4d2b-18c2-437e-82be-4f9099769fdb)

![IMG_20240731_091600](https://github.com/user-attachments/assets/fdb2e8e2-de30-4b1b-b8a4-5bb65b57e6b3)

**Comment by DeZ4p** [comment]
Even in your program, I press the Exit hyprland option, it stays like this and does not exit.  What should I do?

**Comment by mylinuxforwork** [comment]
And please make sure that the lastest version of the ML4W Dotfiles 2.9.4 are installed.

**Comment by DeZ4p** [comment]
> And please make sure that the lastest version of the ML4W Dotfiles 2.9.4 are installed.

wal subdirectory is not inside .cache!!  Yes, I installed the latest version.  I don't know what to do, do you want me to reinstall and replace?  I installed the main version but did not install the rolling version.

I did not find any photos in this directory you mentioned.  After that, how can I have the language of my country except EN??

I added a photo myself and clicked according to your instructions: and it turned out to be this:

![Uploading IMG_20240731_135206.jpg…]()
![Uploading IMG_20240731_135241.jpg…]()
![Uploading IMG_20240731_140455.jpg…]()

**Comment by DeZ4p** [comment]
The problem was solved, teacher, with that photo.  Then the EXIT hyrpland button does not work, then the image is not displayed on the back desktop

**Comment by DeZ4p** [comment]
Almost everything works fine
I had problems again, I will create a new topic.

**Comment by DeZ4p** [comment]
All problems were solved
Again, there was a problem or a bug or something, I will open a new topic
**Thank you very much for your help, you are really first class**

**Comment by mylinuxforwork** [comment]
Great news. Thanks for your feedback.
