### ISSUE TITLE
[BUG]  Problem with the "drag and drop"

### ISSUE THREAD

**Issue by RobertKlonowski** [mylinuxforwork/dotfiles#92]
I have a problem with the "drag and drop" function, e.g. when moving a message in the email program, the message ends up in a different folder than I wanted - the left mouse button was released too early? ... When selecting a screenshot, it selects a smaller part - was the left mouse button released too early? ...

**Comment by mylinuxforwork** [comment]
@RobertKlonowski Never had this before. Can you share your configuration: distro, dotfiles version, and email program?

**Comment by RobertKlonowski** [comment]
ArchLinux, kernel 6.10.2-arch1-1

Laptop : ThinkPad T16 gen 1 , CPU: 12th Gen Intel i7-1260P (16) , GPU: NVIDIA GeForce MX550 , GPU: Intel Alder Lake-P GT2

Dotfiles ver : 2.9.4

email : Thunderbird

**Comment by mylinuxforwork** [comment]
I am using Thunderbird as well. I had never any issues like that. Sounds like mouse settings problems. Do you have another DE installed like Plasma or Gnome on top?

**Comment by RobertKlonowski** [comment]
Yes, I have PLASMA installed

**Comment by mylinuxforwork** [comment]
Do you have the same effect with Plasma?

**Comment by RobertKlonowski** [comment]
No, only with Hyprland

**Comment by mylinuxforwork** [comment]
@RobertKlonowski Cannot replicate this issue. Do you have a special zoom factor defined in the monitor settings? It is maybe an Nvidia side effect.

**Comment by RobertKlonowski** [comment]
I use the default monitor settings "monitor=,preferred,auto,1". 
Yesterday I reinstalled ArchLinux with DE Wayland and then installed Dotfiles - now it's OK

**Comment by mylinuxforwork** [comment]
Great. Thanks for your feedback.

**Comment by RobertKlonowski** [comment]
However, the problem is when I connect an external monitor

**Comment by mylinuxforwork** [comment]
Have you checked all options here https://wiki.hyprland.org/Configuring/Monitors/
