### ISSUE TITLE
High gpu memory usage after booting the computer

### ISSUE THREAD

**Issue by Homer-Max** [mylinuxforwork/dotfiles#93]
My laptop is AMD 5800H with integrated graphics，when I boot in, the gpu memory usage rises up to at least 400M,almost 25%.If I watch videos from YouTube with firefox , it will rise up to 1000M.
I've already turn off the animations,what else can I do![1000005258.jpg](https://github.com/user-attachments/assets/1361b5fd-a953-4fa7-8cb3-3963290818a2)

**Comment by mylinuxforwork** [comment]
Will compare it with my system but I have a separate GPU. Can also check on my laptop. @Homer-Max Do you get the values from htop?

**Comment by Homer-Max** [comment]
I turned off all the animations, the usage of GPU memory is still 400MiB, but it rises slowly now. If I don't open firefox to watch youtube, it will remain stable. I think it may be related to the weak decoding capability of the integrated graphics card.
anyway, you did a great job,thanks

**Comment by mylinuxforwork** [comment]
Thanks for testing. It can't come from the configuration of the Dotfiles. 

I will close the issue for now.
