### ISSUE TITLE
[BUG]  Hyprshade unexpected behavior with 'invert colors' option

### ISSUE THREAD

**Issue by RafTeog** [mylinuxforwork/dotfiles#95]
**Describe the bug**
When I activate Hyprshade with the invert colors option selected, the screen flickers and the popup menu that should just inform that it was enable stays in the background. I attached a video of it, it is strange and not easy to explain.

**To Reproduce**
1. Go to "Toggle screen shader" button
2. Click on invert colors option
3. activate it with the default binding

**Expected behavior**
Normal Invert colors behavior.

**Screenshots**
https://drive.google.com/file/d/18jIiKIzLWoPpx5y9MKPYG3EceV0us0WP/view?usp=sharing

Video was too large, I uploaded it to google drive, seemed easier.

**Distribution (please complete the following information):**
 - Arch Linux
 

**Additional context**
Other shader options are fine.

**Comment by mylinuxforwork** [comment]
@RafTeog Thanks for testing. I have just tested it on the latest rolling release of the dotfiles and it's working fine.

Can you try again? Is hyprshade running with the latest version?

**Comment by RafTeog** [comment]
Hey, I sure can try that. I always run on stable branch (and updated system),
I'll switch to rolling release and test it.

**Comment by RafTeog** [comment]
I just switched to rolling and forced the reinstalation, the issue remains :(
Nothing that will keep me from using, I'll just not use that particular filter. So strange. I even recorded another video. All amd hardware here, nothing fancy, just a ryzen 8600g with 32 gb ddr5.

**Comment by RafTeog** [comment]
> hyprshade --version
hyprshade, version 3.2.1 btw

**Comment by mylinuxforwork** [comment]
@RafTeog I could replicate it. But this is not a Dotfiles issue. It is coming from Hyprshade. I was able to fix the effect by switching to another workspace. The weird effect is gone then. And it seams that it's only happening on an empty workspace.

Would you agree that we can close the issue here? You could open an issue on the Hyprshade GitHub.

**Comment by mylinuxforwork** [comment]
@RafTeog Just made another observation. The effect happens with Dunst and Rofi opened. But as said can be fixed by switching to another workspace. But I agree, it's not nice.

**Comment by RafTeog** [comment]
Hey, totally agree with you, good that you found out the source of the issue. I guess we both can help hyprshade a bit with this, but the matter is closed indeed. Thx for all the info.
