### ISSUE TITLE
[BUG] logic error(?) in ~/dotfiles/update.sh

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/dotfiles#98]
**Describe the bug**
When I execute script ~/dotfiles/update.sh from command line, it exits with:

`
| | | |_ __   __| | __ _| |_ ___ 
| | | | '_ \ / _` |/ _` | __/ _ \
| |_| | |_) | (_| | (_| | ||  __/
 \___/| .__/ \__,_|\__,_|\__\___|
      |_|                        

to ML4W Dotfiles 2.9.4
ERROR:: /home/eljejer/Downloads folder not found.`

When I run it from the ML4W Welcome app, this error is not shown

**To Reproduce**
1. Open Sidebar
2. Click on Welcome App
3. Click 3 vertical dots
4. Click 'Update/Reinstall Dotfiles'
5. no error shown, just exits
6. alternative, start ./dotfiles/update.sh from $HOME
7. the error is reported

**Expected behavior**
A normal execution of the script

**Screenshots**
n/a

**Distribution (please complete the following information):**
 - Arch Linux - CachyOS

**Additional context**
the contents of ~/.config/user-dirs.dirs

`
XDG_DESKTOP_DIR="$HOME/"
XDG_DOWNLOAD_DIR="$HOME/downloads"
XDG_TEMPLATES_DIR="$HOME/sjablonen"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/documenten"
XDG_MUSIC_DIR="$HOME/muziek"
XDG_PICTURES_DIR="$HOME/afbeeldingen"
XDG_VIDEOS_DIR="$HOME/video"
XDG_SCREENSHOTS_DIR="$HOME/screenshots"

`

Also, the script reports an update to ML4W Dotfiles 2.9.4 where the ML4W Welcome App reports: Version: 2.9.5RL. This does not seem right.

**Comment by mylinuxforwork** [comment]
Thanks for testing. I will check it.

**Comment by mylinuxforwork** [comment]
@eljejer With the latest 2.9.5RL the update.sh has been moved into ~/dotfiles/.config/ml4w/update.sh Works fine from the Welcome App and when executed directly. Please update to the latest RL.

**Comment by eljejer** [comment]
> @eljejer With the latest 2.9.5RL the update.sh has been moved into ~/dotfiles/.config/ml4w/update.sh Works fine from the Welcome App and when executed directly. Please update to the latest RL.

@mylinuxforwork my version is 2.9.5RL as shown by the welcome app. Yet there is no ~/dotfiles/.config/ directory present. Please advise on how to update.

**Comment by eljejer** [comment]
> @eljejer With the latest 2.9.5RL the update.sh has been moved into ~/dotfiles/.config/ml4w/update.sh Works fine from the Welcome App and when executed directly. Please update to the latest RL.

@mylinuxforwork Because I was not able to update within the Hyprland session, I started a 2nd tty and installed again using the bash <(curl...) command. Now everything looks good. Apart from the fact that the Dotfiles installation created a ~/Downloads directory while ~/.config/user-dirs.dirs hasd eclared XDG_DOWNLOAD_DIR="$HOME/downloads". Does the installation not interprete ~/.config/user-dirs.dirs

**Comment by eljejer** [comment]
@mylinuxforwork I presume I can just mv ~/Downloads/dotfiles/ to ~/downloads ?
